// Pedagogía por capa: por qué existe, qué pasa si falta, analogía y su papel en el flujo.
// Contenido de LabStack — se puede editar sin tocar la lógica de la app.
// Se carga con <script src> (no con fetch) para que la app siga abriéndose
// con doble clic, sin servidor. Cada entrada es una función: devuelve un
// objeto nuevo en cada llamada, igual que hacían los métodos originales.
window.LABSTACK = window.LABSTACK || {};

// --- capas (antes layerMeta()) ---
window.LABSTACK.capas = function () {
    const F=(es,en)=>({es,en});
    return {
      red:{num:1,order:1,hint:F('La base física y lógica: conmuta y enruta el tráfico entre equipos y redes.','The base: switch and route traffic between hosts and networks.'),
        why:F('Sin red no hay comunicación: es el sistema circulatorio que conecta cada equipo, servicio y usuario.','Without a network there is no communication: it is the circulatory system connecting every host, service and user.'),
        miss:F('Nada se comunica: los servidores quedan aislados, como islas sin puentes.','Nothing communicates: servers stay isolated, like islands with no bridges.'),
        anal:F('Como las carreteras y señales de una ciudad: definen por dónde y cómo circula el tráfico.','Like a city\u2019s roads and signs: they define where and how traffic flows.'),
        flow:F('La petición entra por la red: el router la enruta y el switch la entrega al servidor correcto.','The request enters the network: the router routes it and the switch delivers it to the right server.')},
      computo:{num:2,order:2,hint:F('El hardware físico (servidores) donde se ejecuta absolutamente todo.','The physical hardware (servers) where everything actually runs.'),
        why:F('Todo el software necesita un procesador y memoria reales donde ejecutarse: aquí vive el músculo.','All software needs a real CPU and memory to run on: this is where the muscle lives.'),
        miss:F('No hay dónde ejecutar nada: sin hardware, el resto del stack no existe.','There is nowhere to run anything: without hardware, the rest of the stack does not exist.'),
        anal:F('Como el terreno y los cimientos de un edificio: todo lo demás se construye encima.','Like the plot and foundations of a building: everything else is built on top.'),
        flow:F('El servidor físico aporta la CPU y la memoria que atenderán la petición.','The physical server provides the CPU and memory that will serve the request.')},
      almacenamiento:{num:3,order:3,hint:F('Dónde persisten los datos: bloque, archivo y objeto.','Where data persists: block, file and object.'),
        why:F('Los datos deben sobrevivir a reinicios y fallos: el almacenamiento es la memoria a largo plazo.','Data must survive reboots and failures: storage is the long-term memory.'),
        miss:F('Todo se pierde al apagar: sin persistencia no hay datos ni estado.','Everything is lost on shutdown: without persistence there is no data or state.'),
        anal:F('Como los archivadores y el almacén de una empresa: guardan lo que no cabe en la mesa.','Like a company\u2019s filing cabinets and warehouse: they keep what does not fit on the desk.'),
        flow:F('Si la petición necesita datos, el almacenamiento entrega o guarda la información.','If the request needs data, storage serves or saves the information.')},
      virtualizacion:{num:4,order:4,hint:F('Un hipervisor divide un servidor físico en varias máquinas virtuales.','A hypervisor splits one physical server into many virtual machines.'),
        why:F('Un servidor físico desaprovecha recursos: virtualizar lo divide en varias máquinas independientes.','One physical server wastes resources: virtualization splits it into several independent machines.'),
        miss:F('Se desperdicia hardware y se pierde flexibilidad: una sola carga por máquina.','Hardware is wasted and flexibility is lost: one workload per machine.'),
        anal:F('Como dividir una casa grande en varios apartamentos independientes.','Like splitting a large house into several independent apartments.'),
        flow:F('La máquina virtual donde corre el servicio recibe su porción de CPU y memoria.','The virtual machine running the service gets its slice of CPU and memory.')},
      hci:{num:5,order:5,hint:F('Cómputo, almacenamiento y red convergen por software en un clúster.','Compute, storage and network converge by software into one cluster.'),
        why:F('Gestionar cómputo, red y almacenamiento por separado es complejo: la HCI los unifica por software.','Managing compute, network and storage separately is complex: HCI unifies them by software.'),
        miss:F('Vuelves a silos separados: más piezas que administrar y escalar a mano.','You fall back to separate silos: more pieces to manage and scale by hand.'),
        anal:F('Como un electrodoméstico todo-en-uno frente a comprar cada aparato por separado.','Like an all-in-one appliance versus buying each device separately.'),
        flow:F('El clúster hiperconvergido reparte la carga entre sus nodos de forma transparente.','The hyperconverged cluster spreads the load across its nodes transparently.')},
      so:{num:6,order:6,hint:F('El sistema operativo sobre el que corren las aplicaciones.','The operating system the applications run on top of.'),
        why:F('El hardware por sí solo no hace nada: el SO gestiona recursos y da servicios a las aplicaciones.','Hardware alone does nothing: the OS manages resources and provides services to applications.'),
        miss:F('Las aplicaciones no tienen dónde apoyarse ni cómo hablar con el hardware.','Applications have nothing to rest on and no way to talk to the hardware.'),
        anal:F('Como el idioma común y las normas de una oficina: coordinan a todos los que trabajan dentro.','Like the common language and rules of an office: they coordinate everyone working inside.'),
        flow:F('El sistema operativo entrega la petición al proceso o contenedor correspondiente.','The operating system hands the request to the matching process or container.')},
      contenedores:{num:7,order:7,hint:F('Empaqueta la app y sus dependencias de forma ligera y portable.','Package the app and its dependencies in a light, portable way.'),
        why:F('Instalar dependencias a mano es frágil: el contenedor empaqueta la app para que corra igual en todas partes.','Installing dependencies by hand is fragile: the container packages the app so it runs the same everywhere.'),
        miss:F('Vuelve el «en mi máquina funciona»: entornos inconsistentes y despliegues frágiles.','The “works on my machine” problem returns: inconsistent environments and fragile deploys.'),
        anal:F('Como un contenedor de barco: llevas lo mismo dentro sin importar el buque que lo transporte.','Like a shipping container: the contents stay the same no matter which ship carries it.'),
        flow:F('La petición llega al contenedor que ejecuta la aplicación empaquetada.','The request reaches the container running the packaged application.')},
      orquestacion:{num:8,order:8,hint:F('Programa, escala y auto-repara los contenedores en un clúster.','Schedule, scale and self-heal containers across a cluster.'),
        why:F('Con muchos contenedores hace falta un director: Kubernetes los programa, escala y repara solo.','With many containers you need a conductor: Kubernetes schedules, scales and heals them automatically.'),
        miss:F('Nadie reinicia lo caído ni escala ante picos: la operación se vuelve manual y frágil.','Nobody restarts what fails or scales on spikes: operations become manual and fragile.'),
        anal:F('Como el director de una orquesta: coordina a muchos músicos para que suenen a la vez.','Like an orchestra conductor: coordinates many musicians to play in sync.'),
        flow:F('El Service enruta la petición a un Pod sano, que el orquestador mantiene vivo.','The Service routes the request to a healthy Pod, which the orchestrator keeps alive.')},
      datos:{num:9,order:9,hint:F('Servicios de datos con estado que consumen las aplicaciones.','Stateful data services consumed by the applications.'),
        why:F('Las aplicaciones necesitan un lugar consistente para leer y escribir información de negocio.','Applications need a consistent place to read and write business data.'),
        miss:F('La app no recuerda nada entre peticiones: sin base de datos no hay usuarios, pedidos ni historial.','The app remembers nothing between requests: no database means no users, orders or history.'),
        anal:F('Como el archivo central y organizado de una biblioteca frente a papeles sueltos.','Like a library\u2019s central, organized archive versus loose papers.'),
        flow:F('El servicio consulta o guarda en la base de datos para responder la petición.','The service queries or writes to the database to answer the request.')},
      nube:{num:10,order:10,hint:F('Servicios gestionados y bajo demanda de un proveedor externo.','Managed, on-demand services from an external provider.'),
        why:F('Comprar y operar hardware es lento y caro: la nube ofrece recursos gestionados y bajo demanda.','Buying and running hardware is slow and costly: the cloud offers managed, on-demand resources.'),
        miss:F('Asumes todo el datacenter: compra, mantenimiento y escalado quedan a tu cargo.','You take on the whole datacenter: purchase, maintenance and scaling are all on you.'),
        anal:F('Como alquilar electricidad de la red en vez de montar tu propio generador.','Like renting electricity from the grid instead of running your own generator.'),
        flow:F('El servicio gestionado en la nube atiende la petición y escala según la demanda.','The managed cloud service serves the request and scales with demand.')},
      seguridad:{badge:'SEC',hint:F('Transversal: protege cada capa del stack.','Cross-cutting: protects every layer of the stack.'),
        why:F('Cada capa es un punto de ataque: la seguridad protege el tráfico, las identidades y los datos en todas ellas.','Every layer is an attack surface: security protects traffic, identities and data across all of them.'),
        miss:F('Todo queda expuesto: cualquiera podría interceptar el tráfico o acceder sin permiso.','Everything is exposed: anyone could intercept traffic or gain unauthorized access.'),
        anal:F('Como las cerraduras, cámaras y controles de acceso de un edificio: presentes en cada planta.','Like a building\u2019s locks, cameras and access control: present on every floor.'),
        flow:F('El firewall filtra la petición y TLS la cifra antes de dejarla avanzar.','The firewall filters the request and TLS encrypts it before letting it move on.')},
      cicd:{badge:'CI/CD',hint:F('Transversal: automatiza build, test y despliegue.','Cross-cutting: automates build, test and deploy.'),
        why:F('Desplegar a mano es lento y propenso a errores: CI/CD automatiza construir, probar y entregar.','Deploying by hand is slow and error-prone: CI/CD automates build, test and delivery.'),
        miss:F('Cada despliegue es manual y arriesgado: más errores y entregas lentas.','Every deploy is manual and risky: more errors and slower releases.'),
        anal:F('Como una cadena de montaje automatizada que ensambla y revisa cada producto.','Like an automated assembly line that builds and checks each product.'),
        flow:F('La tubería ya construyó y publicó la versión que ahora atiende la petición.','The pipeline already built and shipped the version now serving the request.')},
      iac:{badge:'IaC',hint:F('Transversal: define toda la infraestructura como código.','Cross-cutting: defines all infrastructure as code.'),
        why:F('Configurar servidores a mano no es reproducible: IaC define toda la infraestructura como código versionado.','Configuring servers by hand is not reproducible: IaC defines all infrastructure as versioned code.'),
        miss:F('La infraestructura se vuelve un misterio irrepetible: difícil de recrear o auditar.','Infrastructure becomes an unrepeatable mystery: hard to recreate or audit.'),
        anal:F('Como los planos de un edificio: permiten reconstruirlo idéntico las veces que haga falta.','Like a building\u2019s blueprints: they let you rebuild it identically as many times as needed.'),
        flow:F('Toda la infraestructura que atraviesa la petición se creó a partir de código.','All the infrastructure the request crosses was created from code.')},
      gobernanza:{badge:'GOV',hint:F('Transversal: gobierno, control y cumplimiento normativo.','Cross-cutting: governance, control and compliance.'),
        why:F('Los marcos de gobierno y cumplimiento aseguran que la infraestructura se opera de forma controlada, segura y auditable.','Governance and compliance frameworks ensure the infrastructure is run in a controlled, secure and auditable way.'),
        miss:F('Sin gobierno no hay control ni trazabilidad: fallas auditorías y asumes riesgos ocultos.','Without governance there is no control or traceability: you fail audits and carry hidden risk.'),
        anal:F('Como las normas, auditorías y reglamentos de una empresa: no producen nada, pero garantizan que todo se hace conforme a la ley y las buenas prácticas.','Like a company’s policies, audits and regulations: they produce nothing, but ensure everything follows the law and best practice.'),
        flow:F('Supervisa y audita cada capa para cumplir la normativa.','Oversees and audits every layer to meet compliance.')},
      monitorizacion:{badge:'MON',hint:F('Transversal: observa métricas, logs y salud del sistema.','Cross-cutting: observes metrics, logs and system health.'),
        why:F('No puedes arreglar lo que no ves: la monitorización mide métricas, logs y salud para detectar problemas.','You cannot fix what you cannot see: monitoring measures metrics, logs and health to catch problems.'),
        miss:F('Vuelas a ciegas: los fallos se descubren cuando ya afectan a los usuarios.','You fly blind: failures are discovered only once they already affect users.'),
        anal:F('Como el cuadro de mandos de un coche: velocidad, gasolina y alertas de un vistazo.','Like a car\u2019s dashboard: speed, fuel and warnings at a glance.'),
        flow:F('Cada paso de la petición emite métricas y logs para vigilar la salud del sistema.','Each step of the request emits metrics and logs to watch the system\u2019s health.')},
      mensajeria:{badge:'MSG',hint:F('Transversal: transporta eventos y mensajes entre servicios.','Cross-cutting: carries events and messages between services.'),
        why:F('Acoplar servicios con llamadas directas los hace fr\u00e1giles: la mensajer\u00eda los desacopla enviando eventos que cada servicio consume a su ritmo.','Coupling services with direct calls makes them fragile: messaging decouples them by sending events each service consumes at its own pace.'),
        miss:F('Los servicios dependen unos de otros en tiempo real: si uno cae o se satura, arrastra a los dem\u00e1s.','Services depend on each other in real time: if one fails or overloads, it drags the rest down.'),
        anal:F('Como la centralita de correo de una empresa: dejas la carta en el buz\u00f3n y el destinatario la recoge cuando puede, sin esperar cara a cara.','Like a company mailroom: you drop the letter in the box and the recipient picks it up when they can, with no face-to-face wait.'),
        flow:F('El servicio publica un evento en el bus y otros lo consumen de forma as\u00edncrona, sin bloquear la petici\u00f3n.','The service publishes an event on the bus and others consume it asynchronously, without blocking the request.')},
      backup:{badge:'BKP',hint:F('Transversal: copias y recuperaci\u00f3n de datos y sistemas.','Cross-cutting: backup and recovery of data and systems.'),
        why:F('Los fallos, los borrados y los ataques (ransomware) ocurren: el backup permite recuperar datos y sistemas, y da continuidad al negocio ante un desastre.','Failures, deletions and attacks (ransomware) happen: backup lets you recover data and systems, and keeps the business running after a disaster.'),
        miss:F('Si algo se pierde, se corrompe o se cifra, no hay vuelta atr\u00e1s: p\u00e9rdida de datos irreversible y parada del servicio.','If something is lost, corrupted or encrypted, there is no going back: irreversible data loss and downtime.'),
        anal:F('Como guardar copias de las llaves y los documentos importantes en otro lugar: si pierdes el original, sigues teniendo acceso.','Like keeping copies of your keys and important documents elsewhere: if you lose the original, you still have access.'),
        flow:F('Mientras la petici\u00f3n se atiende, las copias protegen los datos por detr\u00e1s para poder restaurarlos ante un fallo.','While the request is served, backups protect the data in the background so it can be restored after a failure.')},
    };
};
