// Los pasos del modo Kids, en dos partidas: la torre y los ayudantes.
// Contenido de LabStack — se puede editar sin tocar la lógica de la app.
// Se carga con <script src> (no con fetch) para que la app siga abriéndose
// con doble clic, sin servidor. Cada entrada es una función: devuelve un
// objeto nuevo en cada llamada, igual que hacían los métodos originales.
window.LABSTACK = window.LABSTACK || {};

// --- kids (antes kidsSteps()) ---
window.LABSTACK.kids = function () {
    const F=(es,en)=>({es,en});
    return [
      { cat:'red', block:'switch', wrong:['postgres','baremetal'], chapter:1,
        title:F('Los caminos','The roads'),
        say:F('Vamos a construir por dentro una página web. Se empieza por abajo del todo: los caminos por donde viajan los mensajes.','We are going to build the inside of a web page. We start at the very bottom: the roads the messages travel on.'),
        ask:F('¿Qué reparte los mensajes entre ordenadores?','What hands out messages between computers?'),
        hint:F('Busca algo lleno de agujeritos para enchufar cables.','Look for something full of little holes for cables.'),
        why:F('El switch es un cartero rapidísimo: coge cada mensaje y lo lleva al ordenador correcto.','A switch is a super fast postman: it takes each message to the right computer.') },
      { cat:'red', block:'dns', wrong:['postgres','hypervisor'], chapter:1,
        title:F('La agenda de internet','The internet phone book'),
        say:F('En el piso de los caminos hay más cosas. Tú escribes un nombre, pero los ordenadores solo entienden números.','There is more on the roads floor. You type a name, but computers only understand numbers.'),
        ask:F('¿Quién convierte un nombre en un número?','Who turns a name into a number?'),
        hint:F('Su dibujo es una bola del mundo con líneas alrededor.','Its drawing is a globe with lines around it.'),
        why:F('El DNS es la agenda de internet: tú dices el nombre y él te da el número para llegar.','DNS is the internet phone book: you say the name and it gives you the number to get there.') },
      { cat:'red', block:'lb', wrong:['postgres','linux'], chapter:1,
        title:F('El que reparte la cola','The one who splits the queue'),
        say:F('Una cosa más en el piso de los caminos: si entran miles de personas a la vez, no pueden ir todas al mismo sitio.','One more thing on the roads floor: if thousands of people come in at once, they cannot all go to the same place.'),
        ask:F('¿Quién reparte a la gente entre varias máquinas?','Who shares people out between several machines?'),
        hint:F('Su dibujo tiene una flecha que entra y tres que salen.','Its drawing has one arrow going in and three coming out.'),
        why:F('El balanceador es como abrir más cajas en el súper: reparte la cola para que nadie espere de más.','A load balancer is like opening more tills at the shop: it splits the queue so nobody waits too long.') },
      { cat:'computo', block:'baremetal', wrong:['docker','nas'], chapter:1,
        title:F('La máquina que trabaja','The machine that works'),
        say:F('Ya tenemos caminos. Ahora hace falta una máquina de verdad que piense y trabaje.','We have roads now. Now we need a real machine that thinks and works.'),
        ask:F('¿Cuál es el ordenador grande que nunca se apaga?','Which is the big computer that never turns off?'),
        hint:F('Es plano y ancho, con huecos para los discos delante.','It is flat and wide, with slots for disks at the front.'),
        why:F('El servidor es un ordenador que trabaja de día y de noche, sin descansar nunca.','A server is a computer that works day and night and never rests.') },
      { cat:'almacenamiento', block:'nas', wrong:['linux','switch'], chapter:1,
        title:F('El cajón que no olvida','The drawer that never forgets'),
        say:F('Si apagas un ordenador, se le olvida casi todo. Necesitamos un sitio donde guardar las cosas para siempre.','If you switch a computer off, it forgets almost everything. We need a place to keep things forever.'),
        ask:F('¿Dónde se guardan las fotos y los archivos?','Where do photos and files get stored?'),
        hint:F('Parece una torre con cajoncitos apilados.','It looks like a tower with little stacked drawers.'),
        why:F('El NAS es una caja con muchos cajones. Guardas algo dentro y ahí sigue mañana.','A NAS is a box with many drawers. You put something in and it is still there tomorrow.') },
      { cat:'virtualizacion', block:'hypervisor', wrong:['postgres','switch'], chapter:1,
        title:F('Partir la máquina','Splitting the machine'),
        say:F('Un servidor es enorme para un solo programa. ¡Se puede partir en varias máquinas pequeñas!','A server is huge for just one program. It can be split into several small machines!'),
        ask:F('¿Quién parte un ordenador grande en varios pequeños?','Who splits one big computer into several small ones?'),
        hint:F('Dibuja una máquina con tres máquinas pequeñas encima.','It draws one machine with three little machines on top.'),
        why:F('El hipervisor parte una máquina grande en varias, como cortar una tarta en porciones.','A hypervisor splits one big machine into several, like slicing a cake.') },
      { cat:'so', block:'linux', wrong:['nas','docker'], chapter:1,
        title:F('El jefe de dentro','The boss inside'),
        say:F('Dentro de cada máquina hace falta alguien que mande y reparta el trabajo entre todos.','Inside every machine someone has to be in charge and share the work out.'),
        ask:F('¿Quién manda dentro de un ordenador?','Who is in charge inside a computer?'),
        hint:F('Es una ventana negra con letras verdes.','It is a black window with green letters.'),
        why:F('Linux es el jefe: decide quién usa la memoria y cuándo, para que nadie se pelee.','Linux is the boss: it decides who uses the memory and when, so nobody fights.') },
      { cat:'contenedores', block:'docker', wrong:['baremetal','postgres'], chapter:1,
        title:F('Cajas que viajan','Travelling boxes'),
        say:F('Para llevar un programa de un ordenador a otro, lo metemos en una caja con todo lo que necesita dentro.','To move a program from one computer to another, we pack it in a box with everything it needs.'),
        ask:F('¿Qué mete el programa en una caja para que viaje?','What packs the program into a box so it can travel?'),
        hint:F('Son cajas apiladas, como las de un barco.','They are stacked boxes, like the ones on a ship.'),
        why:F('Docker mete el programa en una caja. Lo lleves donde lo lleves, funciona igual.','Docker packs the program in a box. Wherever you take it, it works the same.') },
      { cat:'orquestacion', block:'k8s', wrong:['nas','dns'], chapter:1,
        title:F('El jefe de las cajas','The boss of the boxes'),
        say:F('Cuando hay muchísimas cajas hace falta alguien que las coloque, las cuente y cambie las que se rompen.','When there are loads of boxes, someone has to place them, count them and replace the broken ones.'),
        ask:F('¿Quién manda sobre todas las cajas a la vez?','Who is in charge of all the boxes at once?'),
        hint:F('Su dibujo es un hexágono con puntitos alrededor, como una rueda.','Its drawing is a hexagon with dots around it, like a wheel.'),
        why:F('Kubernetes es el jefe de obra: reparte las cajas entre las máquinas y, si una se cae, pone otra enseguida.','Kubernetes is the site foreman: it shares the boxes out and, if one falls, it puts another one up straight away.') },
      { cat:'datos', block:'postgres', wrong:['switch','hypervisor'], chapter:1,
        title:F('La libreta gigante','The giant notebook'),
        say:F('La página tiene que acordarse de cosas: nombres, puntos, mensajes que le escribes...','The page has to remember things: names, points, messages you write to it...'),
        ask:F('¿Dónde se apunta todo para no olvidarlo?','Where is everything written down so it is not forgotten?'),
        hint:F('Tiene forma de tarta redonda de varios pisos.','It is shaped like a round cake with several layers.'),
        why:F('La base de datos es una libreta gigante: lo apunta todo y lo encuentra en un segundo.','A database is a giant notebook: it writes everything down and finds it in a second.') },
      { cat:'nube', block:'cloudvm', wrong:['nas','linux'], chapter:1,
        title:F('La nube','The cloud'),
        say:F('¿Y si no quieres cuidar tú las máquinas? Se las alquilas a otra empresa y ellos las cuidan.','What if you do not want to look after the machines? You rent them from another company and they look after them.'),
        ask:F('¿Qué son ordenadores que están lejos y alquilas?','What are computers that live far away and you rent?'),
        hint:F('Su dibujo es una nube con un rayo dentro.','Its drawing is a cloud with a lightning bolt inside.'),
        why:F('En la nube usas ordenadores de otros. Tú solo pides, y ellos se encargan de todo.','In the cloud you use other people’s computers. You just ask, and they take care of everything.') },
      { cat:'mensajeria', block:'rabbitmq', wrong:['nas','hypervisor'], chapter:2, side:true,
        title:F('El buzón de recados','The message box'),
        say:F('La torre ya está entera. Ahora faltan los ayudantes: no viven en ningún piso, pero sin ellos nada va bien.','The tower is finished. Now for the helpers: they do not live on any floor, but without them nothing works well.'),
        ask:F('¿Dónde se dejan los recados hasta que alguien los recoge?','Where are messages left until someone picks them up?'),
        hint:F('Su dibujo son cartas que entran en una caja con ranuras.','Its drawing is letters going into a box with slots.'),
        why:F('RabbitMQ es un buzón: dejas el recado y sigues con lo tuyo, y el otro lo recoge cuando puede.','RabbitMQ is a message box: you drop the note and carry on, and the other side picks it up when it can.') },
      { cat:'seguridad', block:'firewall', wrong:['nas','k8s'], chapter:2, side:true,
        title:F('El portero','The doorkeeper'),
        say:F('Otro ayudante, y este vigila la puerta: no todo el que llama a la torre puede entrar.','Another helper, and this one guards the door: not everyone who knocks on the tower gets in.'),
        ask:F('¿Quién decide quién puede entrar y quién no?','Who decides who gets in and who does not?'),
        hint:F('Su dibujo es un muro de ladrillos con una llama encima.','Its drawing is a brick wall with a flame on top.'),
        why:F('El firewall es el portero: mira quién llama a la puerta y solo deja pasar a los de confianza.','A firewall is the doorkeeper: it checks who is knocking and only lets the trusted ones in.') },
      { cat:'monitorizacion', block:'grafana', wrong:['docker','dns'], chapter:2, side:true,
        title:F('El que vigila','The watcher'),
        say:F('Si algo va mal dentro de la torre, alguien tiene que darse cuenta antes de que se rompa del todo.','If something goes wrong inside the tower, someone has to notice before it breaks completely.'),
        ask:F('¿Quién mira todo el rato si la torre está bien?','Who keeps watching to see if the tower is doing fine?'),
        hint:F('Su dibujo es una pantalla con una gráfica dentro.','Its drawing is a screen with a chart inside.'),
        why:F('Grafana es como el salpicadero de un coche: enseña en dibujos si todo va bien o si algo se está calentando.','Grafana is like a car dashboard: it shows in pictures whether all is well or something is overheating.') },
      { cat:'backup', block:'backup', wrong:['switch','postgres'], chapter:2, side:true,
        title:F('La copia por si acaso','The just-in-case copy'),
        say:F('¿Y si un día se rompe algo y se pierde todo lo guardado? Por eso siempre hay una copia aparte.','And what if one day something breaks and everything saved is lost? That is why there is always a spare copy.'),
        ask:F('¿Qué guarda una copia de todo por si se pierde?','What keeps a copy of everything in case it gets lost?'),
        hint:F('Su dibujo es un cartucho de cinta con dos ruedas.','Its drawing is a tape cartridge with two reels.'),
        why:F('La copia de seguridad es tu red de seguridad: si algo se pierde, se vuelve a poner como estaba.','A backup is your safety net: if something is lost, it goes back to how it was.') },
      { cat:'iac', block:'terraform', wrong:['switch','postgres'], chapter:2, side:true,
        title:F('Las instrucciones de montaje','The building instructions'),
        say:F('Montar la torre entera a mano es lentísimo, y siempre se te acaba olvidando algo.','Building the whole tower by hand is really slow, and you always end up forgetting something.'),
        ask:F('¿Qué guarda por escrito cómo se monta la torre entera?','What writes down how the whole tower is built?'),
        hint:F('Su dibujo es una hoja con una cuadrícula dibujada.','Its drawing is a sheet of paper with a grid on it.'),
        why:F('Terraform es como las instrucciones de un Lego: están escritas, y si la torre se rompe, la vuelves a montar igualita.','Terraform is like Lego instructions: they are written down, so if the tower breaks you can build it again exactly the same.') },
      { cat:'cicd', block:'pipeline', wrong:['nas','dns'], chapter:2, side:true,
        title:F('La cadena de montaje','The assembly line'),
        say:F('Y cuando alguien mejora el programa hay que probarlo y publicarlo. ¿A mano cada vez? Uf.','And when someone improves the program it has to be tested and published. By hand every time? Ugh.'),
        ask:F('¿Qué prueba y publica los cambios él solito?','What tests and publishes the changes all by itself?'),
        hint:F('Su dibujo son tres cajas seguidas con flechas entre ellas.','Its drawing is three boxes in a row with arrows between them.'),
        why:F('El pipeline es una cadena de montaje: coge lo nuevo, lo prueba y, si está bien, lo publica. Sin que nadie toque nada.','A pipeline is an assembly line: it takes what is new, tests it and, if it is fine, publishes it. Without anyone touching a thing.') },
    ];
};
