// Catálogo de tecnologías: categorías, piezas, fichas, iconos y dimensionado.
// Contenido de LabStack — se puede editar sin tocar la lógica de la app.
// Se carga con <script src> (no con fetch) para que la app siga abriéndose
// con doble clic, sin servidor. Cada entrada es una función: devuelve un
// objeto nuevo en cada llamada, igual que hacían los métodos originales.
window.LABSTACK = window.LABSTACK || {};

// --- categorias (antes catsBase()) ---
window.LABSTACK.categorias = function () {
    return [
      // Familia · Infraestructura física (fríos: azul / acero / cian)
      { id:'red', color:'#3b82f6', fam:'phys', name:{es:'Redes',en:'Networking'} },
      { id:'computo', color:'#64748b', fam:'phys', name:{es:'Cómputo físico',en:'Bare-metal compute'} },
      { id:'almacenamiento', color:'#06b6d4', fam:'phys', name:{es:'Almacenamiento',en:'Storage'} },
      // Familia · Plataforma / virtualización (verdes: teal / emerald / green)
      { id:'virtualizacion', color:'#0d9488', fam:'plat', name:{es:'Virtualización',en:'Virtualization'} },
      { id:'hci', color:'#10b981', fam:'plat', name:{es:'HCI · Nutanix',en:'HCI · Nutanix'} },
      { id:'so', color:'#22c55e', fam:'plat', name:{es:'Sistema operativo',en:'Operating system'} },
      // Familia · Aplicación / runtime (ámbar)
      { id:'contenedores', color:'#f59e0b', fam:'app', name:{es:'Contenedores · Docker',en:'Containers · Docker'} },
      { id:'orquestacion', color:'#d97706', fam:'app', name:{es:'Orquestación · K8s',en:'Orchestration · K8s'} },
      { id:'mensajeria', color:'#f97316', fam:'app', name:{es:'Mensajería · Eventos',en:'Messaging · Events'} },
      // Familia · Datos (rosa)
      { id:'datos', color:'#ec4899', fam:'data', name:{es:'Bases de datos',en:'Databases'} },
      // Familia · Nube (celeste)
      { id:'nube', color:'#38bdf8', fam:'cloud', name:{es:'Nube',en:'Cloud'} },
      // Familia · Operación transversal (púrpuras)
      { id:'seguridad', color:'#7c3aed', fam:'ops', name:{es:'Seguridad',en:'Security'} },
      { id:'cicd', color:'#9333ea', fam:'ops', name:{es:'CI/CD',en:'CI/CD'} },
      { id:'iac', color:'#c026d3', fam:'ops', name:{es:'IaC · Terraform',en:'IaC · Terraform'} },
      { id:'monitorizacion', color:'#d946ef', fam:'ops', name:{es:'Monitorización',en:'Monitoring'} },
      { id:'gobernanza', color:'#a855f7', fam:'ops', name:{es:'Gobierno · Cumplimiento',en:'Governance · Compliance'} },
      { id:'backup', color:'#6d28d9', fam:'ops', name:{es:'Backup · Recuperación',en:'Backup · Recovery'} },
    ];
};

// --- iconos (antes pieceIconsBase()) ---
window.LABSTACK.iconos = function () {
    // iconos propios por pieza (formas simples estilo Lucide); las que falten heredan el de su categoría
    return {
      switch:'M4 7h16M8 7 5 4M4 17h16M16 17l3 3', lb:'M12 3v4M12 17v4M4 12h4M16 12h4M9 9h6v6H9z', dns:'M12 2a10 10 0 100 20 10 10 0 000-20zM2 12h20M12 2a15 15 0 010 20 15 15 0 010-20z', vlan:'M3 5h8v6H3zM13 13h8v6h-8zM7 11v2M7 13h10',
      baremetal:'M4 4h16v6H4zM4 14h16v6H4zM7 7h.01M7 17h.01', rack:'M5 3h14v18H5zM5 8h14M5 13h14M8 5.5h.01M8 10.5h.01M8 15.5h.01',
      san:'M4 6h16v5H4zM4 13h16v5H4zM7 8.5h6M7 15.5h6M17 8.5h.01M17 15.5h.01', nas:'M3 7l9-4 9 4-9 4-9-4zM3 7v10l9 4M21 7v10l-9 4', raid:'M4 5c0-1.1 3.6-2 8-2s8 .9 8 2M4 5v14c0 1.1 3.6 2 8 2s8-.9 8-2V5M4 12c0 1.1 3.6 2 8 2s8-.9 8-2', objstore:'M21 8v8l-9 5-9-5V8l9-5 9 5zM3 8l9 5 9-5M12 13v8',
      hypervisor:'M12 2l9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 17l9 5 9-5', kvm:'M4 4h16v16H4zM9 9h6v6H9zM9 1v3M15 1v3M9 20v3M15 20v3M1 9h3M1 15h3M20 9h3M20 15h3', vm:'M3 4h18v12H3zM8 20h8M12 16v4',
      linux:'M4 17l5-5-5-5M12 19h8', winserver:'M3 5h8v8H3zM13 5h8v8h-8zM3 15h8v6H3zM13 15h8v6h-8z',
      docker:'M4 12h4v3H4zM9 12h4v3H9zM14 12h4v3h-4zM9 8h4v3H9zM4 15c0 3 3 4 7 4s9-1 10-5', image:'M3 5h18v14H3zM3 15l5-4 4 3 3-2 6 5', container:'M21 8v8l-9 5-9-5V8l9-5 9 5zM3 8l9 5 9-5M12 13v8',
      pod:'M12 3a4 4 0 100 8 4 4 0 000-8zM5 20a4 4 0 100-8 4 4 0 000 8zM19 20a4 4 0 100-8 4 4 0 000 8z', service:'M18 5a3 3 0 100-6 3 3 0 000 6zM6 15a3 3 0 100-6 3 3 0 000 6zM18 21a3 3 0 100-6 3 3 0 000 6zM8.6 13.5l6.8 4M15.4 6.5l-6.8 4', ingress:'M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4M10 17l5-5-5-5M15 12H3', deployment:'M12 2v14M6 8l6-6 6 6M5 22h14',
      postgres:'M12 8c4.4 0 8-1.3 8-3s-3.6-3-8-3-8 1.3-8 3 3.6 3 8 3zM4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6', redis:'M4 6l8-3 8 3-8 3-8-3zM4 6v5l8 3 8-3V6M4 11v5l8 3 8-3v-5', mongodb:'M12 2c3 4 3 12 0 20-3-8-3-16 0-20zM12 2v20',
      serverless:'M13 2L4 14h7l-2 8 9-12h-7l2-8z', cdn:'M12 2a10 10 0 100 20 10 10 0 000-20zM2 12h20M12 2a15 15 0 010 20 15 15 0 010-20z',
      firewall:'M4 4h16v16H4zM4 9h16M4 14h16M9 4v5M15 9v5M9 14v6', tls:'M5 11h14v10H5zM8 11V7a4 4 0 018 0v4', vpn:'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4', encryption:'M5 11h14v10H5zM8 11V7a4 4 0 018 0v4M12 15v2', iam:'M16 7a4 4 0 11-8 0 4 4 0 018 0zM4 21v-2a4 4 0 014-4h4M17 17l2 2 4-4',
      git:'M6 3v12M18 9a3 3 0 100-6 3 3 0 000 6zM6 21a3 3 0 100-6 3 3 0 000 6zM18 9a9 9 0 01-9 9', pipeline:'M3 12h4l3-8 4 16 3-8h4', registry:'M21 8v8l-9 5-9-5V8l9-5 9 5zM3 8l9 5 9-5M7 6l10 5', gitops:'M4 12a8 8 0 018-8 8 8 0 016 3M20 12a8 8 0 01-8 8 8 8 0 01-6-3M16 4h4v4M8 20H4v-4', actions:'M5 3l14 9-14 9V3z',
      terraform:'M9 4l6 3v6l-6-3V4zM15 7l6 3v6l-6-3V7zM9 11l6 3v6l-6-3v-6z', ansible:'M12 2l9 20H3L12 2zM12 8l4 9',
      prometheus:'M12 2a7 7 0 00-7 7c0 3 2 4 2 7h10c0-3 2-4 2-7a7 7 0 00-7-7zM9 19h6M10 22h4', grafana:'M3 3v18h18M7 15l3-4 3 2 4-6', alerts:'M6 8a6 6 0 1112 0c0 7 3 9 3 9H3s3-2 3-9M10 21a2 2 0 004 0', logs:'M8 3H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2h-3M8 8h8M8 12h8M8 16h5', tracing:'M4 6a2 2 0 100-4 2 2 0 000 4zM4 6v6a2 2 0 002 2h6M12 18a2 2 0 100 4 2 2 0 000-4zM12 14v4M20 6a2 2 0 100-4 2 2 0 000 4zM20 6v4a2 2 0 01-2 2h-2',
      coso:'M12 3l8 4v10l-8 4-8-4V7l8-4zM4 7l8 4 8-4M12 11v10', iso27001:'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4', cobit:'M12 2a10 10 0 100 20 10 10 0 000-20zM12 8a4 4 0 100 8 4 4 0 000-8zM12 11h.01',
      kafka:'M5 3v18M5 12h5M12 6a2 2 0 100 4 2 2 0 000-4zM12 8H10M12 14a2 2 0 100 4 2 2 0 000-4zM12 16H10M18 9a2 2 0 100 4 2 2 0 000-4zM18 11h-6', rabbitmq:'M4 10h4V4h4v6h4V7h4v13H4zM11 15h2', nats:'M4 6h16v12H4zM7 9l5 4 5-4', elasticsearch:'M11 4a7 7 0 100 14 7 7 0 000-14zM16 16l4 4M8 11h6', cassandra:'M4 6c0-1.7 3.6-3 8-3s8 1.3 8 3-3.6 3-8 3-8-1.3-8-3zM4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3',
      istio:'M12 3l7 15H5zM12 3v15M8 14h8', kong:'M4 12h6M14 8l-4 4 4 4M20 5v14M14 8l6-3M14 16l6 3', vault:'M4 4h16v16H4zM12 9a3 3 0 100 6 3 3 0 000-6zM12 15v3M8 8h.01M16 8h.01', argocd:'M12 2a10 10 0 100 20 10 10 0 000-20zM12 7v5l3 2M16 4l1 3-3-1',
      veeam:'M4 6c0-1.7 3.6-3 8-3s8 1.3 8 3-3.6 3-8 3-8-1.3-8-3zM4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6M4 12c0 1.7 3.6 3 8 3M9 15l3 3 3-3M12 11v7', zabbix:'M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7zM12 15a3 3 0 100-6 3 3 0 000 6z',
      backup:'M21 12a9 9 0 11-2.64-6.36M21 3v5h-5', snapshot:'M4 6h4l2-2h4l2 2h4v13H4zM12 16a3.5 3.5 0 100-7 3.5 3.5 0 000 7z', replication:'M4 7h10l-2-2M4 7l2 2M20 17H10l2 2M20 17l-2-2M6 3v4M18 21v-4', velero:'M12 2l8.5 5v10L12 22 3.5 17V7L12 2zM9 12l2 2 4-4',
    };
};

// --- fichas (antes extrasBase()) ---
window.LABSTACK.fichas = function () {
    // info ampliada por pieza: one=en una frase, use=cuándo usarla, alt=alternativas
    const F=(es,en)=>({es,en});
    return {
      router:{ one:F('Decide por qué camino enviar cada paquete entre redes.','Decides which path each packet takes between networks.'), use:F('Cuando necesitas conectar dos redes o subredes distintas.','When you must connect two different networks or subnets.'), alt:'Cisco IOS, MikroTik, pfSense, VyOS' },
      switch:{ one:F('Entrega tramas al equipo correcto dentro de una misma LAN.','Delivers frames to the right host within one LAN.'), use:F('Para conectar muchos equipos dentro de la misma red local.','To wire many hosts within the same local network.'), alt:'Cisco Catalyst, Aruba, Juniper' },
      lb:{ one:F('Reparte las peticiones entre varios servidores.','Spreads requests across several servers.'), use:F('Cuando un solo servidor no basta o quieres alta disponibilidad.','When one server is not enough or you want high availability.'), alt:'HAProxy, NGINX, Envoy, AWS ELB' },
      dns:{ one:F('Traduce nombres (ejemplo.com) a direcciones IP.','Translates names (example.com) into IP addresses.'), use:F('Siempre que quieras usar nombres en vez de IP.','Whenever you want names instead of raw IPs.'), alt:'BIND, CoreDNS, Route 53, Cloudflare' },
      vlan:{ one:F('Divide una red física en segmentos aislados.','Splits one physical network into isolated segments.'), use:F('Para separar tráfico (producción, invitados, gestión).','To separate traffic (production, guest, management).'), alt:'Subredes, VXLAN, segmentación SDN' },
      baremetal:{ one:F('El hardware físico real donde corre todo.','The real physical hardware everything runs on.'), use:F('Cuando quieres máximo rendimiento sin capa de abstracción.','When you want top performance with no abstraction.'), alt:'Máquinas virtuales, instancias cloud' },
      rack:{ one:F('Chasis que agrupa varios servidores físicos.','Chassis grouping several physical servers.'), use:F('Para crecer el datacenter añadiendo nodos.','To grow the datacenter by adding nodes.'), alt:'Blade servers, chasis hiperconvergido' },
      san:{ one:F('Almacenamiento por bloques sobre una red dedicada.','Block storage over a dedicated network.'), use:F('Para bases de datos y VM que exigen baja latencia.','For databases and VMs needing low latency.'), alt:'NAS, almacenamiento local NVMe' },
      nas:{ one:F('Comparte carpetas por la red a nivel de archivo.','Shares folders over the network at file level.'), use:F('Para documentos y respaldos compartidos entre equipos.','For documents and backups shared across hosts.'), alt:'SAN, object storage, SMB/NFS' },
      raid:{ one:F('Combina varios discos por redundancia o velocidad.','Combines disks for redundancy or speed.'), use:F('Para tolerar el fallo de un disco sin perder datos.','To survive a disk failure without data loss.'), alt:'ZFS, LVM, replicación por software' },
      objstore:{ one:F('Guarda datos como objetos accesibles por API.','Stores data as objects accessed via API.'), use:F('Para archivos estáticos, backups y datos no estructurados.','For static files, backups and unstructured data.'), alt:'Amazon S3, MinIO, Ceph, Backblaze' },
      hypervisor:{ one:F('Crea varias máquinas virtuales sobre un servidor.','Runs many virtual machines on one server.'), use:F('Para aprovechar un servidor grande con varias cargas.','To pack several workloads onto one big server.'), alt:'VMware ESXi, Hyper-V, Proxmox, KVM' },
      kvm:{ one:F('Convierte el kernel de Linux en un hipervisor.','Turns the Linux kernel into a hypervisor.'), use:F('Virtualización nativa y open source en Linux.','Native, open-source virtualization on Linux.'), alt:'VMware, Hyper-B, Xen' },
      vm:{ one:F('Un ordenador completo emulado, con su propio SO.','A full emulated computer with its own OS.'), use:F('Cuando necesitas aislamiento fuerte o un SO distinto.','When you need strong isolation or a different OS.'), alt:'Contenedores, funciones serverless' },
      ahv:{ one:F('El hipervisor propio de Nutanix, sin licencia aparte.','Nutanix built-in hypervisor, no extra license.'), use:F('En clústeres Nutanix HCI.','In Nutanix HCI clusters.'), alt:'VMware ESXi, Hyper-V' },
      prism:{ one:F('La consola única de gestión de Nutanix.','Nutanix single management console.'), use:F('Para administrar cómputo, red y disco en un panel.','To manage compute, network and storage in one pane.'), alt:'vCenter, OpenStack Horizon' },
      hcinode:{ one:F('Nodo que aporta cómputo y almacenamiento a la vez.','Node contributing both compute and storage.'), use:F('En hiperconvergencia, para escalar de forma lineal.','In hyperconvergence, to scale linearly.'), alt:'Nodo de cómputo + SAN separados' },
      linux:{ one:F('Sistema operativo abierto que domina servidores y nube.','Open OS that dominates servers and the cloud.'), use:F('Base de casi todo el backend moderno.','The base of almost all modern backend.'), alt:'Windows Server, BSD' },
      winserver:{ one:F('SO de servidor de Microsoft con Active Directory.','Microsoft server OS with Active Directory.'), use:F('Entornos corporativos con .NET e identidades AD.','Enterprise environments with .NET and AD identity.'), alt:'Linux, Samba AD' },
      docker:{ one:F('Empaqueta una app y sus dependencias, portable.','Packages an app and its dependencies, portable.'), use:F('Para que corra igual en dev y en producción.','So it runs the same in dev and prod.'), alt:'Podman, containerd, LXC' },
      image:{ one:F('Plantilla inmutable de la que nacen los contenedores.','Immutable template that containers are born from.'), use:F('Para versionar y distribuir tu aplicación.','To version and ship your application.'), alt:'OCI images, buildpacks' },
      container:{ one:F('Instancia en ejecución de una imagen.','A running instance of an image.'), use:F('La unidad ligera donde corre tu servicio.','The lightweight unit your service runs in.'), alt:'VM, proceso del host' },
      k8s:{ one:F('Programa, escala y auto-repara contenedores.','Schedules, scales and self-heals containers.'), use:F('Cuando tienes muchos contenedores que orquestar.','When you have many containers to orchestrate.'), alt:'Docker Swarm, Nomad, ECS' },
      pod:{ one:F('La unidad mínima que despliega Kubernetes.','The smallest unit Kubernetes deploys.'), use:F('Agrupa uno o varios contenedores acoplados.','Groups one or more tightly-coupled containers.'), alt:'Task (ECS), contenedor suelto' },
      deployment:{ one:F('Mantiene N réplicas de un pod y las actualiza.','Keeps N pod replicas and rolls out updates.'), use:F('Para servicios sin estado con despliegue controlado.','For stateless services with controlled rollout.'), alt:'StatefulSet, DaemonSet' },
      service:{ one:F('Da una dirección estable a un grupo de pods.','Gives a stable address to a set of pods.'), use:F('Para hablar con pods que van y vienen.','To reach pods that come and go.'), alt:'Ingress, service mesh (Istio)' },
      ingress:{ one:F('Enruta el tráfico HTTP externo hacia los servicios.','Routes external HTTP traffic into services.'), use:F('Para exponer tus apps al exterior por dominio/ruta.','To expose apps by domain/path.'), alt:'API Gateway, LoadBalancer directo' },
      postgres:{ one:F('Base de datos relacional potente y fiable.','Powerful, reliable relational database.'), use:F('Para datos con relaciones y transacciones (ACID).','For relational, transactional (ACID) data.'), alt:'MySQL, MariaDB, SQL Server' },
      redis:{ one:F('Almacén clave-valor en memoria, muy rápido.','In-memory key-value store, very fast.'), use:F('Para caché, sesiones y colas.','For caching, sessions and queues.'), alt:'Memcached, KeyDB, Valkey' },
      mongodb:{ one:F('Base de datos de documentos flexible (NoSQL).','Flexible document database (NoSQL).'), use:F('Para datos semiestructurados y esquemas cambiantes.','For semi-structured data and evolving schemas.'), alt:'CouchDB, DynamoDB, Firestore' },
      serverless:{ one:F('Ejecuta funciones bajo demanda, sin gestionar servidores.','Runs functions on demand, no servers to manage.'), use:F('Para cargas esporádicas o event-driven.','For spiky or event-driven workloads.'), alt:'AWS Lambda, Cloud Functions, Azure Functions' },
      cdn:{ one:F('Sirve contenido desde el nodo más cercano al usuario.','Serves content from the node nearest the user.'), use:F('Para acelerar archivos estáticos globalmente.','To speed up static files globally.'), alt:'Cloudflare, Fastly, CloudFront' },
      managedk8s:{ one:F('Kubernetes gestionado por el proveedor cloud.','Kubernetes managed by the cloud provider.'), use:F('K8s sin operar el plano de control tú mismo.','K8s without running the control plane yourself.'), alt:'EKS, GKE, AKS' },
      firewall:{ one:F('Filtra qué tráfico entra y sale de la red.','Filters what traffic enters and leaves the network.'), use:F('Para reducir la superficie de ataque en el perímetro.','To shrink the attack surface at the edge.'), alt:'Security Groups, WAF, iptables' },
      tls:{ one:F('Cifra el tráfico entre cliente y servidor.','Encrypts traffic between client and server.'), use:F('Siempre que expongas servicios por HTTPS.','Whenever you expose services over HTTPS.'), alt:'mTLS, Let’s Encrypt, cert-manager' },
      vpn:{ one:F('Túnel cifrado para acceso remoto seguro.','Encrypted tunnel for secure remote access.'), use:F('Para conectar redes o usuarios de forma privada.','To connect networks or users privately.'), alt:'WireGuard, OpenVPN, IPsec' },
      encryption:{ one:F('Protege los datos en reposo cifrándolos.','Protects data at rest by encrypting it.'), use:F('Para que un disco robado no revele nada.','So a stolen disk reveals nothing.'), alt:'LUKS, KMS, SOPS' },
      iam:{ one:F('Gestiona identidades y qué puede hacer cada una.','Manages identities and what each one may do.'), use:F('Para dar permisos mínimos a usuarios y servicios.','To grant least-privilege to users and services.'), alt:'AWS IAM, Keycloak, Okta' },
      git:{ one:F('Control de versiones distribuido del código.','Distributed version control for code.'), use:F('Base de todo flujo de trabajo moderno.','The base of every modern workflow.'), alt:'Mercurial, SVN' },
      pipeline:{ one:F('Automatiza build, test y despliegue.','Automates build, test and deploy.'), use:F('Para entregar cambios rápido y sin errores manuales.','To ship changes fast without manual errors.'), alt:'GitHub Actions, GitLab CI, Jenkins' },
      registry:{ one:F('Almacén de imágenes de contenedor.','Store of container images.'), use:F('Para guardar y distribuir tus imágenes.','To store and distribute your images.'), alt:'Docker Hub, Harbor, GHCR, ECR' },
      gitops:{ one:F('El estado deseado vive en Git y se aplica solo.','Desired state lives in Git and self-applies.'), use:F('Para desplegar declarativamente desde el repo.','To deploy declaratively from the repo.'), alt:'Argo CD, Flux' },
      actions:{ one:F('Ejecuta tu CI/CD junto al repositorio.','Runs your CI/CD next to the repo.'), use:F('Para automatizar en cada push o PR.','To automate on each push or PR.'), alt:'GitLab CI, CircleCI, Travis' },
      terraform:{ one:F('Define toda la infraestructura como código.','Defines all infrastructure as code.'), use:F('Para crear entornos reproducibles y versionados.','To build reproducible, versioned environments.'), alt:'Pulumi, OpenTofu, CloudFormation' },
      ansible:{ one:F('Configura servidores de forma declarativa.','Configures servers declaratively.'), use:F('Para provisionar y configurar sin agentes.','To provision and configure without agents.'), alt:'Chef, Puppet, Salt' },
      prometheus:{ one:F('Recoge métricas de tu sistema en el tiempo.','Collects time-series metrics of your system.'), use:F('Para medir salud, uso y rendimiento.','To measure health, usage and performance.'), alt:'VictoriaMetrics, Datadog, InfluxDB' },
      grafana:{ one:F('Visualiza métricas en paneles y gráficos.','Visualizes metrics in dashboards and charts.'), use:F('Para ver de un vistazo el estado del sistema.','To see system state at a glance.'), alt:'Kibana, Chronograf' },
      alerts:{ one:F('Avisa cuando algo se sale de lo normal.','Notifies when something goes out of bounds.'), use:F('Para enterarte de un problema antes que los usuarios.','To learn of an issue before users do.'), alt:'Alertmanager, PagerDuty, Opsgenie' },
      logs:{ one:F('Registra qué ocurre para poder investigarlo.','Records what happens so you can investigate.'), use:F('Para depurar incidencias y auditar.','To debug incidents and audit.'), alt:'ELK, Loki, Splunk' },
      tracing:{ one:F('Sigue una petición a través de todos los servicios.','Follows a request across all services.'), use:F('Para encontrar el cuello de botella en microservicios.','To find the bottleneck in microservices.'), alt:'Jaeger, Tempo, Zipkin' },
      dockerfile:{ one:F('Receta de texto para construir una imagen.','Text recipe to build an image.'), use:F('Para definir cómo se empaqueta tu aplicación.','To define how your app is packaged.'), alt:'Buildpacks, Nixpacks' },
      compose:{ one:F('Define y arranca varios contenedores juntos.','Defines and runs several containers together.'), use:F('Para levantar tu stack completo en local.','To spin up your whole stack locally.'), alt:'Docker Swarm, Tilt, Kompose' },
      k8snode:{ one:F('Máquina del clúster donde Kubernetes coloca pods.','Cluster machine where Kubernetes places pods.'), use:F('Aporta CPU y memoria al clúster.','Provides CPU and memory to the cluster.'), alt:'Nodo gestionado (EKS/GKE/AKS)' },
      cloudvm:{ one:F('Máquina virtual alquilada en la nube.','A virtual machine rented in the cloud.'), use:F('Para cómputo bajo demanda sin comprar hardware.','For on-demand compute without buying hardware.'), alt:'EC2, Compute Engine, Droplet' },
      mysql:{ one:F('Base de datos relacional muy popular.','Very popular relational database.'), use:F('Para datos relacionales en web y aplicaciones.','For relational data in web and apps.'), alt:'PostgreSQL, MariaDB, SQL Server' },
      tfstate:{ one:F('Registro de lo que Terraform ha creado.','Record of what Terraform has created.'), use:F('Para conocer el estado real de la infraestructura.','To track the real infrastructure state.'), alt:'Backend remoto (S3), Terraform Cloud' },
      module:{ one:F('Bloque reutilizable de infraestructura como código.','Reusable infrastructure-as-code block.'), use:F('Para no repetir configuración entre entornos.','To avoid repeating config across environments.'), alt:'Terraform Registry, submódulos' },
      coso:{ one:F('Estructura para el control interno y el riesgo.','Structure for internal control and risk.'), use:F('Para dar fiabilidad y control a los procesos del negocio.','To give reliability and control to business processes.'), alt:'COSO ERM, ISO 31000' },
      iso27001:{ one:F('Sistema certificable de seguridad de la información.','Certifiable information-security system.'), use:F('Para demostrar que gestionas la seguridad con rigor.','To prove you manage security rigorously.'), alt:'SOC 2, NIST CSF, ENS' },
      cobit:{ one:F('Gobierno de TI alineado con el negocio.','IT governance aligned with the business.'), use:F('Para dirigir y controlar la TI de forma estratégica.','To direct and control IT strategically.'), alt:'ITIL, ISO/IEC 38500, TOGAF' },
      kafka:{ one:F('Bus de eventos distribuido de alto rendimiento.','High-throughput distributed event bus.'), use:F('Para desacoplar servicios y procesar flujos de eventos.','To decouple services and process event streams.'), alt:'RabbitMQ, Pulsar, AWS Kinesis, Redpanda' },
      rabbitmq:{ one:F('Broker de colas con enrutado flexible.','Queue broker with flexible routing.'), use:F('Para tareas en cola y trabajo asíncrono entre servicios.','For queued tasks and async work between services.'), alt:'Kafka, NATS, ActiveMQ, AWS SQS' },
      nats:{ one:F('Mensajería pub/sub minimalista y rapidísima.','Minimalist, blazing-fast pub/sub messaging.'), use:F('Para comunicación ligera y de baja latencia entre microservicios.','For lightweight, low-latency comms between microservices.'), alt:'Kafka, RabbitMQ, MQTT, Redis Pub/Sub' },
      elasticsearch:{ one:F('Búsqueda full-text y análisis en milisegundos.','Full-text search and analytics in milliseconds.'), use:F('Para buscar texto, logs o datos a gran escala.','To search text, logs or data at scale.'), alt:'OpenSearch, Solr, Meilisearch, Typesense' },
      cassandra:{ one:F('BD distribuida para escritura masiva sin SPOF.','Distributed DB for massive writes with no SPOF.'), use:F('Para escala global con muchísima escritura y alta disponibilidad.','For global scale with heavy writes and high availability.'), alt:'ScyllaDB, DynamoDB, Bigtable, HBase' },
      istio:{ one:F('Service mesh: tráfico seguro entre microservicios.','Service mesh: secure traffic between microservices.'), use:F('Para mTLS, reintentos y despliegues canario sin tocar el código.','For mTLS, retries and canary rollouts without code changes.'), alt:'Linkerd, Consul, Cilium, Kuma' },
      kong:{ one:F('API Gateway: puerta única de entrada a tus APIs.','API Gateway: single entry point to your APIs.'), use:F('Para centralizar auth, rate-limit y enrutado de APIs.','To centralize auth, rate-limiting and API routing.'), alt:'NGINX, Traefik, AWS API Gateway, Apigee' },
      vault:{ one:F('Bóveda central de secretos y credenciales.','Central vault for secrets and credentials.'), use:F('Para no dejar contraseñas ni claves en el código.','To keep passwords and keys out of your code.'), alt:'AWS Secrets Manager, SOPS, Sealed Secrets' },
      argocd:{ one:F('GitOps: el clúster sigue lo declarado en Git.','GitOps: the cluster follows what Git declares.'), use:F('Para desplegar en Kubernetes de forma declarativa y auditable.','To deploy to Kubernetes declaratively and auditably.'), alt:'Flux, Jenkins X, Spinnaker' },
      veeam:{ one:F('Copias de seguridad y recuperación de servidores y VMs.','Backup and recovery of servers and VMs.'), use:F('Cuando necesitas restaurar datos o sistemas tras un fallo, borrado o ransomware.','When you must restore data or systems after a failure, deletion or ransomware.'), alt:'Commvault, Veritas, Bacula, Restic, AWS Backup' },
      backup:{ one:F('Copias de datos para poder recuperarlos.','Copies of your data so you can recover it.'), use:F('Siempre que la pérdida de esos datos sea inaceptable.','Whenever losing that data would be unacceptable.'), alt:'Veeam, Restic, Borg, Duplicati, AWS Backup' },
      snapshot:{ one:F('Foto del estado en un instante para volver atrás rápido.','Point-in-time snapshot to roll back fast.'), use:F('Antes de un cambio arriesgado (no como backup único).','Before a risky change (not as your only backup).'), alt:'LVM, ZFS, snapshots de VMware/cloud' },
      replication:{ one:F('Copia continua a un sitio secundario para DR.','Continuous copy to a secondary site for DR.'), use:F('Para continuidad si cae el sitio principal (RPO/RTO bajos).','For continuity if the primary site fails (low RPO/RTO).'), alt:'Zerto, Veeam Replication, DRBD' },
      velero:{ one:F('Backup y restauración de clústeres de Kubernetes.','Backup and restore of Kubernetes clusters.'), use:F('Para DR y migración de clústeres K8s y sus volúmenes.','For DR and migration of K8s clusters and their volumes.'), alt:'Kasten K10, Stash, snapshots del CSI' },
      zabbix:{ one:F('Monitoriza la infraestructura y avisa cuando algo falla.','Monitors infrastructure and alerts when something breaks.'), use:F('Para vigilar servidores, red y servicios, sobre todo on-premise.','To watch servers, network and services, especially on-prem.'), alt:'Nagios, PRTG, Checkmk, Prometheus, Grafana' },
    };
};

// --- piezas (antes blocksBase()) ---
window.LABSTACK.piezas = function () {
    const F = (es,en)=>({es,en});
    return [
      // RED
      {id:'router',cat:'red',code:'RT',name:F('Router','Router'),why:F('Interconecta y enruta paquetes entre redes o subredes distintas usando tablas de rutas.','Interconnects and routes packets between different networks or subnets via routing tables.'),desc:F('El router decide, salto a salto, por qué interfaz enviar cada paquete para que alcance otra red. Es la frontera lógica entre subredes.','The router decides, hop by hop, which interface to send each packet through so it reaches another network. It is the logical boundary between subnets.'),facts:[F('Trabaja en la capa 3 (IP) del modelo OSI.','Operates at layer 3 (IP) of the OSI model.'),F('Usa NAT para que muchas IP privadas salgan por una pública.','Uses NAT so many private IPs share one public address.')],term:[['$','ip route add 10.0.2.0/24 via 10.0.1.1'],['','route added to table main'],['$','ping -c1 10.0.2.5'],['','64 bytes from 10.0.2.5: icmp_seq=1 ttl=63']]},
      {id:'switch',cat:'red',code:'SW',name:F('Switch','Switch'),why:F('Conecta equipos dentro de la misma red local y reenvía tramas según la dirección MAC.','Connects hosts within the same LAN and forwards frames by MAC address.'),desc:F('El switch aprende qué MAC está en cada puerto y entrega las tramas solo al destino, evitando saturar la red.','The switch learns which MAC lives on each port and delivers frames only to the destination, avoiding flooding the network.'),facts:[F('Opera en la capa 2 (enlace de datos).','Operates at layer 2 (data link).'),F('Segmenta el tráfico en VLAN para aislar dominios.','Segments traffic into VLANs to isolate broadcast domains.')]},
      {id:'lb',cat:'red',code:'LB',name:F('Balanceador','Load balancer'),why:F('Reparte las peticiones entrantes entre varios servidores para escalar y dar alta disponibilidad.','Spreads incoming requests across several servers for scale and high availability.'),desc:F('Distribuye la carga (round-robin, menor número de conexiones…) y retira de rotación los nodos que fallan.','Distributes load (round-robin, least-connections…) and pulls failing nodes out of rotation.'),facts:[F('Puede ser de capa 4 (TCP) o capa 7 (HTTP).','Can be layer 4 (TCP) or layer 7 (HTTP).'),F('Habilita despliegues sin cortes y health-checks.','Enables zero-downtime deploys and health checks.')]},
      {id:'dns',cat:'red',code:'DNS',name:F('DNS','DNS'),why:F('Traduce nombres legibles (ejemplo.com) a direcciones IP.','Translates human names (example.com) into IP addresses.'),desc:F('El DNS es la agenda de Internet: resuelve un nombre a una IP mediante una jerarquía de servidores.','DNS is the phonebook of the Internet: it resolves a name to an IP through a hierarchy of servers.'),facts:[F('Registros clave: A, AAAA, CNAME, MX.','Key records: A, AAAA, CNAME, MX.'),F('El TTL controla cuánto se cachea una respuesta.','TTL controls how long a response is cached.')]},
      {id:'vlan',cat:'red',code:'VLN',name:F('VLAN / Subred','VLAN / Subnet'),why:F('Divide lógicamente una red física en segmentos aislados.','Logically splits one physical network into isolated segments.'),desc:F('Permite separar tráfico (producción, invitados, gestión) sin cablear redes distintas.','Lets you separate traffic (production, guest, management) without wiring separate networks.'),facts:[F('Cada VLAN es un dominio de broadcast propio.','Each VLAN is its own broadcast domain.'),F('El CIDR (/24) define el tamaño de la subred.','CIDR (/24) defines the subnet size.')]},
      // COMPUTO
      {id:'baremetal',cat:'computo',code:'BM',name:F('Servidor físico','Bare-metal server'),why:F('Es el hardware real (CPU, RAM, disco) sobre el que se apoya toda la infraestructura.','It is the real hardware (CPU, RAM, disk) that all infrastructure rests on.'),desc:F('Sin virtualizar: el sistema operativo o el hipervisor se instalan directamente sobre la máquina.','No virtualization: the OS or hypervisor installs directly on the machine.'),facts:[F('Máximo rendimiento, sin capa de abstracción.','Maximum performance, no abstraction layer.'),F('Menos flexible: una carga por máquina.','Less flexible: one workload per machine.')]},
      {id:'rack',cat:'computo',code:'RCK',name:F('Rack / Nodo','Rack / Node'),why:F('Agrupa varios servidores físicos con energía y red compartidas en un chasis.','Groups several physical servers sharing power and networking in a chassis.'),desc:F('La unidad de crecimiento del datacenter: se añaden nodos para escalar horizontalmente.','The datacenter unit of growth: nodes are added to scale out horizontally.'),facts:[F('Se mide en unidades de rack (U).','Measured in rack units (U).'),F('Redundancia de energía y refrigeración.','Redundant power and cooling.')]},
      // ALMACENAMIENTO
      {id:'san',cat:'almacenamiento',code:'SAN',name:F('SAN','SAN'),why:F('Ofrece almacenamiento por bloques a los servidores a través de una red dedicada.','Provides block storage to servers over a dedicated network.'),desc:F('Presenta discos (LUN) como si fueran locales; ideal para bases de datos y VM.','Presents disks (LUNs) as if local; ideal for databases and VMs.'),facts:[F('Protocolos: iSCSI, Fibre Channel.','Protocols: iSCSI, Fibre Channel.'),F('Bloque = baja latencia y alto IOPS.','Block = low latency and high IOPS.')],term:[['$','iscsiadm -m discovery -t st -p 10.0.3.10'],['','10.0.3.10:3260,1 iqn.2024-01.lab:disk0'],['$','iscsiadm -m node --login'],['','Login to [iface: default] successful.']]},
      {id:'nas',cat:'almacenamiento',code:'NAS',name:F('NAS','NAS'),why:F('Comparte almacenamiento a nivel de archivo por la red (NFS/SMB).','Shares file-level storage over the network (NFS/SMB).'),desc:F('Varios equipos montan la misma carpeta compartida; simple para documentos y respaldos.','Multiple hosts mount the same shared folder; simple for documents and backups.'),facts:[F('Protocolos: NFS (Linux), SMB (Windows).','Protocols: NFS (Linux), SMB (Windows).'),F('Archivo = fácil de compartir, más latencia que bloque.','File = easy to share, higher latency than block.')]},
      {id:'raid',cat:'almacenamiento',code:'RAID',name:F('RAID','RAID'),why:F('Combina varios discos para dar redundancia y/o rendimiento.','Combines several disks for redundancy and/or performance.'),desc:F('Reparte los datos (y su paridad) entre discos para tolerar fallos sin perder información.','Spreads data (and parity) across disks to tolerate failures without data loss.'),facts:[F('RAID 1 espeja; RAID 5 usa paridad; RAID 10 combina ambos.','RAID 1 mirrors; RAID 5 uses parity; RAID 10 combines both.'),F('No sustituye a una copia de seguridad.','It is not a substitute for a backup.')]},
      {id:'objstore',cat:'almacenamiento',code:'OBJ',name:F('Object storage','Object storage'),why:F('Guarda datos como objetos con metadatos, accesibles por API.','Stores data as objects with metadata, accessed via API.'),desc:F('Escala casi infinitamente y es ideal para archivos estáticos, backups y datos no estructurados.','Scales almost infinitely; ideal for static files, backups and unstructured data.'),facts:[F('Acceso por HTTP con una clave única por objeto.','HTTP access with a unique key per object.'),F('Base de servicios como S3, MinIO o Ceph.','Foundation of services like S3, MinIO or Ceph.')]},
      // VIRTUALIZACION
      {id:'hypervisor',cat:'virtualizacion',code:'HYP',name:F('Hipervisor','Hypervisor'),why:F('Software que crea y gestiona máquinas virtuales sobre un servidor físico.','Software that creates and manages virtual machines on a physical server.'),desc:F('El hipervisor tipo 1 (ESXi, Hyper-V) corre directo sobre el hardware y reparte CPU, RAM y disco entre VM.','A type-1 hypervisor (ESXi, Hyper-V) runs directly on hardware and shares CPU, RAM and disk among VMs.'),facts:[F('Tipo 1: sobre el hardware. Tipo 2: sobre un SO.','Type 1: on the hardware. Type 2: on top of an OS.'),F('Aísla las VM entre sí para más seguridad.','Isolates VMs from each other for more security.')]},
      {id:'kvm',cat:'virtualizacion',code:'KVM',name:F('KVM','KVM'),why:F('Convierte el kernel de Linux en un hipervisor tipo 1.','Turns the Linux kernel into a type-1 hypervisor.'),desc:F('KVM es la virtualización nativa de Linux; se gestiona con libvirt/virsh y es la base de muchas nubes.','KVM is Linux-native virtualization, managed with libvirt/virsh and the base of many clouds.'),facts:[F('Open source e integrado en el kernel.','Open source and built into the kernel.'),F('QEMU emula el hardware virtual.','QEMU emulates the virtual hardware.')],term:[['$','virsh list --all'],[''," Id   Name        State"],[''," 3    web-vm-01   running"],['$','virsh start db-vm-02'],['','Domain db-vm-02 started']]},
      {id:'vm',cat:'virtualizacion',code:'VM',name:F('Máquina virtual','Virtual machine'),why:F('Un ordenador completo emulado por software, con su propio SO.','A full software-emulated computer, with its own OS.'),desc:F('Cada VM incluye kernel y SO propios; pesada pero muy aislada frente al contenedor.','Each VM ships its own kernel and OS; heavy but strongly isolated compared to a container.'),facts:[F('Arranca en minutos; ocupa GB.','Boots in minutes; takes GBs.'),F('Se mueve entre nodos con migración en vivo.','Moves between nodes via live migration.')],steps:[F('El hipervisor reserva CPU, RAM y disco virtuales.','The hypervisor reserves virtual CPU, RAM and disk.'),F('Se instala un sistema operativo invitado.','A guest operating system is installed.'),F('La VM arranca aislada como un equipo real.','The VM boots, isolated, like a real machine.')]},
      // HCI
      {id:'ahv',cat:'hci',code:'AHV',name:F('Nutanix AHV','Nutanix AHV'),why:F('El hipervisor propio de Nutanix, incluido en la plataforma HCI.','Nutanix\u0027s own hypervisor, bundled in the HCI platform.'),desc:F('AHV virtualiza el cómputo dentro de un clúster hiperconvergente, sin licencias de hipervisor aparte.','AHV virtualizes compute inside a hyperconverged cluster, with no separate hypervisor licensing.'),facts:[F('Basado en KVM, endurecido por Nutanix.','Based on KVM, hardened by Nutanix.'),F('Se gestiona desde Prism, sin herramientas externas.','Managed from Prism, no external tools.')]},
      {id:'prism',cat:'hci',code:'PRS',name:F('Prism','Prism'),why:F('La consola única de gestión de un clúster Nutanix.','The single management console of a Nutanix cluster.'),desc:F('Prism unifica cómputo, almacenamiento y red en un panel, con analítica y automatización.','Prism unifies compute, storage and network in one pane, with analytics and automation.'),facts:[F('Prism Element gestiona un clúster; Prism Central, varios.','Prism Element manages one cluster; Prism Central, many.'),F('Todo por API REST reutilizable.','Everything via a reusable REST API.')]},
      {id:'hcinode',cat:'hci',code:'HCI',name:F('Nodo HCI','HCI node'),why:F('Un servidor que aporta a la vez cómputo y almacenamiento al clúster.','A server that contributes both compute and storage to the cluster.'),desc:F('En hiperconvergencia cada nodo suma recursos; el software une los discos locales en un pool distribuido.','In hyperconvergence each node adds resources; software pools local disks into a distributed store.'),facts:[F('Escalado lineal: añades nodos y crece todo.','Linear scaling: add nodes and everything grows.'),F('Tolera la caída de un nodo sin perder datos.','Tolerates a node failure without data loss.')]},
      // SO
      {id:'linux',cat:'so',code:'LNX',name:F('Linux','Linux'),why:F('Sistema operativo abierto que domina los servidores y la nube.','Open OS that dominates servers and the cloud.'),desc:F('Ligero, estable y scriptable; base de contenedores, Kubernetes y la mayoría de servicios cloud.','Light, stable and scriptable; the base of containers, Kubernetes and most cloud services.'),facts:[F('Distribuciones: Ubuntu, Debian, Rocky, Alpine.','Distros: Ubuntu, Debian, Rocky, Alpine.'),F('El kernel provee cgroups y namespaces (base de Docker).','The kernel provides cgroups and namespaces (Docker\u0027s base).')]},
      {id:'winserver',cat:'so',code:'WIN',name:F('Windows Server','Windows Server'),why:F('SO de servidor de Microsoft para servicios de directorio y apps .NET.','Microsoft server OS for directory services and .NET apps.'),desc:F('Integra Active Directory, IIS y roles de red; habitual en entornos corporativos.','Integrates Active Directory, IIS and network roles; common in enterprise environments.'),facts:[F('Active Directory centraliza identidades.','Active Directory centralizes identities.'),F('Se administra con PowerShell.','Administered with PowerShell.')]},
      // CONTENEDORES
      {id:'docker',cat:'contenedores',code:'DKR',name:F('Docker Engine','Docker Engine'),why:F('El motor que construye y ejecuta contenedores sobre el SO.','The engine that builds and runs containers on top of the OS.'),desc:F('Docker aísla procesos con namespaces y cgroups: la app comparte el kernel del host pero cree tener el suyo.','Docker isolates processes with namespaces and cgroups: the app shares the host kernel but thinks it has its own.'),facts:[F('Más ligero que una VM: arranca en milisegundos.','Lighter than a VM: starts in milliseconds.'),F('Una imagen produce el mismo entorno en cualquier lugar.','One image yields the same environment everywhere.')],term:[['$','docker run -d -p 8080:80 nginx'],['','a1f3c9  ...  Up 2 seconds'],['$','docker ps'],['','CONTAINER   IMAGE   STATUS'],['','a1f3c9      nginx   Up 3s']]},
      {id:'image',cat:'contenedores',code:'IMG',name:F('Imagen','Image'),why:F('Plantilla inmutable, por capas, con la app y sus dependencias.','Immutable, layered template with the app and its dependencies.'),desc:F('Una imagen es la "foto" desde la que se instancian contenedores idénticos; cada instrucción del build añade una capa cacheable.','An image is the "snapshot" containers are instantiated from; each build step adds a cacheable layer.'),facts:[F('Se versiona con tags (nginx:1.25).','Versioned with tags (nginx:1.25).'),F('Se guarda y comparte en un registry.','Stored and shared in a registry.')]},
      {id:'container',cat:'contenedores',code:'CTR',name:F('Contenedor','Container'),why:F('Instancia en ejecución de una imagen, aislada del resto.','A running instance of an image, isolated from the rest.'),desc:F('Es efímero y desechable: si se rompe, se descarta y se crea otro idéntico desde la imagen.','It is ephemeral and disposable: if it breaks, throw it away and spin an identical one from the image.'),facts:[F('El estado que debe persistir va en volúmenes.','State that must persist goes into volumes.'),F('Comparte el kernel del host, no lleva SO propio.','Shares the host kernel, ships no OS of its own.')],steps:[F('Docker toma una imagen del registry o local.','Docker takes an image from the registry or local cache.'),F('Crea un espacio aislado (namespaces, cgroups).','Creates an isolated space (namespaces, cgroups).'),F('Arranca el proceso; queda listo en milisegundos.','Starts the process; ready in milliseconds.')]},
      {id:'dockerfile',cat:'contenedores',code:'DF',name:F('Dockerfile','Dockerfile'),why:F('Receta de texto que describe cómo construir una imagen.','Text recipe that describes how to build an image.'),desc:F('Cada línea (FROM, COPY, RUN…) crea una capa; el resultado es una imagen reproducible.','Each line (FROM, COPY, RUN…) creates a layer; the result is a reproducible image.'),facts:[F('El orden importa: aprovecha la caché de capas.','Order matters: leverage the layer cache.'),F('FROM define la imagen base.','FROM sets the base image.')],term:[['#','Dockerfile'],['','FROM node:20-alpine'],['','WORKDIR /app'],['','COPY . .'],['','RUN npm ci'],['','CMD ["npm","start"]']]},
      {id:'compose',cat:'contenedores',code:'CMP',name:F('Docker Compose','Docker Compose'),why:F('Define y levanta varios contenedores relacionados con un solo archivo.','Defines and spins up several related containers from one file.'),desc:F('Con un YAML describes app, base de datos y red; un comando lo arranca todo conectado.','With one YAML you describe app, database and network; a single command starts it all wired together.'),facts:[F('docker compose up levanta el stack completo.','docker compose up brings the whole stack online.'),F('Ideal para desarrollo local multi-servicio.','Ideal for local multi-service development.')]},
      // ORQUESTACION
      {id:'k8s',cat:'orquestacion',code:'K8s',name:F('Kubernetes','Kubernetes'),why:F('Orquesta contenedores en un clúster: los programa, escala y repara.','Orchestrates containers across a cluster: schedules, scales and heals them.'),desc:F('El plano de control decide dónde corre cada contenedor y mantiene el estado deseado que declaras.','The control plane decides where each container runs and keeps the desired state you declare.'),facts:[F('Declarativo: describes el "qué", no el "cómo".','Declarative: you describe the "what", not the "how".'),F('Componentes: API server, scheduler, etcd, kubelet.','Components: API server, scheduler, etcd, kubelet.')],term:[['$','kubectl get nodes'],['','NAME     STATUS   ROLES'],['','node-1   Ready    control-plane'],['','node-2   Ready    worker'],['$','kubectl get pods -A'],['','kube-system  coredns  Running']]},
      {id:'pod',cat:'orquestacion',code:'POD',name:F('Pod','Pod'),why:F('La unidad mínima de despliegue: uno o varios contenedores que comparten red.','The smallest deployable unit: one or more containers sharing a network.'),desc:F('Los contenedores de un pod comparten IP y volúmenes; se crean y destruyen juntos.','Containers in a pod share IP and volumes; they are created and destroyed together.'),facts:[F('Efímero: Kubernetes lo recrea si muere.','Ephemeral: Kubernetes recreates it if it dies.'),F('Rara vez se crea solo; lo gestiona un Deployment.','Rarely created alone; a Deployment manages it.')],term:[['$','kubectl run web --image=nginx'],['','pod/web created'],['$','kubectl get pod web'],['','NAME  READY  STATUS   RESTARTS'],['','web   1/1    Running  0']]},
      {id:'deployment',cat:'orquestacion',code:'DEP',name:F('Deployment','Deployment'),why:F('Declara cuántas réplicas de un pod deben existir y las mantiene.','Declares how many pod replicas must exist and keeps them.'),desc:F('Si un pod cae, el Deployment crea otro; también hace despliegues progresivos y rollback.','If a pod dies the Deployment creates another; it also does rolling updates and rollback.'),facts:[F('replicas define el número deseado de pods.','replicas sets the desired number of pods.'),F('Actualiza sin cortes con rolling update.','Updates without downtime via rolling update.')],steps:[F('Declaras el estado deseado en un YAML.','You declare the desired state in a YAML.'),F('El controlador crea las réplicas de pods.','The controller creates the pod replicas.'),F('Vigila y reemplaza cualquier pod caído.','It watches and replaces any failed pod.')]},
      {id:'service',cat:'orquestacion',code:'SVC',name:F('Service','Service'),why:F('Da una dirección estable a un grupo de pods cambiante.','Gives a stable address to a shifting set of pods.'),desc:F('Como los pods cambian de IP, el Service ofrece un nombre y balanceo fijos hacia ellos.','Since pods change IP, the Service provides a stable name and load balancing toward them.'),facts:[F('Tipos: ClusterIP, NodePort, LoadBalancer.','Types: ClusterIP, NodePort, LoadBalancer.'),F('Selecciona pods por etiquetas (labels).','Selects pods by labels.')]},
      {id:'ingress',cat:'orquestacion',code:'ING',name:F('Ingress','Ingress'),why:F('Enruta el tráfico HTTP externo hacia los Services correctos.','Routes external HTTP traffic to the right Services.'),desc:F('Publica varias apps bajo un mismo punto de entrada, con reglas por host o ruta y TLS.','Publishes several apps behind one entry point, with host/path rules and TLS.'),facts:[F('Necesita un ingress controller (nginx, Traefik).','Needs an ingress controller (nginx, Traefik).'),F('Termina TLS y aplica reglas por dominio.','Terminates TLS and applies per-domain rules.')]},
      {id:'k8snode',cat:'orquestacion',code:'WKR',name:F('Nodo worker','Worker node'),why:F('Máquina del clúster que ejecuta los pods asignados por el scheduler.','Cluster machine that runs the pods assigned by the scheduler.'),desc:F('El kubelet de cada nodo habla con el plano de control y arranca los contenedores.','Each node\u0027s kubelet talks to the control plane and starts the containers.'),facts:[F('Añadir nodos aumenta la capacidad del clúster.','Adding nodes increases cluster capacity.'),F('El scheduler decide en qué nodo cabe cada pod.','The scheduler decides which node fits each pod.')]},
      // NUBE
      {id:'cloudvm',cat:'nube',code:'EC2',name:F('VM en la nube','Cloud VM'),why:F('Servidor virtual bajo demanda de un proveedor (EC2, Azure VM, Compute Engine).','On-demand virtual server from a provider (EC2, Azure VM, Compute Engine).'),desc:F('Se aprovisiona en minutos y se paga por uso; sin comprar hardware ni gestionar el datacenter.','Provisioned in minutes and paid per use; no hardware to buy or datacenter to run.'),facts:[F('Pago por hora/segundo, se apaga cuando no se usa.','Billed per hour/second, turned off when idle.'),F('Elige tipo de instancia según CPU/RAM.','Pick an instance type by CPU/RAM.')],term:[['$','aws ec2 run-instances --image-id ami-0abc \\'],['','  --instance-type t3.micro --count 1'],['','{ "InstanceId": "i-0a1b2c3d" }']]},
      {id:'managedk8s',cat:'nube',code:'EKS',name:F('K8s gestionado','Managed K8s'),why:F('Kubernetes operado por el proveedor (EKS, AKS, GKE): tú solo pones cargas.','Kubernetes operated by the provider (EKS, AKS, GKE): you just add workloads.'),desc:F('El proveedor mantiene el plano de control; tú despliegas apps sin administrar los masters.','The provider maintains the control plane; you deploy apps without managing the masters.'),facts:[F('Autoescalado de nodos integrado.','Built-in node autoscaling.'),F('Menos operación, algo menos de control fino.','Less operations, slightly less fine control.')]},
      {id:'serverless',cat:'nube',code:'FN',name:F('Serverless','Serverless'),why:F('Ejecuta funciones bajo demanda sin gestionar servidores (Lambda, Functions).','Runs functions on demand with no servers to manage (Lambda, Functions).'),desc:F('Tu código corre solo cuando se le invoca y escala a cero; pagas por ejecución y milisegundos.','Your code runs only when invoked and scales to zero; you pay per execution and millisecond.'),facts:[F('Escala a cero: sin coste en reposo.','Scales to zero: no cost while idle.'),F('Ideal para eventos y APIs esporádicas.','Ideal for events and bursty APIs.')],steps:[F('Un evento (HTTP, cola, cron) dispara la función.','An event (HTTP, queue, cron) triggers the function.'),F('El proveedor arranca un entorno efímero.','The provider spins up an ephemeral runtime.'),F('Ejecuta el código y libera los recursos.','It runs the code and releases the resources.')]},
      {id:'cdn',cat:'nube',code:'CDN',name:F('CDN','CDN'),why:F('Cachea contenido en servidores cercanos al usuario para servirlo rápido.','Caches content on servers near the user to serve it fast.'),desc:F('Réplica los archivos estáticos en el borde (edge) de la red mundial, reduciendo latencia y carga del origen.','Replicates static files at the network edge worldwide, cutting latency and origin load.'),facts:[F('Acerca el contenido geográficamente al usuario.','Brings content geographically closer to the user.'),F('Absorbe picos y ataques en el borde.','Absorbs spikes and attacks at the edge.')]},
      // DATOS
      {id:'postgres',cat:'datos',code:'PG',name:F('PostgreSQL','PostgreSQL'),why:F('Base de datos relacional (SQL) robusta para datos estructurados y transacciones.','Robust relational (SQL) database for structured data and transactions.'),desc:F('Guarda los datos en tablas con esquema y relaciones, garantizando consistencia con transacciones ACID.','Stores data in schema tables with relations, guaranteeing consistency via ACID transactions.'),facts:[F('ACID: atomicidad, consistencia, aislamiento y durabilidad.','ACID: atomicity, consistency, isolation, durability.'),F('Se consulta con SQL; ideal para datos relacionados.','Queried with SQL; ideal for related data.')],term:[['$','psql -U lab -d taller'],['','taller=#'],['#','SELECT id,nombre FROM alumnos LIMIT 2;'],['',' 1 | Ana'],['',' 2 | Luis']]},
      {id:'mysql',cat:'datos',code:'SQL',name:F('MySQL / MariaDB','MySQL / MariaDB'),why:F('Base de datos relacional muy extendida en aplicaciones web.','Widely used relational database in web applications.'),desc:F('Motor SQL ligero y popular; base de muchos CMS y stacks LAMP.','Light, popular SQL engine; base of many CMSs and LAMP stacks.'),facts:[F('Modelo relacional con SQL estándar.','Relational model with standard SQL.'),F('Replicación primario-réplica para escalar lecturas.','Primary-replica replication to scale reads.')]},
      {id:'mongodb',cat:'datos',code:'MDB',name:F('MongoDB','MongoDB'),why:F('Base de datos NoSQL orientada a documentos JSON flexibles.','NoSQL document database with flexible JSON documents.'),desc:F('Almacena documentos sin esquema fijo; encaja cuando la estructura de datos evoluciona rápido.','Stores documents with no fixed schema; fits when data structure evolves fast.'),facts:[F('Documentos tipo JSON (BSON), sin esquema rígido.','JSON-like documents (BSON), no rigid schema.'),F('Escala horizontalmente por sharding.','Scales out horizontally via sharding.')]},
      {id:'redis',cat:'datos',code:'RDS',name:F('Redis','Redis'),why:F('Almacén clave-valor en memoria, usado como caché y colas.','In-memory key-value store, used as cache and queues.'),desc:F('Sirve datos desde RAM a altísima velocidad; ideal para caché, sesiones y contadores.','Serves data from RAM at very high speed; ideal for cache, sessions and counters.'),facts:[F('En memoria: latencia de microsegundos.','In-memory: microsecond latency.'),F('Descarga a la base de datos principal.','Offloads load from the primary database.')]},
      // CI/CD
      {id:'git',cat:'cicd',code:'GIT',name:F('Git / Repositorio','Git / Repository'),why:F('Control de versiones distribuido: historia y ramas del código.','Distributed version control: history and branches of the code.'),desc:F('Cada cambio queda registrado; las ramas permiten trabajar en paralelo y fusionar sin perder trabajo.','Every change is recorded; branches allow parallel work and merging without losing work.'),facts:[F('El commit es la unidad de cambio versionada.','The commit is the versioned unit of change.'),F('El push al repositorio remoto dispara la CI.','Pushing to the remote repo triggers CI.')],term:[['$','git add . && git commit -m "feat: api"'],['','[main a1b2c3] feat: api'],['$','git push origin main'],['','-> triggering pipeline...']]},
      {id:'pipeline',cat:'cicd',code:'CI',name:F('Pipeline CI','CI pipeline'),why:F('Automatiza compilar y probar el código en cada cambio.','Automates building and testing the code on every change.'),desc:F('Ante cada push, ejecuta pasos (build, test, lint); si algo falla, detiene la entrega.','On each push it runs steps (build, test, lint); if anything fails it stops delivery.'),facts:[F('Integración continua: detecta errores pronto.','Continuous integration: catches errors early.'),F('Definido como código en YAML.','Defined as code in YAML.')],steps:[F('Un push al repositorio dispara el pipeline.','A push to the repo triggers the pipeline.'),F('Se compila y se ejecutan los tests.','The code is built and the tests run.'),F('Si todo pasa, se genera un artefacto o imagen.','If everything passes, an artifact or image is produced.')]},
      {id:'actions',cat:'cicd',code:'GHA',name:F('GitHub Actions','GitHub Actions'),why:F('Motor de automatización de flujos de CI/CD integrado en el repositorio.','CI/CD workflow automation engine built into the repository.'),desc:F('Ejecuta flujos definidos en YAML ante eventos (push, PR, cron) usando runners.','Runs YAML-defined workflows on events (push, PR, cron) using runners.'),facts:[F('Workflows por eventos y jobs paralelos.','Event-driven workflows and parallel jobs.'),F('Reutiliza acciones del marketplace.','Reuses actions from the marketplace.')]},
      {id:'registry',cat:'cicd',code:'REG',name:F('Registro de imágenes','Image registry'),why:F('Almacena y versiona las imágenes de contenedor que produce la CI.','Stores and versions the container images produced by CI.'),desc:F('El pipeline sube la imagen construida al registry; el clúster la descarga al desplegar.','The pipeline pushes the built image to the registry; the cluster pulls it on deploy.'),facts:[F('Ejemplos: Docker Hub, GHCR, ECR, Harbor.','Examples: Docker Hub, GHCR, ECR, Harbor.'),F('Etiqueta cada versión para poder revertir.','Tags every version so you can roll back.')]},
      {id:'gitops',cat:'cicd',code:'CD',name:F('CD / GitOps','CD / GitOps'),why:F('Despliega automáticamente el estado declarado en el repositorio al clúster.','Automatically deploys the state declared in the repo to the cluster.'),desc:F('Con GitOps el repositorio es la fuente de verdad; un agente (Argo CD, Flux) sincroniza el clúster.','With GitOps the repo is the source of truth; an agent (Argo CD, Flux) syncs the cluster.'),facts:[F('El estado deseado vive en Git.','The desired state lives in Git.'),F('Reversión = volver a un commit anterior.','Rollback = revert to an earlier commit.')]},
      // IaC
      {id:'terraform',cat:'iac',code:'TF',name:F('Terraform','Terraform'),why:F('Define y aprovisiona la infraestructura de forma declarativa como código.','Defines and provisions infrastructure declaratively as code.'),desc:F('Describes los recursos (redes, VM, clústeres) en archivos; Terraform los crea y mantiene en cualquier proveedor.','You describe resources (networks, VMs, clusters) in files; Terraform creates and keeps them on any provider.'),facts:[F('Declarativo y multiproveedor.','Declarative and multi-cloud.'),F('plan muestra los cambios antes de aplicarlos.','plan shows changes before applying them.')],term:[['$','terraform plan'],['','+ aws_instance.web will be created'],['$','terraform apply'],['','Apply complete! 1 added, 0 changed.']]},
      {id:'ansible',cat:'iac',code:'ANS',name:F('Ansible','Ansible'),why:F('Automatiza la configuración de servidores de forma idempotente.','Automates server configuration idempotently.'),desc:F('Con playbooks describe el estado deseado de cada máquina; aplica cambios por SSH sin agentes.','With playbooks you describe each machine\u0027s desired state; applies changes over SSH, agentless.'),facts:[F('Idempotente: aplicar dos veces da el mismo resultado.','Idempotent: applying twice yields the same result.'),F('Sin agentes: funciona por SSH.','Agentless: works over SSH.')]},
      {id:'tfstate',cat:'iac',code:'ST',name:F('Estado / State','State'),why:F('Registro de qué recursos gestiona IaC y su estado actual real.','Record of which resources IaC manages and their current real state.'),desc:F('El estado permite a la herramienta saber qué existe y calcular el mínimo cambio necesario.','State lets the tool know what exists and compute the minimum change required.'),facts:[F('Debe guardarse remoto y bloqueado en equipo.','Should be stored remote and locked in a team.'),F('Nunca se edita a mano.','Never edited by hand.')]},
      {id:'module',cat:'iac',code:'MOD',name:F('Módulo','Module'),why:F('Empaqueta configuración de IaC reutilizable y parametrizable.','Packages reusable, parametrizable IaC configuration.'),desc:F('Encapsula un patrón (una red, un clúster) para reutilizarlo con distintas variables.','Encapsulates a pattern (a network, a cluster) to reuse with different variables.'),facts:[F('Fomenta la reutilización y el estándar.','Encourages reuse and standardization.'),F('Se versiona como el resto del código.','Versioned like the rest of the code.')]},
      // MONITORIZACION
      {id:'prometheus',cat:'monitorizacion',code:'PROM',name:F('Prometheus','Prometheus'),why:F('Recolecta y almacena métricas del sistema en series temporales.','Collects and stores system metrics as time series.'),desc:F('Sondea (scrape) periódicamente los servicios y guarda métricas numéricas para consultarlas con PromQL.','Periodically scrapes services and stores numeric metrics to query with PromQL.'),facts:[F('Modelo pull: sondea a los objetivos.','Pull model: it scrapes the targets.'),F('PromQL consulta series temporales.','PromQL queries time series.')],term:[['$','curl localhost:9090/metrics'],['','http_requests_total{code="200"} 1042'],['','process_cpu_seconds_total 8.31']]},
      {id:'grafana',cat:'monitorizacion',code:'GRAF',name:F('Grafana','Grafana'),why:F('Visualiza métricas en paneles y gráficos comprensibles.','Visualizes metrics in understandable dashboards and charts.'),desc:F('Conecta con Prometheus u otras fuentes y construye dashboards para ver el estado de un vistazo.','Connects to Prometheus or other sources and builds dashboards to see health at a glance.'),facts:[F('Dashboards con múltiples fuentes de datos.','Dashboards with multiple data sources.'),F('No almacena datos: los consulta.','It stores no data: it queries it.')]},
      {id:'logs',cat:'monitorizacion',code:'LOG',name:F('Logs / ELK','Logs / ELK'),why:F('Centraliza y busca los registros de todos los servicios.','Centralizes and searches logs from every service.'),desc:F('Agrega los logs dispersos en un solo lugar indexado y buscable, clave para diagnosticar incidencias.','Aggregates scattered logs into one indexed, searchable place, key to diagnosing incidents.'),facts:[F('Stack típico: Elasticsearch, Logstash, Kibana.','Typical stack: Elasticsearch, Logstash, Kibana.'),F('Correlaciona eventos entre servicios.','Correlates events across services.')]},
      {id:'alerts',cat:'monitorizacion',code:'ALRT',name:F('Alertas','Alerting'),why:F('Avisa automáticamente cuando una métrica cruza un umbral.','Automatically notifies when a metric crosses a threshold.'),desc:F('Define reglas (CPU alta, servicio caído) y envía avisos por correo, Slack o guardia (on-call).','Defines rules (high CPU, service down) and sends notifications by email, Slack or on-call.'),facts:[F('Reglas basadas en umbrales y tendencias.','Rules based on thresholds and trends.'),F('Reduce el tiempo de detección de fallos.','Reduces failure detection time.')],steps:[F('Se define una regla sobre una métrica.','A rule is defined over a metric.'),F('El sistema evalúa la métrica continuamente.','The system evaluates the metric continuously.'),F('Al cruzar el umbral, dispara la notificación.','On crossing the threshold, it fires the notification.')]},
      {id:'tracing',cat:'monitorizacion',code:'APM',name:F('Trazas / APM','Tracing / APM'),why:F('Sigue una petición a través de todos los servicios que atraviesa.','Follows a request across every service it passes through.'),desc:F('El trazado distribuido muestra dónde se pierde el tiempo en una arquitectura de microservicios.','Distributed tracing shows where time is spent across a microservices architecture.'),facts:[F('Cada petición lleva un trace-id único.','Each request carries a unique trace-id.'),F('Localiza cuellos de botella de latencia.','Pinpoints latency bottlenecks.')]},
      // GOBIERNO · CUMPLIMIENTO
      {id:'coso',cat:'gobernanza',code:'COSO',name:F('COSO','COSO'),why:F('Marco de control interno y gestión de riesgos de la empresa.','Framework for internal control and enterprise risk management.'),desc:F('COSO da una estructura de 5 componentes (entorno de control, evaluación de riesgos, actividades de control, información y comunicación, y supervisión) para que la organización controle sus riesgos y opere con fiabilidad.','COSO provides a 5-component structure (control environment, risk assessment, control activities, information and communication, and monitoring) so the organization controls its risks and operates reliably.'),facts:[F('Base del control interno y la fiabilidad financiera.','Foundation of internal control and financial reliability.'),F('Su versión ERM enfoca la gestión de riesgos del negocio.','Its ERM version focuses on enterprise risk management.')]},
      {id:'iso27001',cat:'gobernanza',code:'27001',name:F('ISO 27001','ISO 27001'),why:F('Estándar para gestionar la seguridad de la información (SGSI).','Standard to manage information security (ISMS).'),desc:F('Define cómo montar un Sistema de Gestión de Seguridad de la Información: análisis de riesgos, controles del Anexo A y mejora continua (ciclo PDCA). Es certificable por auditoría externa.','Defines how to run an Information Security Management System: risk analysis, Annex A controls and continual improvement (PDCA). It is certifiable by external audit.'),facts:[F('Certificable por una auditoría externa acreditada.','Certifiable by an accredited external audit.'),F('El Anexo A reúne los controles de seguridad.','Annex A gathers the security controls.')]},
      {id:'cobit',cat:'gobernanza',code:'COBIT',name:F('COBIT','COBIT'),why:F('Marco de gobierno y gestión de TI, alineado con el negocio.','IT governance and management framework, aligned with the business.'),desc:F('Creado por ISACA, separa gobierno (dirigir) de gestión (ejecutar) y define objetivos de control para que la TI aporte valor y controle el riesgo.','Created by ISACA, it separates governance (direct) from management (execute) and sets control objectives so IT delivers value and controls risk.'),facts:[F('Distingue claramente gobierno de gestión de la TI.','Clearly separates IT governance from management.'),F('Se integra con ISO, ITIL y otros marcos.','Integrates with ISO, ITIL and other frameworks.')]},
      // SEGURIDAD
      {id:'firewall',cat:'seguridad',code:'FW',name:F('Firewall','Firewall'),why:F('Filtra el tráfico según reglas, permitiendo o bloqueando conexiones.','Filters traffic by rules, allowing or blocking connections.'),desc:F('Define qué puertos y orígenes pueden comunicarse; primera línea de defensa perimetral y entre segmentos.','Defines which ports and sources may talk; the first line of perimeter and segment defense.'),facts:[F('Reglas por puerto, IP y protocolo.','Rules by port, IP and protocol.'),F('Los grupos de seguridad son firewalls en la nube.','Security groups are firewalls in the cloud.')],term:[['$','ufw allow 443/tcp'],['','Rule added'],['$','ufw deny 23'],['','Rule added'],['$','ufw status'],['','443/tcp  ALLOW   Anywhere']]},
      {id:'iam',cat:'seguridad',code:'IAM',name:F('IAM','IAM'),why:F('Gestiona identidades y qué puede hacer cada usuario o servicio.','Manages identities and what each user or service may do.'),desc:F('Aplica el mínimo privilegio: cada rol recibe solo los permisos que necesita, ni más ni menos.','Enforces least privilege: each role gets only the permissions it needs, no more.'),facts:[F('Principio de mínimo privilegio.','Principle of least privilege.'),F('Roles y políticas en lugar de contraseñas compartidas.','Roles and policies instead of shared passwords.')]},
      {id:'tls',cat:'seguridad',code:'TLS',name:F('TLS / Certificados','TLS / Certificates'),why:F('Cifra el tráfico en tránsito y verifica la identidad del servidor.','Encrypts traffic in transit and verifies the server identity.'),desc:F('El certificado, firmado por una CA, habilita HTTPS y evita que un tercero lea o altere los datos.','The CA-signed certificate enables HTTPS and stops third parties from reading or altering data.'),facts:[F('HTTPS = HTTP sobre TLS.','HTTPS = HTTP over TLS.'),F('Los certificados caducan y se renuevan (Let\u0027s Encrypt).','Certificates expire and are renewed (Let\u0027s Encrypt).')],steps:[F('El cliente y el servidor negocian claves (handshake).','Client and server negotiate keys (handshake).'),F('Se valida el certificado contra una CA de confianza.','The certificate is validated against a trusted CA.'),F('El resto de la sesión viaja cifrada.','The rest of the session travels encrypted.')]},
      {id:'vpn',cat:'seguridad',code:'VPN',name:F('VPN','VPN'),why:F('Crea un túnel cifrado entre redes o usuarios remotos.','Creates an encrypted tunnel between networks or remote users.'),desc:F('Conecta con seguridad una oficina, un usuario o una nube a través de Internet como si fuera una red privada.','Securely connects an office, a user or a cloud over the Internet as if on a private network.'),facts:[F('Protocolos: WireGuard, IPsec, OpenVPN.','Protocols: WireGuard, IPsec, OpenVPN.'),F('Site-to-site o de acceso remoto.','Site-to-site or remote access.')]},
      {id:'encryption',cat:'seguridad',code:'ENC',name:F('Cifrado en reposo','Encryption at rest'),why:F('Protege los datos almacenados para que sean ilegibles si se roban los discos.','Protects stored data so it is unreadable if disks are stolen.'),desc:F('Cifra volúmenes, backups y objetos con claves gestionadas; complemento del cifrado en tránsito (TLS).','Encrypts volumes, backups and objects with managed keys; complements in-transit encryption (TLS).'),facts:[F('Claves gestionadas por un KMS.','Keys managed by a KMS.'),F('Requisito habitual de cumplimiento normativo.','A common compliance requirement.')]},
      // MENSAJERIA · EVENTOS
      {id:'kafka',cat:'mensajeria',code:'KFK',name:F('Apache Kafka','Apache Kafka'),why:F('Bus de eventos distribuido de alto rendimiento para conectar servicios.','High-throughput distributed event bus that connects services.'),desc:F('Es un log distribuido y particionado: los productores publican eventos en topics y los consumidores los leen a su ritmo, desacoplando los servicios.','It is a distributed, partitioned log: producers publish events to topics and consumers read them at their own pace, decoupling services.'),facts:[F('Retiene los eventos: se pueden reprocesar (replay).','Retains events: they can be reprocessed (replay).'),F('Escala por particiones y réplicas.','Scales by partitions and replicas.')],term:[['$','kafka-topics --create --topic pedidos --partitions 3'],['','Created topic pedidos.'],['$','kafka-console-producer --topic pedidos'],['','> {"id":42,"total":19.9}']]},
      {id:'rabbitmq',cat:'mensajeria',code:'RMQ',name:F('RabbitMQ','RabbitMQ'),why:F('Broker de mensajes con colas y enrutado flexible.','Message broker with queues and flexible routing.'),desc:F('Implementa AMQP: enruta mensajes desde exchanges hacia colas, con confirmaciones (ack) y reintentos; ideal para tareas y trabajo en cola.','Implements AMQP: routes messages from exchanges into queues, with acknowledgements and retries; ideal for tasks and work queues.'),facts:[F('Colas con confirmación (ack) y reintentos.','Queues with acknowledgements and retries.'),F('Patrones: pub/sub, work queues, RPC.','Patterns: pub/sub, work queues, RPC.')]},
      {id:'nats',cat:'mensajeria',code:'NATS',name:F('NATS','NATS'),why:F('Mensajería ligera y ultrarrápida para microservicios.','Lightweight, ultra-fast messaging for microservices.'),desc:F('Pub/sub minimalista de muy baja latencia; con JetStream añade persistencia y colas duraderas.','Minimalist, very low-latency pub/sub; JetStream adds persistence and durable queues.'),facts:[F('Muy simple y rapidísimo (millones de msg/s).','Very simple and blazing fast (millions of msgs/s).'),F('Soporta pub/sub y request/reply.','Supports pub/sub and request/reply.')]},
      // DATOS (ampliación)
      {id:'elasticsearch',cat:'datos',code:'ES',name:F('Elasticsearch','Elasticsearch'),why:F('Motor de búsqueda y análisis sobre grandes volúmenes de texto.','Search and analytics engine over large volumes of text.'),desc:F('Indexa documentos JSON y responde búsquedas full-text y agregaciones en milisegundos; es el núcleo del stack ELK de logs.','Indexes JSON documents and answers full-text searches and aggregations in milliseconds; the core of the ELK logging stack.'),facts:[F('Usa un índice invertido para buscar texto rápido.','Uses an inverted index for fast text search.'),F('Escala por shards y réplicas.','Scales by shards and replicas.')]},
      {id:'cassandra',cat:'datos',code:'CAS',name:F('Cassandra','Cassandra'),why:F('Base de datos distribuida para escritura masiva y alta disponibilidad.','Distributed database for massive writes and high availability.'),desc:F('Modelo de columnas ancho, sin punto único de fallo: replica entre nodos y regiones con consistencia ajustable.','Wide-column model with no single point of failure: replicates across nodes and regions with tunable consistency.'),facts:[F('Escala lineal: escribes en cualquier nodo.','Linear scale: you write to any node.'),F('Prioriza disponibilidad (AP en el teorema CAP).','Favors availability (AP in the CAP theorem).')]},
      // ORQUESTACION (ampliación)
      {id:'istio',cat:'orquestacion',code:'IST',name:F('Istio (Service Mesh)','Istio (Service Mesh)'),why:F('Gestiona el tráfico entre microservicios sin tocar su código.','Manages traffic between microservices without touching their code.'),desc:F('Inyecta proxies sidecar (Envoy) junto a cada pod que aportan mTLS, reintentos, balanceo, tráfico canario y observabilidad.','Injects sidecar proxies (Envoy) next to each pod, adding mTLS, retries, load balancing, canary traffic and observability.'),facts:[F('Un sidecar Envoy por pod intercepta el tráfico.','An Envoy sidecar per pod intercepts traffic.'),F('mTLS y despliegues canario sin cambiar la app.','mTLS and canary rollouts with no app changes.')]},
      // RED (ampliación)
      {id:'kong',cat:'red',code:'KNG',name:F('Kong (API Gateway)','Kong (API Gateway)'),why:F('Centraliza la entrada a tus APIs en un único punto controlado.','Centralizes entry to your APIs in a single controlled point.'),desc:F('Punto único de entrada ante los servicios backend: aplica autenticación, límites de tasa (rate-limit), enrutado y plugins.','Single entry point in front of backend services: applies authentication, rate-limiting, routing and plugins.'),facts:[F('Plugins: auth, rate-limit, logging, transformaciones.','Plugins: auth, rate-limit, logging, transforms.'),F('Construido sobre NGINX/Envoy.','Built on top of NGINX/Envoy.')]},
      // SEGURIDAD (ampliación)
      {id:'vault',cat:'seguridad',code:'VLT',name:F('HashiCorp Vault','HashiCorp Vault'),why:F('Gestiona secretos, claves y credenciales de forma centralizada.','Centrally manages secrets, keys and credentials.'),desc:F('Almacena y entrega secretos con acceso auditado, rotación automática y credenciales dinámicas de corta vida en lugar de contraseñas fijas en el código.','Stores and delivers secrets with audited access, automatic rotation and short-lived dynamic credentials instead of hardcoded passwords.'),facts:[F('Secretos dinámicos y de corta vida.','Short-lived, dynamic secrets.'),F('Cifrado como servicio y acceso auditado.','Encryption-as-a-service and audited access.')]},
      // CI/CD (ampliación)
      {id:'argocd',cat:'cicd',code:'ARGO',name:F('Argo CD','Argo CD'),why:F('Despliegue GitOps declarativo para Kubernetes.','Declarative GitOps deployment for Kubernetes.'),desc:F('Sincroniza el clúster con el estado declarado en Git: detecta desviaciones (drift) y revierte automáticamente a lo definido en el repositorio.','Syncs the cluster with the state declared in Git: detects drift and automatically reverts to what the repo defines.'),facts:[F('La fuente de verdad es Git.','The source of truth is Git.'),F('Auto-sync, detección de drift y rollback.','Auto-sync, drift detection and rollback.')]},
      // BACKUP · RECUPERACIÓN (transversal)
      {id:'backup',cat:'backup',code:'BKP',name:F('Copia de seguridad','Backup'),why:F('Guarda copias de los datos para poder recuperarlos si se pierden, se corrompen o los cifra un ataque.','Keeps copies of your data so you can recover it if it is lost, corrupted or encrypted by an attack.'),desc:F('Puede ser completa, incremental o diferencial. Una buena estrategia sigue la regla 3-2-1 y, sobre todo, prueba la restauración: un backup que no se restaura no vale.','It can be full, incremental or differential. A good strategy follows the 3-2-1 rule and, above all, tests the restore: a backup you cannot restore is worthless.'),facts:[F('Completa vs incremental vs diferencial.','Full vs incremental vs differential.'),F('Regla 3-2-1 y probar la restauración periódicamente.','3-2-1 rule and test the restore regularly.')]},
      {id:'snapshot',cat:'backup',code:'SNAP',name:F('Snapshot','Snapshot'),why:F('Captura el estado de un volumen o VM en un instante para poder volver atrás muy rápido.','Captures the state of a volume or VM at an instant so you can roll back very fast.'),desc:F('Es instantáneo y ligero (copy-on-write), ideal antes de un cambio arriesgado; pero NO sustituye a un backup: vive en el mismo sistema y desaparece si este falla.','It is instant and lightweight (copy-on-write), ideal before a risky change; but it is NOT a backup: it lives on the same system and is gone if that system fails.'),facts:[F('Casi instantáneo, poco espacio al principio.','Almost instant, little space at first.'),F('No es un backup: mismo almacenamiento.','Not a backup: same underlying storage.')]},
      {id:'replication',cat:'backup',code:'REPL',name:F('Replicación / DR','Replication / DR'),why:F('Copia los datos de forma continua a un sitio secundario para seguir operando si cae el principal.','Continuously copies data to a secondary site so you keep operating if the primary goes down.'),desc:F('Es la base de la recuperación ante desastres: se mide con RPO (cuántos datos puedes perder) y RTO (cuánto tardas en recuperar el servicio).','It is the foundation of disaster recovery: measured by RPO (how much data you can lose) and RTO (how long to restore service).'),facts:[F('RPO y RTO definen el objetivo de recuperación.','RPO and RTO define the recovery target.'),F('Síncrona (sin pérdida) o asíncrona (más barata).','Synchronous (no loss) or asynchronous (cheaper).')]},
      {id:'velero',cat:'backup',code:'VELO',name:F('Velero (K8s)','Velero (K8s)'),why:F('Copia y restaura los recursos de un clúster de Kubernetes y sus volúmenes.','Backs up and restores the resources of a Kubernetes cluster and its volumes.'),desc:F('Exporta los objetos del clúster (namespaces, deployments…) junto a snapshots de los volúmenes hacia object storage; sirve para migrar clústeres y para DR.','Exports cluster objects (namespaces, deployments…) along with volume snapshots to object storage; useful to migrate clusters and for DR.'),facts:[F('Backup por namespace o de todo el clúster.','Backup per namespace or of the whole cluster.'),F('Guarda las copias en object storage (S3…).','Stores backups in object storage (S3…).')]},
      {id:'veeam',cat:'backup',code:'VBR',name:F('Veeam Backup','Veeam Backup'),why:F('Hace copias de seguridad y replica servidores y VMs para poder restaurarlos ante fallos, borrados o ransomware.','Backs up and replicates servers and VMs so you can restore them after failures, deletions or ransomware.'),desc:F('Protege máquinas virtuales, físicas y cargas en la nube con copias incrementales, verificación automática y recuperación rápida, incluida la recuperación ante desastres (DR).','Protects virtual, physical and cloud workloads with incremental backups, automatic verification and fast recovery, including disaster recovery (DR).'),facts:[F('Sigue la regla 3-2-1: 3 copias, 2 medios, 1 fuera del sitio.','Follows the 3-2-1 rule: 3 copies, 2 media, 1 off-site.'),F('Restauración granular: desde un archivo hasta una VM entera.','Granular restore: from a single file to a whole VM.')],term:[['$','veeam job start --name Backup-Prod'],['','Creating incremental restore point...'],['','Verifying backup (SureBackup)... OK'],['','Job finished: 42 VMs protected']]},
      // MONITORIZACION (ampliación)
      {id:'zabbix',cat:'monitorizacion',code:'ZBX',name:F('Zabbix','Zabbix'),why:F('Monitoriza la disponibilidad y el rendimiento de servidores, red y servicios, y avisa cuando algo falla.','Monitors availability and performance of servers, network and services, and alerts when something breaks.'),desc:F('Recoge métricas con o sin agente (SNMP, IPMI), detecta problemas con umbrales y triggers, y dispara alertas; muy usado en infraestructura on-premise.','Collects metrics with or without agents (SNMP, IPMI), detects issues via thresholds and triggers, and fires alerts; widely used in on-prem infrastructure.'),facts:[F('Agentes o SNMP para vigilar también equipos de red.','Agents or SNMP to also watch network gear.'),F('Plantillas y triggers para alertar sin repetir configuración.','Templates and triggers to alert without repeating config.')]},
    ];
};

// --- dimensionado (antes specsBase()) ---
window.LABSTACK.dimensionado = function () {
    // valores didácticos por categoría: coste €/mes, CPU vCPU, RAM GB (por pieza colocada)
    return {
      red:{cost:40,cpu:1,ram:1}, computo:{cost:120,cpu:16,ram:64}, almacenamiento:{cost:60,cpu:0,ram:0},
      virtualizacion:{cost:25,cpu:2,ram:8}, hci:{cost:150,cpu:16,ram:64}, so:{cost:0,cpu:1,ram:2},
      contenedores:{cost:10,cpu:1,ram:2}, orquestacion:{cost:35,cpu:2,ram:4}, mensajeria:{cost:30,cpu:2,ram:4}, datos:{cost:80,cpu:4,ram:16},
      nube:{cost:110,cpu:0,ram:0}, seguridad:{cost:25,cpu:1,ram:1}, cicd:{cost:15,cpu:1,ram:2},
      iac:{cost:5,cpu:0,ram:0}, monitorizacion:{cost:20,cpu:1,ram:2}, gobernanza:{cost:20,cpu:0,ram:0}, backup:{cost:25,cpu:1,ram:2},
    };
};
