// Todos los textos de interfaz, en español e inglés.
// Contenido de LabStack — se puede editar sin tocar la lógica de la app.
// Se carga con <script src> (no con fetch) para que la app siga abriéndose
// con doble clic, sin servidor. Cada entrada es una función: devuelve un
// objeto nuevo en cada llamada, igual que hacían los métodos originales.
window.LABSTACK = window.LABSTACK || {};

// --- textos (antes strings()) ---
window.LABSTACK.textos = function () {
    const es = {
      title:'LabStack', subtitle:'Laboratorio visual de infraestructura — arrastra y construye tu stack',
      progress:'Progreso', reset:'Reiniciar', palette:'Tecnologías', paletteHint:'Arrastra una pieza al árbol, o toca para armarla y luego toca su capa.',
      canvasTitle:'Árbol de infraestructura', keyIdeas:'Ideas clave', flow:'Cómo funciona', terminal:'Terminal (simulada)',
      placingHint:'seleccionada — toca (o pulsa Enter en) la capa donde colocarla.', placingCancel:'Cancelar',
      guideTitle:'Bienvenido al laboratorio', guideIntro:'Construye una infraestructura completa de abajo hacia arriba, igual que en la vida real: primero la red, al final la nube. Cada pieza mal colocada te explicará por qué.',
      howto:[{n:'1',text:'Elige una tecnología del panel izquierdo y arrástrala al árbol (o toca la pieza y luego la capa).'},{n:'2',text:'Si aciertas la capa, la pieza se coloca y recibes su explicación. Si no, te decimos dónde va y por qué.'},{n:'3',text:'Toca una capa (sin pieza en mano) para leer por qué existe, qué pasa si falta y una analogía.'},{n:'4',text:'Completa las capas y pulsa «Simular flujo» para ver, paso a paso, una petición recorrer tu stack.'}],
      checklist:'Capas del stack', done:'capas completas', flowLabel:'Simular flujo', flowRunning:'Fluyendo…',
      okTitle:'Correcto', errTitle:'Revisa esto', infoTitle:'Aviso',
      themeDark:'Modo oscuro', themeLight:'Modo claro',
      whyLayer:'¿Por qué esta capa?', ifMissing:'¿Qué pasa si falta?', analogy:'Analogía', belongs:'Qué colocar aquí', layerInfoHint:'Toca una capa vacía para leer su explicación.',
      suggestedTag:'empieza aquí', targetTag:'aquí va',
      modeFree:'Aprender', modeMission:'Misión', modeQuiz:'Quiz',
      missionPick:'Elige un reto y móntalo en el árbol', missionGoals:'Objetivos', missionCheck:'Evaluar reto', missionExit:'Cambiar de reto',
      lvlBasic:'Básico', lvlInter:'Intermedio', lvlAdv:'Avanzado',
      missionMet:'cumplidos', missionDoneT:'¡Reto superado!', missionPartialT:'Casi… revisa lo que falta', missionMissLabel:'Te falta:',
      quizTitle:'Pon a prueba lo que sabes', quizQ:'¿A qué capa pertenece esta pieza?', quizNext:'Siguiente', quizResult:'Ver resultado',
      quizScore:'Aciertos', quizRestart:'Repetir quiz', quizRight:'¡Correcto!', quizWrong:'No exactamente', quizDoneT:'Quiz completado', quizStart:'Empezar quiz', quizQuestion:'Pregunta',
      modeMap:'Mapa', modeTerminal:'Terminal', modeMetrics:'Métricas', modeHttp:'Petición', simGroup:'Simuladores', navModes:'Modos de aprendizaje', toolsBtn:'Herramientas', closeLbl:'Cerrar', cmdRefBtn:'Comandos', cmdRefTitle:'Referencia de comandos', cmdRefSubtitle:'Toca un comando para insertarlo en la terminal.', cmdRefSearch:'Buscar comando…', cmdRefResults:'comandos', cmdRefEmpty:'Sin resultados', metTitle:'Métricas en vivo', metLoad:'Carga simulada', metLoadHint:'Sube la carga y observa cómo responde tu stack (modelo, no medición real).', metAlertsLabel:'Alertas', termTitle:'terminal', mapHint:'Rueda: zoom · arrastra: mover · toca una pieza para su ficha · pasa por un cable para ver qué conecta · ⤢ mapa entero', mapDemo:'Ejemplo — monta tu stack en «Aprender» para ver el tuyo', mapPieces:'piezas',
      httpTitle:'Petición HTTP — recorrido', httpHint:'Sigue una petición salto a salto por tu stack y mira dónde se va el tiempo (modelo didáctico, no medición real).', httpRelaunch:'Relanzar petición', httpTotal:'Tiempo total', httpTapHint:'Toca un salto para simular su caída y ver cómo falla la petición.', httpNotesLabel:'Avisos', httpHopsLabel:'saltos', httpClearFail:'Quitar caída simulada',
      modeDeploy:'Despliegue', depTitle:'Simulador de despliegue', depHint:'Compara estrategias para publicar una versión nueva (v1 → v2) y observa cómo cambia el tráfico, sin cortar el servicio.', depTraffic:'Reparto de tráfico', depDowntime:'Downtime', depStep:'Paso', depReset:'Reiniciar', depRollback:'Rollback', depNext:'Siguiente', depPrev:'Anterior', depDoneTag:'Completo', depV1:'v1 (actual)', depV2:'v2 (nueva)', depUpd:'actualizando',
      modeIncident:'Incidente', incTitle:'Sala de incidentes', incHint:'Diagnostica una avería real: reúne pistas, identifica la causa raíz y aplica el arreglo correcto.', incPickHint:'Elige un incidente para resolver:', incSymptom:'Síntoma', incStartBtn:'Empezar a investigar', incChecks:'Comprobaciones', incChecksHint:'Toca una comprobación para ver su salida.', incToDiagnose:'Ya tengo una hipótesis →', incDiagnoseTitle:'¿Cuál es la causa raíz?', incConfirmCause:'Confirmar causa', incBackInvestigate:'← Volver a investigar', incFixTitle:'¿Cómo lo arreglas?', incApplyFix:'Aplicar arreglo', incResolvedTag:'Incidente resuelto', incLearnLabel:'Aprendizaje', incAnother:'Elegir otro incidente', incRetry:'Reintentar', incPhInvestigate:'Investigar', incPhDiagnose:'Diagnosticar', incPhFix:'Arreglar', incExit:'Salir',
      quizAdaptive:'Adaptativo: las categorías donde fallas volverán a aparecer más.', quizWeak:'A reforzar', quizMastered:'Dominadas',
      chaosStart:'Simular avería', chaosOn:'Toca una pieza…', chaosResil:'Resiliencia', chaosSpof:'puntos únicos de fallo', chaosHint:'Modo avería: toca una pieza para tirarla y ver el impacto.',
      analysisTitle:'Análisis de arquitectura', analysisRobust:'Robustez', mapLegend:'Leyenda', legFlow:'camino de la petición', legDep:'necesita debajo', legOps:'opera sobre', flowPacket:'GET /',
      infoUse:'¿Cuándo usarla?', infoAlt:'Alternativas',
      sizingTitle:'Dimensionado', szCost:'Coste', szBudget:'Presupuesto', szMonth:'€/mes', szPerMonth:'€/mes', szUnitCpu:'vCPU', szUnitRam:'GB', szEach:'por pieza',
      searchPh:'Buscar tecnología…', famAllLabel:'Todas', noResults:'Sin resultados',
      share:'Compartir', copied:'¡Copiado!',
      achTitle:'Logros', achSubtitle:'Desbloquea medallas construyendo y aprendiendo', toastLabel:'¡Logro desbloqueado!',
      achReset:'Reiniciar logros', achResetConfirm:'¿Borrar todo el progreso de logros?', achResetYes:'Sí, borrar', achCancel:'Cancelar',
      contentTitle:'Modo profesor · Contenido', contentSubtitle:'Añade piezas y misiones propias en JSON. Se guardan en este navegador y se aplican al instante.', contentApply:'Aplicar', contentClearBtn:'Limpiar', contentExportBtn:'Exportar .json', contentTpl:'Plantilla', contentFile:'Subir archivo', contentPlaceholder:'Pega aquí el JSON del pack de contenido…', contentActiveLbl:'Cargado ahora:', contentPiecesLbl:'piezas', contentMissionsLbl:'misiones',
      tour:'Tour', tourNext:'Siguiente', tourPrev:'Anterior', tourFinish:'Terminar', tourWhy:'¿Por qué existe?', tourMiss:'¿Qué pasa si falta?', tourAnal:'Analogía', exportLabel:'Exportar',
      stackExport:'Exportar stack (.json)', stackImport:'Importar stack (.json)',
      pathTitle:'Ruta de aprendizaje', pathSubtitle:'Un camino guiado de 0 a arquitecto: teoría, retos y quiz en orden.', pathRead:'Leer', pathHide:'Ocultar', pathMarkRead:'Marcar como leído', pathStart:'Empezar reto', pathDoQuiz:'Hacer quiz', pathGo:'Ir', pathCurrent:'Siguiente paso',
      glTitle:'Glosario', glSubtitle:'Todos los términos con su definición. Busca y toca uno para ampliarlo.', glSearch:'Buscar término…', glCat:'Categoría', glView:'Ver ficha', glResults:'términos', glEmpty:'Sin resultados',
      homeBack:'Volver al inicio', moreBtn:'Más',
      navBuild:'Aprender', navPractice:'Practicar', navExplore:'Explorar', navKids:'Kids',
      navKidsHint:'Para peques: la infraestructura paso a paso, jugando',
      cardKidsT:'Kids', cardKidsD:'Para los más peques. Dos partidas cortas, una capa cada vez, con dibujos y sin equivocarse nunca del todo.', cardKidsM:'2 partidas · a partir de 8 años',
      navBuildHint:'Monta tu stack pieza a pieza y entiende cada capa', navPracticeHint:'Retos con objetivos y quiz de repaso', navExploreHint:'Mira tu stack desde otros ángulos: mapa, petición, despliegue…',
      homeContinue:'Seguir donde lo dejaste', homeContinueDesc:'Vuelve a tu stack y sigue montando.',
      homeJobT:'Puesto real: Administración de sistemas Linux', homeJobD:'Veinte tickets sobre una plataforma OpenStack + Ceph simulada. Se arreglan con comandos: ssh, systemctl, ceph, ansible-playbook, terraform.', homeJobCta:'Abrir el puesto',
      cardLearnT:'Aprender', cardLearnD:'Monta un stack completo de abajo hacia arriba. Cada pieza que colocas te explica qué hace y por qué va ahí.', cardLearnM:'Empieza aquí si es tu primera vez',
      cardPracticeT:'Practicar', cardPracticeD:'Retos con objetivos concretos y presupuesto, y un quiz que insiste donde fallas.', cardPracticeM:'Retos · Quiz adaptativo',
      cardExploreT:'Explorar', cardExploreD:'Tu stack visto como datacenter, como petición HTTP, como despliegue o como métricas, y un puesto de guardia con tickets reales.', cardExploreM:'8 vistas · simuladores',
      statPieces:'tecnologías', statLayers:'capas', statMissions:'retos', statModes:'vistas',
      modeEvents:'Eventos', modeDesk:'Puesto', deskLesson:'Lo que te llevas', deskNext:'Volver a la cola',
      subnavLabel:'Vista', canvasSub:'De abajo hacia arriba: primero la red, al final la nube.',
      densCompact:'Compacto', densDetail:'Detalle', densCompactHint:'Ver el stack entero de un vistazo', densDetailHint:'Ver la explicación de cada capa',
      progressTitle:'Tu progreso', progLayers:'capas', progPillars:'pilares',
      nextStepLbl:'Siguiente:', allDoneMsg:'Stack completo. Pulsa «Simular flujo» para verlo funcionar.', emptyStepMsg:'Empieza por abajo: coloca algo en Redes.',
      pillarsHint:'atraviesan todas las capas, no viven dentro de una',
      planeRoles:{ cloud:'servicios de terceros, bajo demanda', data:'dónde vive el estado', app:'dónde corre tu código', plat:'convierte el hierro en recursos', phys:'el hierro y los cables' },
      printTitle:'Resumen de arquitectura — LabStack', printStack:'Stack montado', printRobust:'Robustez', printCost:'Coste estimado', printEmpty:'No hay piezas montadas.',
    };
    const en = {
      title:'LabStack', subtitle:'Visual infrastructure lab — drag and build your stack',
      progress:'Progress', reset:'Reset', palette:'Technologies', paletteHint:'Drag a piece onto the tree, or tap to arm it and then tap its layer.',
      canvasTitle:'Infrastructure tree', keyIdeas:'Key ideas', flow:'How it works', terminal:'Terminal (simulated)',
      placingHint:'selected — tap (or press Enter on) the layer to place it.', placingCancel:'Cancel',
      guideTitle:'Welcome to the lab', guideIntro:'Build a full infrastructure from the bottom up, just like in real life: networking first, cloud last. Every misplaced piece will explain why.',
      howto:[{n:'1',text:'Pick a technology from the left panel and drag it onto the tree (or tap the piece, then the layer).'},{n:'2',text:'If you hit the right layer, the piece lands and you get its explanation. If not, we tell you where it goes and why.'},{n:'3',text:'Tap a layer (with no piece in hand) to read why it exists, what breaks without it, and an analogy.'},{n:'4',text:'Fill the layers and hit “Run flow” to watch, step by step, a request travel through your stack.'}],
      checklist:'Stack layers', done:'layers complete', flowLabel:'Run flow', flowRunning:'Flowing…',
      okTitle:'Correct', errTitle:'Check this', infoTitle:'Note',
      themeDark:'Dark mode', themeLight:'Light mode',
      whyLayer:'Why this layer?', ifMissing:'What if it is missing?', analogy:'Analogy', belongs:'What goes here', layerInfoHint:'Tap an empty layer to read its explanation.',
      suggestedTag:'start here', targetTag:'goes here',
      modeFree:'Learn', modeMission:'Mission', modeQuiz:'Quiz',
      missionPick:'Pick a challenge and build it on the tree', missionGoals:'Goals', missionCheck:'Evaluate', missionExit:'Change challenge',
      lvlBasic:'Basic', lvlInter:'Intermediate', lvlAdv:'Advanced',
      missionMet:'met', missionDoneT:'Challenge complete!', missionPartialT:'Almost… check what is missing', missionMissLabel:'Still missing:',
      quizTitle:'Test what you know', quizQ:'Which layer does this piece belong to?', quizNext:'Next', quizResult:'See result',
      quizScore:'Score', quizRestart:'Retry quiz', quizRight:'Correct!', quizWrong:'Not quite', quizDoneT:'Quiz complete', quizStart:'Start quiz', quizQuestion:'Question',
      modeMap:'Map', modeTerminal:'Terminal', modeMetrics:'Metrics', modeHttp:'Request', simGroup:'Simulators', navModes:'Learning modes', toolsBtn:'Tools', closeLbl:'Close', cmdRefBtn:'Commands', cmdRefTitle:'Command reference', cmdRefSubtitle:'Tap a command to insert it in the terminal.', cmdRefSearch:'Search command…', cmdRefResults:'commands', cmdRefEmpty:'No results', metTitle:'Live metrics', metLoad:'Simulated load', metLoadHint:'Raise the load and watch your stack respond (a model, not real measurement).', metAlertsLabel:'Alerts', termTitle:'terminal', mapHint:'Wheel: zoom · drag: pan · tap a piece for details · hover a cable to see what it connects · ⤢ whole map', mapDemo:'Example — build your stack in “Learn” to see yours', mapPieces:'pieces',
      httpTitle:'HTTP request — waterfall', httpHint:'Follow a request hop by hop across your stack and see where the time goes (a didactic model, not real measurement).', httpRelaunch:'Relaunch request', httpTotal:'Total time', httpTapHint:'Tap a hop to simulate its failure and see how the request breaks.', httpNotesLabel:'Warnings', httpHopsLabel:'hops', httpClearFail:'Clear simulated failure',
      modeDeploy:'Deploy', depTitle:'Deployment simulator', depHint:'Compare strategies to ship a new version (v1 → v2) and watch traffic shift, with no service interruption.', depTraffic:'Traffic split', depDowntime:'Downtime', depStep:'Step', depReset:'Reset', depRollback:'Rollback', depNext:'Next', depPrev:'Previous', depDoneTag:'Done', depV1:'v1 (current)', depV2:'v2 (new)', depUpd:'updating',
      modeIncident:'Incident', incTitle:'Incident room', incHint:'Diagnose a real outage: gather clues, identify the root cause and apply the right fix.', incPickHint:'Pick an incident to resolve:', incSymptom:'Symptom', incStartBtn:'Start investigating', incChecks:'Checks', incChecksHint:'Tap a check to see its output.', incToDiagnose:'I have a hypothesis →', incDiagnoseTitle:'What is the root cause?', incConfirmCause:'Confirm cause', incBackInvestigate:'← Back to investigating', incFixTitle:'How do you fix it?', incApplyFix:'Apply fix', incResolvedTag:'Incident resolved', incLearnLabel:'Takeaway', incAnother:'Pick another incident', incRetry:'Retry', incPhInvestigate:'Investigate', incPhDiagnose:'Diagnose', incPhFix:'Fix', incExit:'Exit',
      quizAdaptive:'Adaptive: the categories you miss will show up more often.', quizWeak:'To review', quizMastered:'Mastered',
      chaosStart:'Simulate failure', chaosOn:'Tap a piece…', chaosResil:'Resilience', chaosSpof:'single points of failure', chaosHint:'Failure mode: tap a piece to drop it and see the impact.',
      analysisTitle:'Architecture analysis', analysisRobust:'Robustness', mapLegend:'Legend', legFlow:'request path', legDep:'needs underneath', legOps:'operates on', flowPacket:'GET /',
      infoUse:'When to use it', infoAlt:'Alternatives',
      sizingTitle:'Sizing', szCost:'Cost', szBudget:'Budget', szMonth:'€/mo', szPerMonth:'€/mo', szUnitCpu:'vCPU', szUnitRam:'GB', szEach:'per piece',
      searchPh:'Search technology…', famAllLabel:'All', noResults:'No results',
      share:'Share', copied:'Copied!',
      achTitle:'Achievements', achSubtitle:'Unlock badges by building and learning', toastLabel:'Achievement unlocked!',
      achReset:'Reset achievements', achResetConfirm:'Erase all achievement progress?', achResetYes:'Yes, erase', achCancel:'Cancel',
      contentTitle:'Teacher mode · Content', contentSubtitle:'Add your own pieces and missions as JSON. Saved in this browser and applied instantly.', contentApply:'Apply', contentClearBtn:'Clear', contentExportBtn:'Export .json', contentTpl:'Template', contentFile:'Upload file', contentPlaceholder:'Paste the content pack JSON here…', contentActiveLbl:'Loaded now:', contentPiecesLbl:'pieces', contentMissionsLbl:'missions',
      tour:'Tour', tourNext:'Next', tourPrev:'Back', tourFinish:'Finish', tourWhy:'Why it exists', tourMiss:'What if it is missing?', tourAnal:'Analogy', exportLabel:'Export',
      stackExport:'Export stack (.json)', stackImport:'Import stack (.json)',
      pathTitle:'Learning path', pathSubtitle:'A guided path from zero to architect: theory, challenges and quiz in order.', pathRead:'Read', pathHide:'Hide', pathMarkRead:'Mark as read', pathStart:'Start challenge', pathDoQuiz:'Take quiz', pathGo:'Go', pathCurrent:'Next step',
      glTitle:'Glossary', glSubtitle:'Every term with its definition. Search and tap one to expand.', glSearch:'Search term…', glCat:'Category', glView:'View card', glResults:'terms', glEmpty:'No results',
      homeBack:'Back to start', moreBtn:'More',
      navBuild:'Learn', navPractice:'Practice', navExplore:'Explore', navKids:'Kids',
      navKidsHint:'For kids: infrastructure step by step, by playing',
      cardKidsT:'Kids', cardKidsD:'For the youngest. Two short games, one layer at a time, with drawings and no real way to get it wrong.', cardKidsM:'2 games · ages 8+',
      navBuildHint:'Build your stack piece by piece and understand every layer', navPracticeHint:'Goal-based challenges and a revision quiz', navExploreHint:'See your stack from other angles: map, request, deployment…',
      homeContinue:'Pick up where you left off', homeContinueDesc:'Go back to your stack and keep building.',
      homeJobT:'Real job: Linux systems administration', homeJobD:'Twenty tickets on a simulated OpenStack + Ceph platform, fixed with real commands: ssh, systemctl, ceph, ansible-playbook, terraform.', homeJobCta:'Open the desk',
      cardLearnT:'Learn', cardLearnD:'Build a full stack from the bottom up. Every piece you place explains what it does and why it goes there.', cardLearnM:'Start here if it is your first time',
      cardPracticeT:'Practice', cardPracticeD:'Challenges with concrete goals and budgets, plus a quiz that insists where you slip.', cardPracticeM:'Challenges · Adaptive quiz',
      cardExploreT:'Explore', cardExploreD:'Your stack seen as a datacenter, as an HTTP request, as a deployment or as metrics, plus an on-call desk with real tickets.', cardExploreM:'8 views · simulators',
      statPieces:'technologies', statLayers:'layers', statMissions:'challenges', statModes:'views',
      modeEvents:'Events', modeDesk:'Desk', deskLesson:'What you take away', deskNext:'Back to the queue',
      subnavLabel:'View', canvasSub:'Bottom-up: networking first, cloud last.',
      densCompact:'Compact', densDetail:'Detail', densCompactHint:'See the whole stack at a glance', densDetailHint:'See the explanation of every layer',
      progressTitle:'Your progress', progLayers:'layers', progPillars:'pillars',
      nextStepLbl:'Next:', allDoneMsg:'Stack complete. Hit “Run flow” to watch it work.', emptyStepMsg:'Start at the bottom: place something in Networking.',
      pillarsHint:'they cut across every layer, they do not live inside one',
      planeRoles:{ cloud:'third-party services, on demand', data:'where state lives', app:'where your code runs', plat:'turns metal into resources', phys:'the metal and the cables' },
      printTitle:'Architecture summary — LabStack', printStack:'Built stack', printRobust:'Robustness', printCost:'Estimated cost', printEmpty:'No pieces placed.',
    };
    return { es, en };
};
