// Puesto · solucionario: por qué se hace cada paso, y el glosario.
//
// Los comandos NO se repiten aquí: salen del `guion` de cada escenario. Cada
// paso sólo añade la fase y la explicación, en el mismo orden. puesto-test.js
// exige que `pasos` y `guion` coincidan comando a comando, así que si alguien
// cambia un guion, el solucionario deja de pasar el test hasta que se actualice.
//
//   fase: 'diag' (mirar) · 'arreglo' (cambiar algo) · 'comprobar' · '' (moverse)
//   <ID>, <IP> en un comando = se copia de una salida anterior.
(function (P) {
'use strict';

P.soluciones = {
'INC-4821': {
  terminos: ['osd', 'health', 'down-out', 'start-limit', 'recent-crash', 'smart'],
  pasos: [
    ['ceph -s', 'diag', 'La foto general: 1 OSD down, 160 PGs degradadas y RECENT_CRASH. No se ha perdido nada: quedan dos copias de cada dato.'],
    ['ssh ceph02', '', 'osd.4 vive en ceph02 (lo dicen la alerta y ceph osd tree). Un servicio se mira en su nodo.'],
    ['journalctl -u ceph-osd@4 -n 20', 'diag', 'Tres "suicide timed out" seguidos y "Start request repeated too quickly": el proceso se colgó tres veces y systemd dejó de reintentarlo.'],
    ['sudo smartctl -a /dev/sdc', 'diag', 'Antes de levantarlo, descarta el hardware: osd.4 es /dev/sdc y SMART dice PASSED. Si dijera FAILED, estarías en el INC-4847.'],
    ['sudo systemctl reset-failed ceph-osd@4', 'arreglo', 'Borra el contador de arranques fallidos. Sin esto, start y restart se niegan a intentarlo.'],
    ['sudo systemctl start ceph-osd@4', 'arreglo', 'El OSD vuelve y se pone al día con lo escrito mientras estuvo caído: una recuperación corta, sin mover datos.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ceph crash ls', 'diag', 'Los tres crashes siguen marcados como nuevos (*): son lo que mantiene el HEALTH_WARN.'],
    ['ceph crash archive-all', 'arreglo', 'Archivar significa "visto y documentado". No borra nada.'],
    ['sleep 60', '', 'Un minuto para que termine la recuperación.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK, 9 OSD up y 9 in.'],
  ],
},
'REQ-1307': {
  terminos: ['openrc', 'cuota', 'replica'],
  pasos: [
    ['source ~/admin-openrc', '', 'Carga las credenciales de admin: sin ellas el cliente de OpenStack no sabe a qué nube hablar.'],
    ['openstack quota show --usage tienda-online', 'diag', '950 de 1000 GB usados: un volumen de 500 GB no cabe en la cuota.'],
    ['ceph df', 'diag', 'La cuota es una promesa; esto es lo que hay. MAX AVAIL del pool volumes (unos 1,8 TiB) confirma que hay sitio real para 500 GB más.'],
    ['openstack quota set --gigabytes 1500 tienda-online', 'arreglo', '950 + 500 = 1450. 1500 deja margen sin regalar capacidad que no existe.'],
    ['openstack quota show tienda-online', 'comprobar', 'El nuevo límite está aplicado.'],
  ],
},
'REQ-1315': {
  terminos: ['openrc', 'proyecto', 'rol-admin', 'cuota'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales de admin para el cliente de OpenStack.'],
    ['openstack project create --description "Franquicia Valencia" tienda-valencia', 'arreglo', 'Crea el proyecto. Nace con la cuota por defecto: 10 instancias, 20 cores y 1000 GB.'],
    ['openstack user create --project tienda-valencia --email jgarcia@retail.es --password-prompt jgarcia', 'arreglo', 'Crea el usuario. --password-prompt pide la contraseña sin que quede en el historial ni en la lista de procesos.'],
    ['Temporal-2026!', '', 'La contraseña. No se ve al escribirla.'],
    ['Temporal-2026!', '', 'Repetida, para confirmar.'],
    ['openstack role add --project tienda-valencia --user jgarcia member', 'arreglo', 'member: trabaja en su proyecto y no ve los demás. admin aquí sería admin de toda la nube.'],
    ['openstack role assignment list --project tienda-valencia --names', 'comprobar', 'jgarcia con member en tienda-valencia, y nada más.'],
    ['openstack quota set --instances 10 --cores 40 --gigabytes 500 tienda-valencia', 'arreglo', 'La cuota pedida: sube lo que falta (cores de 20 a 40) y baja lo que sobra (volúmenes de 1000 a 500 GB).'],
    ['openstack quota show tienda-valencia', 'comprobar', '10 instancias, 40 cores y 500 GB.'],
  ],
},
'INC-4830': {
  terminos: ['openrc', 'no-valid-host', 'nova-compute', 'libvirt', 'enable-start'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales para el cliente de OpenStack.'],
    ['openstack compute service list', 'diag', 'nova-compute de cmp02 está down desde ayer por la tarde.'],
    ['openstack hypervisor list --long', 'diag', 'cmp01 y cmp03 casi sin RAM libre y cmp02 fuera: por eso una VM de 16 GB no cabe en ningún sitio.'],
    ['ssh cmp02', '', 'Al hipervisor que falla.'],
    ['systemctl status nova-compute', 'diag', '"Failed to connect socket to /var/run/libvirt/libvirt-sock": nova-compute no encuentra a libvirt, que es quien maneja las VMs.'],
    ['sudo systemctl enable --now libvirtd', 'arreglo', 'Habilita y arranca libvirt. El enable es lo que evita que vuelva a pasar en el próximo reinicio.'],
    ['sudo systemctl restart nova-compute', 'arreglo', 'Ahora sí conecta con el hipervisor y vuelve a presentarse al scheduler.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['openstack compute service list', 'comprobar', 'cmp02 vuelve a estar up.'],
    ['openstack server delete pedidos-api-v2-01 pedidos-api-v2-02', 'arreglo', 'Limpieza que autoriza el ticket: el pipeline las volverá a crear, y ahora caben.'],
  ],
},
'INC-4833': {
  terminos: ['alertmanager', 'rabbitmq', 'du-df', 'playbook', 'handler'],
  pasos: [
    ['amtool alert', 'diag', 'Tres alertas, las tres en ctl02: /var al 100 %, RabbitMQ fuera del clúster y una unidad en failed.'],
    ['ssh ctl02', '', 'Al controlador que se queja.'],
    ['df -h', 'diag', '/var al 100 % y 0 libres. Sin espacio, RabbitMQ no puede ni arrancar.'],
    ['du -sh /var/log/*', 'diag', 'df dice que está lleno; du dice quién lo llena: /var/log/rabbitmq pesa 31 GB.'],
    ['du -sh /var/log/rabbitmq/*', 'diag', 'El culpable es rabbit@ctl02.log: un log que alguien dejó en nivel debug.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['cd infra', '', 'ansible.cfg y el inventario viven aquí; Ansible sólo los encuentra desde esta carpeta.'],
    ['ansible-playbook playbooks/logrotate.yml -l ctl02', 'arreglo', 'Pone el nivel en info (la causa), rota y comprime el log (el síntoma) y el handler reinicia RabbitMQ.'],
    ['ssh ctl02', '', 'A comprobarlo en el nodo.'],
    ['sudo rabbitmqctl cluster_status', 'comprobar', 'rabbit@ctl02 vuelve a Running Nodes: el clúster tiene otra vez sus tres nodos y se acaban los 500.'],
  ],
},
'INC-4836': {
  terminos: ['clock-skew', 'chrony', 'alertmanager', 'adhoc', 'idempotencia'],
  pasos: [
    ['ceph health detail', 'diag', 'MON_CLOCK_SKEW en mon.ceph03: casi un segundo de desfase, veinte veces el máximo.'],
    ['amtool alert', 'diag', 'NodeClockNotSynchronising en ceph03… y en cmp01, que no tiene monitor de Ceph y por eso Ceph no lo ve.'],
    ['cd infra', '', 'La carpeta de Ansible.'],
    ['ansible all -m shell -a "timedatectl | grep synchronized"', 'diag', 'Una pregunta a toda la flota a la vez: sólo ceph03 y cmp01 contestan "no".'],
    ['ansible-playbook playbooks/chrony.yml', 'arreglo', 'Arranca y habilita chrony donde falta y fuerza la sincronización (makestep). En los otros diez nodos no cambia nada.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK.'],
  ],
},
'INC-4840': {
  terminos: ['nearfull', 'osd-df', 'balancer', 'pg'],
  pasos: [
    ['ceph health detail', 'diag', 'OSD_NEARFULL en osd.7 y todos los pools en nearfull.'],
    ['ceph osd df', 'diag', 'osd.7 al 87 % y el resto en torno al 57 %: VAR 1.45. Es un problema de reparto, no de capacidad.'],
    ['ceph balancer status', 'diag', '"active": false. Nadie está repartiendo.'],
    ['ceph balancer on', 'arreglo', 'El balancer (modo upmap) mueve PGs hasta igualar el uso de los OSD.'],
    ['sleep 420', '', 'El reparto tarda unos minutos.'],
    ['ceph osd df', 'comprobar', 'osd.7 vuelve a la media y STDDEV baja.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK.'],
  ],
},
'INC-4861': {
  terminos: ['certificado', 'recargar', 'playbook', 'handler'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales para el cliente de OpenStack.'],
    ['openstack server list --all-projects', 'diag', 'El mismo error que los pipelines: CERTIFICATE_VERIFY_FAILED, certificate has expired.'],
    ['curl -I https://api.retail.local:5000', 'diag', 'Confirmado sin el cliente de por medio: "SSL certificate problem: certificate has expired".'],
    ['ssh ctl01', '', 'ctl01 tiene la VIP (keepalived): su HAProxy es el que contesta.'],
    ['openssl x509 -in /etc/haproxy/certs/api.pem -noout -dates', 'diag', 'notAfter es hoy a las 08:20: el fichero en disco está caducado.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['cd infra', '', 'La carpeta de Ansible.'],
    ['ansible-playbook playbooks/certs.yml', 'arreglo', 'Copia el certificado renovado a los tres controladores, y el handler recarga HAProxy en cada uno.'],
    ['openssl s_client -connect api.retail.local:5000', 'comprobar', 'Verify return code: 0 (ok), y el notAfter pasa a dentro de un año.'],
    ['openstack server list --all-projects', 'comprobar', 'La API vuelve a responder.'],
  ],
},
'INC-4866': {
  terminos: ['galera', 'oom', 'split-brain', 'alertmanager'],
  pasos: [
    ['amtool alert', 'diag', 'GaleraClusterSizeLow en ctl01 y ctl02, y mariadb en failed en ctl03.'],
    ['ssh ctl01', '', 'A un nodo sano.'],
    ["sudo mysql -e \"SHOW STATUS LIKE 'wsrep_cluster_size'\"", 'diag', '2: el clúster sigue vivo y con quórum, pero le falta ctl03.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ssh ctl03', '', 'Al nodo caído.'],
    ['sudo dmesg | tail -n 5', 'diag', '"Out of memory: Killed process … (mariadbd)": lo mató el OOM killer, no un fallo de la base de datos.'],
    ['systemctl status mariadb', 'diag', 'failed (Result: oom-kill). Nada le impide volver a arrancar.'],
    ['sudo systemctl start mariadb', 'arreglo', 'Arranque normal: se une al clúster vivo y recibe lo que se perdió mientras estaba fuera (IST).'],
    ["sudo mysql -e \"SHOW STATUS LIKE 'wsrep_%'\"", 'comprobar', 'wsrep_cluster_size = 3, Synced, y las tres IPs en wsrep_incoming_addresses.'],
  ],
},
'INC-4875': {
  terminos: ['radio', 'ovs', 'nova-compute'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales para el cliente de OpenStack.'],
    ['openstack server show web-tienda-01', 'diag', 'ACTIVE y en cmp01: para nova la VM está bien. Apunta su IP.'],
    ['ping <IP>', 'diag', 'web-tienda-01 no responde.'],
    ['ping <IP>', 'diag', 'web-tienda-02, que vive en cmp02, sí responde: el problema está en un hipervisor, no en toda la red.'],
    ['openstack network agent list', 'diag', 'El agente de Open vSwitch de cmp01 aparece XXX.'],
    ['ssh cmp01', '', 'Al hipervisor afectado.'],
    ['systemctl status neutron-openvswitch-agent', 'diag', 'No consigue conectar con unix:/var/run/openvswitch/db.sock: Open vSwitch no está corriendo.'],
    ['sudo systemctl start openvswitch-switch', 'arreglo', 'Primero la base: Open vSwitch. El bloqueo que dejó la actualización ya se ha liberado.'],
    ['sudo systemctl restart neutron-openvswitch-agent', 'arreglo', 'Después el agente, que ahora sí encuentra a Open vSwitch y reconstruye los puertos de las VMs.'],
    ['sudo ovs-vsctl show', 'comprobar', 'br-int conectado (is_connected: true) y un puerto tap por cada VM de cmp01.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ping <IP>', 'comprobar', 'web-tienda-01 vuelve a responder.'],
  ],
},
'REQ-1319': {
  terminos: ['snapshot', 'ambito', 'rpo', 'openrc'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales de admin.'],
    ['openstack server list --project tienda-online', 'diag', 'Queda redis-carrito-01; redis-carrito-02 ya no existe.'],
    ['openstack image list', 'diag', 'Las copias nocturnas: la más reciente de redis-carrito-02 es la de 20260923, de las 03:00.'],
    ['openstack image show backup-redis-carrito-02-20260923', 'diag', 'Sus propiedades guardan cómo era la VM original: m1.medium, retail-net y proyecto tienda-online.'],
    ['openstack --os-project-name tienda-online server create --flavor m1.medium --image backup-redis-carrito-02-20260923 --network retail-net redis-carrito-02', 'arreglo', 'La VM nueva, desde la copia y en su proyecto, con el mismo flavor y la misma red.'],
    ['sleep 60', '', 'Un minuto para que arranque.'],
    ['openstack server show redis-carrito-02', 'comprobar', 'ACTIVE, en tienda-online y con la imagen de la copia.'],
  ],
},
'INC-4880': {
  terminos: ['estado-transitorio', 'cinder-volume', 'openrc', 'cuota'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales para el cliente de OpenStack.'],
    ['openstack volume list --all-projects', 'diag', 'pedidos-db-old, 400 GB, en deleting.'],
    ['openstack volume show pedidos-db-old', 'diag', 'os-vol-host-attr:host = ctl02@rbd-1: es el cinder-volume de ctl02 quien tenía que terminar el borrado. updated_at es de ayer.'],
    ['openstack volume service list', 'diag', 'cinder-volume de ctl02@rbd-1: down desde ayer por la tarde.'],
    ['ssh ctl02', '', 'Al controlador que tiene el servicio caído.'],
    ['systemctl status cinder-volume', 'diag', '"RADOS timed out": perdió la conexión con Ceph en mitad del borrado y murió.'],
    ['sudo systemctl restart cinder-volume', 'arreglo', 'Ceph ya responde: el servicio vuelve a arrancar.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['openstack volume set --state error pedidos-db-old', 'arreglo', 'Un volumen en deleting no admite otro borrado. Pasarlo a error lo desbloquea: es la forma de decir «esto se quedó a medias».'],
    ['openstack volume delete pedidos-db-old', 'arreglo', 'Ahora sí hay un cinder-volume vivo que lo termine.'],
    ['sleep 60', '', 'Un minuto para que cinder-volume lo borre en Ceph.'],
    ['openstack volume list --project tienda-online', 'comprobar', 'pedidos-db-old ya no está.'],
    ['openstack quota show --usage tienda-online', 'comprobar', 'gigabytes en uso: de 1000 a 600. Ya pueden crear el volumen nuevo.'],
  ],
},
'INC-4884': {
  terminos: ['fuga-memoria', 'instalado-corriendo', 'rolling-restart', 'oom'],
  pasos: [
    ['amtool alert', 'diag', 'NodeMemoryHighUtilization en ctl03, al 92 %.'],
    ['ssh ctl03', '', 'Al controlador que se está quedando sin memoria.'],
    ['free -h', 'diag', 'Cuánto: más de 110 de 128 GB usados.'],
    ['ps aux --sort=-rss | head -5', 'diag', 'Quién: nova-api con más de 60 GB de memoria residente. Normalmente ocupa uno.'],
    ['apt list --upgradable', 'diag', 'Hay una versión nueva de nova: 29.2.1.'],
    ['apt changelog nova-api', 'diag', '"Fix memory leak in nova-api when listing servers with many ports (LP: #2071234)": es exactamente esto.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['cd infra', '', 'La carpeta de Ansible.'],
    ['ansible-playbook playbooks/nova-patch.yml', 'arreglo', 'Instala la 29.2.1 y reinicia nova-api en los tres controladores, de uno en uno: la API nunca se queda sin servicio.'],
    ['ssh ctl03', '', 'A comprobarlo.'],
    ['free -h', 'comprobar', 'La memoria vuelve a su sitio, y con el parche cargado ya no volverá a subir.'],
  ],
},
'CHG-0218': {
  terminos: ['cambio', 'noout', 'down-out', 'playbook'],
  pasos: [
    ['ceph -s', 'diag', 'El punto de partida está sano. Un cambio no empieza sobre un clúster degradado.'],
    ['cd infra', '', 'La carpeta de Ansible.'],
    ['ansible-playbook playbooks/os-update.yml -l ceph02', 'arreglo', 'Instala el kernel nuevo en ceph02. A propósito no reinicia: eso va aparte y con cuidado.'],
    ['ansible-playbook playbooks/ceph-reboot.yml -l ceph02', 'arreglo', 'Comprueba HEALTH_OK, pone noout, reinicia, espera a los OSD y a la recuperación, y quita noout.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK y sin flags.'],
    ['ssh ceph02', '', 'Al nodo parcheado.'],
    ['uname -r', 'comprobar', '5.15.0-122-generic: el kernel nuevo está cargado.'],
  ],
},
'INC-4847': {
  terminos: ['noout', 'down-out', 'smart', 'osd', 'recent-crash', 'degraded'],
  pasos: [
    ['ceph health detail', 'diag', 'Dos líneas clave: OSD_DOWN (osd.7) y OSDMAP_FLAGS (noout). La segunda explica por qué Ceph no se ha curado solo.'],
    ['ceph osd metadata 7', 'diag', 'osd.7 está en ceph03, disco sdc, con su número de serie: lo que necesita hardware para cambiarlo.'],
    ['ssh ceph03', '', 'Al nodo del disco.'],
    ['sudo smartctl -a /dev/sdc', 'diag', 'SMART FAILED: el disco está muerto. No se reinicia: se saca y se cambia.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ceph crash ls', 'diag', 'El crash de osd.7 al fallar la lectura.'],
    ['ceph osd unset noout', 'arreglo', 'Quita el flag olvidado del cambio de anoche.'],
    ['ceph osd out 7', 'arreglo', 'Saca el OSD ya, sin esperar: Ceph empieza a reconstruir sus réplicas en los otros ocho.'],
    ['sleep 600', '', 'La reconstrucción tarda unos minutos.'],
    ['ceph crash archive-all', 'arreglo', 'Crash leído y archivado.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK con 8 OSD up y 8 in. Queda abrir el ticket a hardware para /dev/sdc de ceph03.'],
  ],
},
'INC-4871': {
  terminos: ['quorum', 'admin-socket', 'fallo-latente', 'start-limit', 'enable-start', 'recent-crash'],
  pasos: [
    ['amtool alert', 'diag', 'CephHealthError con MON_DOWN y ceph-mon@ceph03 en failed: el clúster ha perdido el quórum.'],
    ['ssh ceph01', '', 'Al único monitor que sigue vivo.'],
    ['sudo ceph daemon mon.ceph01 mon_status', 'diag', '"state": "probing" y quorum vacío: ceph01 está solo, buscando a los demás. El socket responde aunque ceph -s se cuelgue.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ssh ceph03', '', 'Al monitor caído hoy.'],
    ['systemctl status ceph-mon@ceph03', 'diag', 'Un fallo de Paxos tres veces seguidas y "Start request repeated too quickly": systemd ha dejado de intentarlo.'],
    ['sudo systemctl reset-failed ceph-mon@ceph03', 'arreglo', 'Limpia el contador de arranques fallidos.'],
    ['sudo systemctl start ceph-mon@ceph03', 'arreglo', 'Con ceph01 y ceph03 ya son 2 de 3: vuelve el quórum.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ssh ceph02', '', 'Al monitor que lleva días fuera.'],
    ['journalctl -u ceph-mon@ceph02 -n 5', 'diag', '"systemctl disable --now ceph-mon@ceph02" hace tres días, durante el CHG-0215. Nadie lo volvió a encender.'],
    ['sudo systemctl enable --now ceph-mon@ceph02', 'arreglo', 'Habilitado y arrancado: vuelven a ser tres.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ceph crash archive-all', 'arreglo', 'El crash de mon.ceph03, leído y archivado.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK y quórum de ceph01, ceph02 y ceph03.'],
  ],
},
'INC-4889': {
  terminos: ['config-central', 'nivel-log', 'du-df', 'adhoc', 'quorum'],
  pasos: [
    ['ceph health detail', 'diag', 'MON_DOWN (ceph01) y MON_DISK_LOW en ceph02: el problema no es sólo de un nodo.'],
    ['ssh ceph01', '', 'Al nodo del monitor caído.'],
    ['df -h', 'diag', '/ al 100 %.'],
    ['sudo du -sh /var/log/ceph/*', 'diag', 'ceph-mon.ceph01.log pesa 35 GB: un monitor escribiendo en debug.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ceph config dump', 'diag', 'mon · debug_mon · 20/20: alguien lo subió para depurar y nunca lo bajó. Afecta a los tres monitores.'],
    ['ceph config set mon debug_mon 1/5', 'arreglo', 'Vuelve al valor por defecto en los tres a la vez: se corta el grifo.'],
    ['cd infra', '', 'La carpeta de Ansible.'],
    ['ansible ceph -b -m shell -a "truncate -s 0 /var/log/ceph/ceph-mon.*.log"', 'arreglo', 'Vacía los logs de los tres monitores de una vez, también los de ceph02 y ceph03, que iban camino de llenarse.'],
    ['ssh ceph01', '', 'Al nodo del monitor caído.'],
    ['sudo systemctl start ceph-mon@ceph01', 'arreglo', 'Con espacio, el monitor arranca y vuelve al quórum.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['ceph -s', 'comprobar', 'HEALTH_OK: tres monitores en quórum y sin avisos de disco.'],
  ],
},
'INC-4852': {
  terminos: ['openrc', 'security-group', 'terraform-state', 'drift'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales: tanto el cliente de OpenStack como el provider de Terraform las leen del entorno.'],
    ['openstack security group rule list sg-pos-backend', 'diag', 'Hay una regla 22 desde 0.0.0.0/0 y falta la de 10.20.0.0/16.'],
    ['cd infra/terraform', '', 'Terraform sólo encuentra su configuración en esta carpeta.'],
    ['terraform plan', 'diag', 'Terraform ve que ssh_admin "has been deleted" y la quiere recrear. De la regla abierta no dice nada: nunca estuvo en su estado.'],
    ['terraform apply -auto-approve', 'arreglo', 'Recrea la regla de SSH de administración.'],
    ['openstack security group rule delete <ID>', 'arreglo', 'Borra a mano la regla abierta al mundo. El ID se copia de la lista del paso 2.'],
    ['terraform plan', 'comprobar', '"No changes": lo declarado y lo real vuelven a coincidir.'],
  ],
},
'CHG-0221': {
  terminos: ['cambio', 'inventario', 'check', 'celda', 'nova-compute'],
  pasos: [
    ['cd infra', '', 'La carpeta de Ansible.'],
    ['ansible cmp04 -m ping', 'diag', 'Ansible llega al nodo y el nodo está en el inventario.'],
    ['cat playbooks/alta-compute.yml', 'diag', 'Leer antes de lanzar: el comentario de cabecera avisa de que el mapeo en la celda no lo hace el playbook.'],
    ['ansible-playbook playbooks/alta-compute.yml -l cmp04 --check', 'diag', 'Ensayo: cuenta lo que cambiaría sin tocar nada.'],
    ['ansible-playbook playbooks/alta-compute.yml -l cmp04', 'arreglo', 'Instala y arranca nova-compute, libvirt y el agente de Open vSwitch.'],
    ['ssh ctl01', '', 'nova-manage se ejecuta en un controlador.'],
    ['sudo nova-manage cell_v2 discover_hosts --verbose', 'arreglo', 'Mapea cmp04 en cell1. Sin esto, el scheduler nunca le manda una VM.'],
    ['exit', '', 'De vuelta al bastión.'],
    ['source ~/admin-openrc', '', 'Credenciales para el cliente de OpenStack.'],
    ['openstack hypervisor list', 'comprobar', 'cmp04 aparece up.'],
  ],
},
'CHG-0224': {
  terminos: ['disable-compute', 'live-migration', 'cambio', 'nova-compute'],
  pasos: [
    ['source ~/admin-openrc', '', 'Credenciales para el cliente de OpenStack.'],
    ['openstack server list --all-projects --host cmp03', 'diag', 'Siete VMs de clientes viven en cmp03.'],
    ['openstack compute service set --disable --disable-reason "CHG-0224 firmware" cmp03 nova-compute', 'arreglo', 'Saca cmp03 del scheduler: no recibirá VMs nuevas mientras lo vacías.'],
    ['nova host-evacuate-live cmp03', 'arreglo', 'Migra en vivo todas sus VMs a cmp01 y cmp02, sin apagarlas.'],
    ['openstack server list --all-projects --host cmp03', 'comprobar', 'Vacío. Ahora sí se puede reiniciar.'],
    ['ssh cmp03', '', 'Al hipervisor.'],
    ['sudo reboot', 'arreglo', 'El reinicio aplica el firmware. No queda nada dentro que apagar.'],
    ['sleep 300', '', 'Un hipervisor tarda unos 4 minutos en volver.'],
    ['openstack compute service set --enable cmp03 nova-compute', 'arreglo', 'Devuelve cmp03 al scheduler.'],
    ['openstack compute service list', 'comprobar', 'cmp03 enabled y up.'],
  ],
},
};

// ------------------------------------------------------------------ glosario
P.glosario = [
  { id: 'adhoc', t: 'Orden ad-hoc (Ansible)', d: 'Un comando suelto lanzado a muchos nodos a la vez: ansible <grupo> -m shell -a "…". Sirve para preguntar a la flota antes de cambiar nada.' },
  { id: 'alertmanager', t: 'Alertmanager', d: 'La parte de Prometheus que agrupa las alertas y avisa a la guardia. amtool alert las lista. Es lo primero que se mira: dice dónde duele antes que ningún log.' },
  { id: 'balancer', t: 'Balancer (Ceph)', d: 'Módulo del mgr que mueve PGs entre OSD hasta igualar su uso. En modo upmap lo hace con precisión. Si se apaga, el reparto natural de CRUSH deja OSD mucho más llenos que otros.' },
  { id: 'cambio', t: 'Cambio (ITIL)', d: 'Una modificación planificada y aprobada (por el CAB), con ventana y criterio de éxito. No es una incidencia: nada está roto, pero hacerlo mal puede romperlo.' },
  { id: 'celda', t: 'Celda de nova (cell_v2)', d: 'Nova agrupa sus hipervisores en celdas. Un nodo nuevo se registra solo, pero hay que mapearlo en su celda con nova-manage cell_v2 discover_hosts; hasta entonces el scheduler lo ignora.' },
  { id: 'check', t: 'Modo --check (Ansible)', d: 'Ensayo: el playbook cuenta qué cambiaría (changed) sin cambiar nada. Las tareas de tipo command se saltan, porque Ansible no puede saber qué harían.' },
  { id: 'chrony', t: 'chrony', d: 'El cliente NTP de la flota. Corrige la hora poco a poco (slew) para no dar saltos; chronyc makestep la corrige de golpe. chronyc tracking dice el desfase actual.' },
  { id: 'clock-skew', t: 'Clock skew (MON_CLOCK_SKEW)', d: 'Los monitores de Ceph necesitan la hora casi idéntica (menos de 50 ms). Si uno se desvía, el clúster avisa; si se desvía mucho, pueden perder el quórum.' },
  { id: 'cuota', t: 'Cuota (OpenStack)', d: 'Límite administrativo por proyecto: instancias, cores, RAM, gigabytes de volumen… Es lo que prometes, no lo que tienes: antes de ampliarla se mira la capacidad real.' },
  { id: 'degraded', t: 'Degraded / misplaced', d: 'Degraded: hay datos con menos copias de las debidas (peligro). Misplaced: están todas las copias pero no donde deberían (sólo hay que moverlas). ceph -s distingue los dos.' },
  { id: 'down-out', t: 'down / out (OSD)', d: 'down: el proceso no responde. out: Ceph ya no le asigna datos y reconstruye sus réplicas en otro sitio. Un OSD down pasa a out solo a los 10 minutos (mon_osd_down_out_interval), salvo con noout.' },
  { id: 'drift', t: 'Deriva (drift)', d: 'Diferencia entre lo que declara el código (Terraform, Ansible) y lo que existe de verdad, casi siempre por un cambio a mano. terraform plan la detecta, pero sólo en los recursos que conoce.' },
  { id: 'du-df', t: 'df y du', d: 'df dice cuánto espacio queda en cada sistema de ficheros; du dice qué ocupa ese espacio. Primero df para saber que está lleno, después du para saber quién lo llena.' },
  { id: 'enable-start', t: 'enable frente a start (systemd)', d: 'start arranca el servicio ahora; enable hace que arranque en cada reinicio. enable --now hace las dos cosas. Arrancado pero sin habilitar es una avería aplazada al próximo reinicio.' },
  { id: 'handler', t: 'Handler (Ansible)', d: 'Una tarea que sólo se ejecuta si otra la avisa (notify) porque ha cambiado algo. Típico: reiniciar un servicio sólo si su configuración cambió.' },
  { id: 'health', t: 'HEALTH_OK / WARN / ERR', d: 'El estado global de Ceph. WARN no significa que se pierdan datos, pero algo requiere atención; ceph health detail dice qué, línea a línea.' },
  { id: 'idempotencia', t: 'Idempotencia', d: 'Aplicar lo mismo dos veces deja el mismo resultado que aplicarlo una. Un playbook bien escrito arregla lo que está mal y no toca lo que está bien: la segunda pasada da changed=0.' },
  { id: 'inventario', t: 'Inventario (Ansible)', d: 'La lista de nodos agrupados (controllers, compute, ceph…). Los playbooks apuntan a grupos; -l limita a unos nodos concretos.' },
  { id: 'libvirt', t: 'libvirt', d: 'El demonio que maneja las máquinas virtuales KVM en cada hipervisor. nova-compute le da órdenes; sin libvirtd, nova-compute no arranca.' },
  { id: 'nearfull', t: 'nearfull / full', d: 'Umbrales de llenado de un OSD: 85 % avisa, 95 % bloquea las escrituras de todo el clúster. Cuenta el OSD más lleno, no la media: subir el umbral sólo esconde el problema.' },
  { id: 'no-valid-host', t: '"No valid host was found"', d: 'El scheduler de nova no encontró ningún hipervisor que cumpla los requisitos de la VM (RAM, CPU, disco, estar vivo y mapeado). Casi nunca es falta de hardware: es hardware no disponible para el scheduler.' },
  { id: 'noout', t: 'noout', d: 'Flag de Ceph que impide marcar out a los OSD caídos. Se pone antes de un reinicio planificado para que el clúster no empiece a mover datos, y se quita al terminar. Olvidarlo puesto impide que Ceph se cure solo.' },
  { id: 'nova-compute', t: 'nova-compute', d: 'El servicio de OpenStack que corre en cada hipervisor. Se presenta al scheduler y crea las VMs a través de libvirt. openstack compute service list dice si está up.' },
  { id: 'openrc', t: 'openrc', d: 'Fichero con las variables OS_* (URL, usuario, proyecto) que necesitan el cliente de OpenStack y el provider de Terraform. Se carga con source ~/admin-openrc en cada sesión.' },
  { id: 'osd', t: 'OSD', d: 'Object Storage Daemon: un proceso por disco que guarda los datos de Ceph. Aquí hay 9 (3 por nodo), cada dato está en 3 OSD de nodos distintos.' },
  { id: 'osd-df', t: 'ceph osd df', d: 'Uso de cada OSD. Las columnas clave son %USE, VAR (uso frente a la media) y STDDEV al pie: un VAR alto señala un OSD mucho más lleno que el resto.' },
  { id: 'pg', t: 'PG (placement group)', d: 'Ceph no reparte objetos sueltos sino grupos de objetos (PGs). Mover datos es mover PGs de un OSD a otro.' },
  { id: 'playbook', t: 'Playbook (Ansible)', d: 'Un fichero YAML que describe el estado deseado de un grupo de nodos, tarea a tarea. Deja constancia y se puede repetir: por eso los cambios de configuración van por aquí y no a mano.' },
  { id: 'rabbitmq', t: 'RabbitMQ', d: 'La cola de mensajes por la que se hablan los servicios de OpenStack. Si un nodo del clúster cae, las peticiones que pasan por él fallan con errores 500 intermitentes.' },
  { id: 'recent-crash', t: 'RECENT_CRASH', d: 'Aviso de Ceph cuando un demonio se ha caído con volcado. Sigue ahí aunque el demonio ya funcione, hasta que alguien lo lea (ceph crash info) y lo archive (ceph crash archive).' },
  { id: 'replica', t: 'Réplica 3', d: 'Cada dato se guarda tres veces en nodos distintos (size 3, min_size 2). Aguanta perder un nodo entero, pero cada GB útil ocupa 3 GB de disco.' },
  { id: 'security-group', t: 'Grupo de seguridad', d: 'El cortafuegos de OpenStack por VM: reglas de entrada y salida por puerto y rango de IPs. Una regla 0.0.0.0/0 abre ese puerto a todo internet.' },
  { id: 'smart', t: 'SMART (smartctl)', d: 'La autoevaluación del propio disco. smartctl -a da PASSED o FAILED, y contadores como sectores reasignados o pendientes. Un FAILED no se arregla reiniciando.' },
  { id: 'start-limit', t: 'Límite de arranques (systemd)', d: 'Si un servicio falla varias veces seguidas, systemd deja de intentarlo ("Start request repeated too quickly"). Hay que limpiar el contador con systemctl reset-failed antes de volver a arrancarlo.' },
  { id: 'terraform-state', t: 'Estado de Terraform', d: 'Lo que Terraform recuerda haber creado, con sus IDs. Compara ese estado con la realidad: lo que alguien creó a mano no está en el estado y para Terraform no existe.' },
  { id: 'certificado', t: 'Certificado TLS', d: 'Prueba la identidad de un servicio y cifra la conexión. Caduca a una hora exacta (notAfter), y a esa hora todos los clientes empiezan a rechazarlo. openssl x509 -noout -dates la lee.' },
  { id: 'recargar', t: 'Recargar un servicio', d: 'Muchos servicios leen su configuración y sus certificados sólo al arrancar. Cambiar el fichero no basta: hasta el reload o el restart siguen usando lo que tienen en memoria.' },
  { id: 'live-migration', t: 'Migración en vivo', d: 'Mover una VM de un hipervisor a otro sin apagarla: se copia su memoria mientras sigue funcionando. Es lo que permite reiniciar un hipervisor sin corte.' },
  { id: 'disable-compute', t: 'Deshabilitar un hipervisor', d: 'openstack compute service set --disable lo saca del scheduler: sus VMs siguen corriendo, pero no recibe ninguna nueva. Se hace antes de un mantenimiento y se deshace al terminar.' },
  { id: 'galera', t: 'Galera (MariaDB)', d: 'Clúster de MariaDB con réplica síncrona, donde escriben todos los servicios de OpenStack. Necesita mayoría: con 3 nodos aguanta perder 1. wsrep_cluster_size dice cuántos hay.' },
  { id: 'split-brain', t: 'Split-brain', d: 'Dos partes de un clúster que se creen cada una el clúster bueno y aceptan escrituras por separado. Los datos divergen y juntarlos luego es muy caro. En Galera se provoca con galera_new_cluster teniendo los otros nodos vivos.' },
  { id: 'oom', t: 'OOM killer', d: 'Cuando el kernel se queda sin memoria mata un proceso para sobrevivir: normalmente el que más ocupa, que no tiene por qué ser el culpable. Deja rastro en dmesg ("Out of memory: Killed process").' },
  { id: 'rol-admin', t: 'Roles de Keystone', d: 'member trabaja dentro de su proyecto; reader sólo mira; admin, aunque se asigne en un proyecto, da poder sobre toda la nube. Por eso admin sólo para el equipo de plataforma.' },
  { id: 'proyecto', t: 'Proyecto (Keystone)', d: 'La unidad de reparto de OpenStack: agrupa VMs, redes y volúmenes, con su cuota y sus usuarios. Lo que hay en un proyecto no se ve desde otro.' },
  { id: 'quorum', t: 'Quórum (monitores de Ceph)', d: 'Para decidir, los monitores necesitan mayoría: 2 de 3. Sin quórum el clúster no puede cambiar su mapa y los comandos ceph se quedan colgados hasta "RADOS timed out".' },
  { id: 'admin-socket', t: 'Socket de administración (ceph daemon)', d: 'Canal local con cada demonio de Ceph (/var/run/ceph/*.asok). Funciona aunque el clúster no tenga quórum: sudo ceph daemon mon.<nodo> mon_status, en su propio nodo.' },
  { id: 'fallo-latente', t: 'Fallo latente', d: 'Un fallo que no rompe nada porque la redundancia lo absorbe, y que por eso nadie arregla. Deja al sistema a un solo fallo de la caída. Un aviso de redundancia perdida es una incidencia, no ruido.' },
  { id: 'ovs', t: 'Open vSwitch', d: 'El switch virtual de cada hipervisor, que conecta las VMs a la red. El agente de neutron lo configura; sin Open vSwitch las VMs siguen ACTIVE pero sin red.' },
  { id: 'radio', t: 'Acotar el radio', d: 'Antes de arreglar, averigua a cuánto afecta: ¿una VM, un nodo, todo? Si sólo fallan las VMs de un hipervisor, el problema está en ese hipervisor.' },
  { id: 'snapshot', t: 'Copia (snapshot) de una VM', d: 'Imagen del disco de una VM en un momento dado. En OpenStack se guarda como imagen, y restaurar es crear una VM nueva desde ella.' },
  { id: 'ambito', t: 'Ámbito de proyecto', d: 'Cada orden de OpenStack actúa en un proyecto: el de las credenciales (OS_PROJECT_NAME) o el que indiques con --os-project-name. Una VM creada en el proyecto equivocado existe, pero su dueño no la ve.' },
  { id: 'rpo', t: 'RPO', d: 'Recovery Point Objective: cuántos datos puedes perder como máximo. Con una copia nocturna, hasta un día. Restaurar recupera la copia, no lo escrito después.' },
  { id: 'estado-transitorio', t: 'Estado transitorio atascado', d: '«deleting», «creating», «migrating»: estados que deberían durar segundos. Si no avanzan, casi siempre murió el servicio que tenía que terminar la operación. Primero se levanta ese servicio; después se corrige el estado.' },
  { id: 'cinder-volume', t: 'cinder-volume', d: 'El servicio de Cinder que ejecuta las operaciones de los volúmenes en el almacenamiento (aquí, Ceph). Cada volumen lo gestiona uno concreto: os-vol-host-attr:host dice cuál.' },
  { id: 'fuga-memoria', t: 'Fuga de memoria', d: 'Un proceso que reserva memoria y nunca la libera: crece sin parar hasta que el sistema se queda sin ella. Reiniciarlo la devuelve (mitigación); sólo el parche lo corrige.' },
  { id: 'instalado-corriendo', t: 'Instalado no es corriendo', d: 'Actualizar un paquete cambia los ficheros en disco, no el proceso que ya está en memoria. Hasta reiniciar el servicio (o el nodo, si es el kernel), sigue funcionando el código viejo.' },
  { id: 'rolling-restart', t: 'Reinicio de uno en uno', d: 'Reiniciar los nodos de un servicio redundante de uno en uno (serial: 1 en Ansible), para que el balanceador siempre tenga alguno sano al que mandar las peticiones.' },
  { id: 'config-central', t: 'Configuración central de Ceph', d: 'ceph config set guarda la configuración en los monitores y se aplica a todos los demonios del tipo indicado (mon, osd…), estén en el nodo que estén. ceph config dump enseña lo que difiere de los valores por defecto.' },
  { id: 'nivel-log', t: 'Nivel de log (debug)', d: 'Cuánto detalle escribe un servicio. Subirlo ayuda a depurar un rato; dejarlo subido llena discos. En Ceph, debug_mon 1/5 es lo normal y 20/20 es el máximo.' },
];

})(window.PUESTO = window.PUESTO || {});
