// Puesto · solucionario: por qué se hace cada paso, y el glosario.
//
// Los comandos NO se repiten aquí: salen del `guion` de cada escenario. Cada
// paso sólo añade la fase y la explicación, en el mismo orden. puesto-test.js
// exige que `pasos` y `guion` coincidan comando a comando, así que si alguien
// cambia un guion, el solucionario deja de pasar el test hasta que se actualice.
//
//   fase: 'diag' (mirar) · 'arreglo' (cambiar algo) · 'comprobar' · '' (moverse)
//   <ID>, <IP> en un comando = se copia de una salida anterior.
(function (P) {
'use strict';
const T = P.T;

P.soluciones = {
'INC-4821': {
  terminos: ['osd', 'health', 'down-out', 'start-limit', 'recent-crash', 'smart'],
  pasos: [
    ['ceph -s', 'diag', T('La foto general: 1 OSD down, 160 PGs degradadas y RECENT_CRASH. No se ha perdido nada: quedan dos copias de cada dato.', 'The big picture: 1 OSD down, 160 PGs degraded and RECENT_CRASH. Nothing has been lost: two copies of every piece of data remain.')],
    ['ssh ceph02', '', T('osd.4 vive en ceph02 (lo dicen la alerta y ceph osd tree). Un servicio se mira en su nodo.', 'osd.4 lives on ceph02 (the alert and ceph osd tree both say so). You inspect a service on its own node.')],
    ['journalctl -u ceph-osd@4 -n 20', 'diag', T('Tres "suicide timed out" seguidos y "Start request repeated too quickly": el proceso se colgó tres veces y systemd dejó de reintentarlo.', 'Three "suicide timed out" in a row and "Start request repeated too quickly": the process hung three times and systemd stopped retrying.')],
    ['sudo smartctl -a /dev/sdc', 'diag', T('Antes de levantarlo, descarta el hardware: osd.4 es /dev/sdc y SMART dice PASSED. Si dijera FAILED, estarías en el INC-4847.', 'Before bringing it back, rule out the hardware: osd.4 is /dev/sdc and SMART says PASSED. If it said FAILED, you would be in INC-4847.')],
    ['sudo systemctl reset-failed ceph-osd@4', 'arreglo', T('Borra el contador de arranques fallidos. Sin esto, start y restart se niegan a intentarlo.', 'Clears the failed-start counter. Without it, start and restart refuse to even try.')],
    ['sudo systemctl start ceph-osd@4', 'arreglo', T('El OSD vuelve y se pone al día con lo escrito mientras estuvo caído: una recuperación corta, sin mover datos.', 'The OSD comes back and catches up on what was written while it was down: a short recovery, with no data movement.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ceph crash ls', 'diag', T('Los tres crashes siguen marcados como nuevos (*): son lo que mantiene el HEALTH_WARN.', 'The three crashes are still flagged as new (*): they are what keeps the cluster in HEALTH_WARN.')],
    ['ceph crash archive-all', 'arreglo', T('Archivar significa "visto y documentado". No borra nada.', 'Archiving means "seen and documented". It deletes nothing.')],
    ['sleep 60', '', T('Un minuto para que termine la recuperación.', 'One minute for the recovery to finish.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK, 9 OSD up y 9 in.', 'HEALTH_OK, 9 OSDs up and 9 in.')],
  ],
},
'REQ-1307': {
  terminos: ['openrc', 'cuota', 'replica'],
  pasos: [
    ['source ~/admin-openrc', '', T('Carga las credenciales de admin: sin ellas el cliente de OpenStack no sabe a qué nube hablar.', 'Loads the admin credentials: without them the OpenStack client does not know which cloud to talk to.')],
    ['openstack quota show --usage tienda-online', 'diag', T('950 de 1000 GB usados: un volumen de 500 GB no cabe en la cuota.', '950 of 1000 GB used: a 500 GB volume does not fit in the quota.')],
    ['ceph df', 'diag', T('La cuota es una promesa; esto es lo que hay. MAX AVAIL del pool volumes (unos 1,8 TiB) confirma que hay sitio real para 500 GB más.', 'The quota is a promise; this is what actually exists. MAX AVAIL for the volumes pool (about 1.8 TiB) confirms there is real room for 500 GB more.')],
    ['openstack quota set --gigabytes 1500 tienda-online', 'arreglo', T('950 + 500 = 1450. 1500 deja margen sin regalar capacidad que no existe.', '950 + 500 = 1450. 1500 leaves headroom without handing out capacity that does not exist.')],
    ['openstack quota show tienda-online', 'comprobar', T('El nuevo límite está aplicado.', 'The new limit is in place.')],
  ],
},
'REQ-1315': {
  terminos: ['openrc', 'proyecto', 'rol-admin', 'cuota'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales de admin para el cliente de OpenStack.', 'Admin credentials for the OpenStack client.')],
    ['openstack project create --description "Franquicia Valencia" tienda-valencia', 'arreglo', T('Crea el proyecto. Nace con la cuota por defecto: 10 instancias, 20 cores y 1000 GB.', 'Creates the project. It starts with the default quota: 10 instances, 20 cores and 1000 GB.')],
    ['openstack user create --project tienda-valencia --email jgarcia@retail.es --password-prompt jgarcia', 'arreglo', T('Crea el usuario. --password-prompt pide la contraseña sin que quede en el historial ni en la lista de procesos.', 'Creates the user. --password-prompt asks for the password without leaving it in the shell history or the process list.')],
    ['Temporal-2026!', '', T('La contraseña. No se ve al escribirla.', 'The password. It is not shown as you type.')],
    ['Temporal-2026!', '', T('Repetida, para confirmar.', 'Repeated, to confirm.')],
    ['openstack role add --project tienda-valencia --user jgarcia member', 'arreglo', T('member: trabaja en su proyecto y no ve los demás. admin aquí sería admin de toda la nube.', 'member: works in their own project and cannot see the others. admin here would mean admin of the whole cloud.')],
    ['openstack role assignment list --project tienda-valencia --names', 'comprobar', T('jgarcia con member en tienda-valencia, y nada más.', 'jgarcia with member on tienda-valencia, and nothing else.')],
    ['openstack quota set --instances 10 --cores 40 --gigabytes 500 tienda-valencia', 'arreglo', T('La cuota pedida: sube lo que falta (cores de 20 a 40) y baja lo que sobra (volúmenes de 1000 a 500 GB).', 'The requested quota: raise what is short (cores from 20 to 40) and lower what is excessive (volumes from 1000 to 500 GB).')],
    ['openstack quota show tienda-valencia', 'comprobar', T('10 instancias, 40 cores y 500 GB.', '10 instances, 40 cores and 500 GB.')],
  ],
},
'INC-4830': {
  terminos: ['openrc', 'no-valid-host', 'nova-compute', 'libvirt', 'enable-start'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales para el cliente de OpenStack.', 'Credentials for the OpenStack client.')],
    ['openstack compute service list', 'diag', T('nova-compute de cmp02 está down desde ayer por la tarde.', 'nova-compute on cmp02 has been down since yesterday afternoon.')],
    ['openstack hypervisor list --long', 'diag', T('cmp01 y cmp03 casi sin RAM libre y cmp02 fuera: por eso una VM de 16 GB no cabe en ningún sitio.', 'cmp01 and cmp03 almost out of free RAM and cmp02 out of the pool: that is why a 16 GB VM fits nowhere.')],
    ['ssh cmp02', '', T('Al hipervisor que falla.', 'To the failing hypervisor.')],
    ['systemctl status nova-compute', 'diag', T('"Failed to connect socket to /var/run/libvirt/libvirt-sock": nova-compute no encuentra a libvirt, que es quien maneja las VMs.', '"Failed to connect socket to /var/run/libvirt/libvirt-sock": nova-compute cannot reach libvirt, which is what actually runs the VMs.')],
    ['sudo systemctl enable --now libvirtd', 'arreglo', T('Habilita y arranca libvirt. El enable es lo que evita que vuelva a pasar en el próximo reinicio.', 'Enables and starts libvirt. The enable is what keeps this from happening again on the next reboot.')],
    ['sudo systemctl restart nova-compute', 'arreglo', T('Ahora sí conecta con el hipervisor y vuelve a presentarse al scheduler.', 'Now it connects to the hypervisor and reports back to the scheduler.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['openstack compute service list', 'comprobar', T('cmp02 vuelve a estar up.', 'cmp02 is up again.')],
    ['openstack server delete pedidos-api-v2-01 pedidos-api-v2-02', 'arreglo', T('Limpieza que autoriza el ticket: el pipeline las volverá a crear, y ahora caben.', 'Cleanup authorized by the ticket: the pipeline will recreate them, and now they fit.')],
  ],
},
'INC-4833': {
  terminos: ['alertmanager', 'rabbitmq', 'du-df', 'playbook', 'handler'],
  pasos: [
    ['amtool alert', 'diag', T('Tres alertas, las tres en ctl02: /var al 100 %, RabbitMQ fuera del clúster y una unidad en failed.', 'Three alerts, all three on ctl02: /var at 100 %, RabbitMQ out of the cluster and a unit in failed.')],
    ['ssh ctl02', '', T('Al controlador que se queja.', 'To the controller that is complaining.')],
    ['df -h', 'diag', T('/var al 100 % y 0 libres. Sin espacio, RabbitMQ no puede ni arrancar.', '/var at 100 % with 0 free. With no space, RabbitMQ cannot even start.')],
    ['du -sh /var/log/*', 'diag', T('df dice que está lleno; du dice quién lo llena: /var/log/rabbitmq pesa 31 GB.', 'df says it is full; du says who is filling it: /var/log/rabbitmq weighs 31 GB.')],
    ['du -sh /var/log/rabbitmq/*', 'diag', T('El culpable es rabbit@ctl02.log: un log que alguien dejó en nivel debug.', 'The culprit is rabbit@ctl02.log: a log someone left at debug level.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['cd infra', '', T('ansible.cfg y el inventario viven aquí; Ansible sólo los encuentra desde esta carpeta.', 'ansible.cfg and the inventory live here; Ansible only finds them from this directory.')],
    ['ansible-playbook playbooks/logrotate.yml -l ctl02', 'arreglo', T('Pone el nivel en info (la causa), rota y comprime el log (el síntoma) y el handler reinicia RabbitMQ.', 'Sets the level to info (the cause), rotates and compresses the log (the symptom), and the handler restarts RabbitMQ.')],
    ['ssh ctl02', '', T('A comprobarlo en el nodo.', 'To check it on the node.')],
    ['sudo rabbitmqctl cluster_status', 'comprobar', T('rabbit@ctl02 vuelve a Running Nodes: el clúster tiene otra vez sus tres nodos y se acaban los 500.', 'rabbit@ctl02 is back in Running Nodes: the cluster has its three nodes again and the 500s stop.')],
  ],
},
'INC-4836': {
  terminos: ['clock-skew', 'chrony', 'alertmanager', 'adhoc', 'idempotencia'],
  pasos: [
    ['ceph health detail', 'diag', T('MON_CLOCK_SKEW en mon.ceph03: casi un segundo de desfase, veinte veces el máximo.', 'MON_CLOCK_SKEW on mon.ceph03: almost one second of drift, twenty times the maximum.')],
    ['amtool alert', 'diag', T('NodeClockNotSynchronising en ceph03… y en cmp01, que no tiene monitor de Ceph y por eso Ceph no lo ve.', 'NodeClockNotSynchronising on ceph03… and on cmp01, which has no Ceph monitor, so Ceph cannot see it.')],
    ['cd infra', '', T('La carpeta de Ansible.', 'The Ansible directory.')],
    ['ansible all -m shell -a "timedatectl | grep synchronized"', 'diag', T('Una pregunta a toda la flota a la vez: sólo ceph03 y cmp01 contestan "no".', 'One question to the whole fleet at once: only ceph03 and cmp01 answer "no".')],
    ['ansible-playbook playbooks/chrony.yml', 'arreglo', T('Arranca y habilita chrony donde falta y fuerza la sincronización (makestep). En los otros diez nodos no cambia nada.', 'Starts and enables chrony where it is missing and forces the sync (makestep). On the other ten nodes nothing changes.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK.', 'HEALTH_OK.')],
  ],
},
'INC-4840': {
  terminos: ['nearfull', 'osd-df', 'balancer', 'pg'],
  pasos: [
    ['ceph health detail', 'diag', T('OSD_NEARFULL en osd.7 y todos los pools en nearfull.', 'OSD_NEARFULL on osd.7 and every pool in nearfull.')],
    ['ceph osd df', 'diag', T('osd.7 al 87 % y el resto en torno al 57 %: VAR 1.45. Es un problema de reparto, no de capacidad.', 'osd.7 at 87 % and the rest around 57 %: VAR 1.45. It is a distribution problem, not a capacity problem.')],
    ['ceph balancer status', 'diag', T('"active": false. Nadie está repartiendo.', '"active": false. Nobody is rebalancing.')],
    ['ceph balancer on', 'arreglo', T('El balancer (modo upmap) mueve PGs hasta igualar el uso de los OSD.', 'The balancer (upmap mode) moves PGs until OSD usage evens out.')],
    ['sleep 420', '', T('El reparto tarda unos minutos.', 'Rebalancing takes a few minutes.')],
    ['ceph osd df', 'comprobar', T('osd.7 vuelve a la media y STDDEV baja.', 'osd.7 is back to the average and STDDEV drops.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK.', 'HEALTH_OK.')],
  ],
},
'INC-4861': {
  terminos: ['certificado', 'recargar', 'playbook', 'handler'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales para el cliente de OpenStack.', 'Credentials for the OpenStack client.')],
    ['openstack server list --all-projects', 'diag', T('El mismo error que los pipelines: CERTIFICATE_VERIFY_FAILED, certificate has expired.', 'The same error the pipelines get: CERTIFICATE_VERIFY_FAILED, certificate has expired.')],
    ['curl -I https://api.retail.local:5000', 'diag', T('Confirmado sin el cliente de por medio: "SSL certificate problem: certificate has expired".', 'Confirmed without the client in the way: "SSL certificate problem: certificate has expired".')],
    ['ssh ctl01', '', T('ctl01 tiene la VIP (keepalived): su HAProxy es el que contesta.', 'ctl01 holds the VIP (keepalived): its HAProxy is the one answering.')],
    ['openssl x509 -in /etc/haproxy/certs/api.pem -noout -dates', 'diag', T('notAfter es hoy a las 08:20: el fichero en disco está caducado.', 'notAfter is today at 08:20: the file on disk has expired.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['cd infra', '', T('La carpeta de Ansible.', 'The Ansible directory.')],
    ['ansible-playbook playbooks/certs.yml', 'arreglo', T('Copia el certificado renovado a los tres controladores, y el handler recarga HAProxy en cada uno.', 'Copies the renewed certificate to the three controllers, and the handler reloads HAProxy on each one.')],
    ['openssl s_client -connect api.retail.local:5000', 'comprobar', T('Verify return code: 0 (ok), y el notAfter pasa a dentro de un año.', 'Verify return code: 0 (ok), and notAfter moves to a year from now.')],
    ['openstack server list --all-projects', 'comprobar', T('La API vuelve a responder.', 'The API responds again.')],
  ],
},
'INC-4866': {
  terminos: ['galera', 'oom', 'split-brain', 'alertmanager'],
  pasos: [
    ['amtool alert', 'diag', T('GaleraClusterSizeLow en ctl01 y ctl02, y mariadb en failed en ctl03.', 'GaleraClusterSizeLow on ctl01 and ctl02, and mariadb in failed on ctl03.')],
    ['ssh ctl01', '', T('A un nodo sano.', 'To a healthy node.')],
    ["sudo mysql -e \"SHOW STATUS LIKE 'wsrep_cluster_size'\"", 'diag', T('2: el clúster sigue vivo y con quórum, pero le falta ctl03.', '2: the cluster is still alive and has quorum, but ctl03 is missing.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ssh ctl03', '', T('Al nodo caído.', 'To the node that is down.')],
    ['sudo dmesg | tail -n 5', 'diag', T('"Out of memory: Killed process … (mariadbd)": lo mató el OOM killer, no un fallo de la base de datos.', '"Out of memory: Killed process … (mariadbd)": the OOM killer took it out, not a database failure.')],
    ['systemctl status mariadb', 'diag', T('failed (Result: oom-kill). Nada le impide volver a arrancar.', 'failed (Result: oom-kill). Nothing prevents it from starting again.')],
    ['sudo systemctl start mariadb', 'arreglo', T('Arranque normal: se une al clúster vivo y recibe lo que se perdió mientras estaba fuera (IST).', 'A normal start: it joins the live cluster and receives what it missed while it was out (IST).')],
    ["sudo mysql -e \"SHOW STATUS LIKE 'wsrep_%'\"", 'comprobar', T('wsrep_cluster_size = 3, Synced, y las tres IPs en wsrep_incoming_addresses.', 'wsrep_cluster_size = 3, Synced, and all three IPs in wsrep_incoming_addresses.')],
  ],
},
'INC-4875': {
  terminos: ['radio', 'ovs', 'nova-compute'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales para el cliente de OpenStack.', 'Credentials for the OpenStack client.')],
    ['openstack server show web-tienda-01', 'diag', T('ACTIVE y en cmp01: para nova la VM está bien. Apunta su IP.', 'ACTIVE and on cmp01: as far as nova knows, the VM is fine. Note its IP.')],
    ['ping <IP>', 'diag', T('web-tienda-01 no responde.', 'web-tienda-01 does not respond.')],
    ['ping <IP>', 'diag', T('web-tienda-02, que vive en cmp02, sí responde: el problema está en un hipervisor, no en toda la red.', 'web-tienda-02, which lives on cmp02, does respond: the problem is on one hypervisor, not the whole network.')],
    ['openstack network agent list', 'diag', T('El agente de Open vSwitch de cmp01 aparece XXX.', 'The Open vSwitch agent on cmp01 shows XXX.')],
    ['ssh cmp01', '', T('Al hipervisor afectado.', 'To the affected hypervisor.')],
    ['systemctl status neutron-openvswitch-agent', 'diag', T('No consigue conectar con unix:/var/run/openvswitch/db.sock: Open vSwitch no está corriendo.', 'It cannot connect to unix:/var/run/openvswitch/db.sock: Open vSwitch is not running.')],
    ['sudo systemctl start openvswitch-switch', 'arreglo', T('Primero la base: Open vSwitch. El bloqueo que dejó la actualización ya se ha liberado.', 'The foundation first: Open vSwitch. The lock left by the upgrade has already been released.')],
    ['sudo systemctl restart neutron-openvswitch-agent', 'arreglo', T('Después el agente, que ahora sí encuentra a Open vSwitch y reconstruye los puertos de las VMs.', 'Then the agent, which can now find Open vSwitch and rebuilds the VM ports.')],
    ['sudo ovs-vsctl show', 'comprobar', T('br-int conectado (is_connected: true) y un puerto tap por cada VM de cmp01.', 'br-int connected (is_connected: true) and one tap port for each VM on cmp01.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ping <IP>', 'comprobar', T('web-tienda-01 vuelve a responder.', 'web-tienda-01 responds again.')],
  ],
},
'REQ-1319': {
  terminos: ['snapshot', 'ambito', 'rpo', 'openrc'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales de admin.', 'Admin credentials.')],
    ['openstack server list --project tienda-online', 'diag', T('Queda redis-carrito-01; redis-carrito-02 ya no existe.', 'redis-carrito-01 is still there; redis-carrito-02 no longer exists.')],
    ['openstack image list', 'diag', T('Las copias nocturnas: la más reciente de redis-carrito-02 es la de 20260923, de las 03:00.', 'The nightly backups: the most recent one of redis-carrito-02 is from 20260923, at 03:00.')],
    ['openstack image show backup-redis-carrito-02-20260923', 'diag', T('Sus propiedades guardan cómo era la VM original: m1.medium, retail-net y proyecto tienda-online.', 'Its properties record what the original VM looked like: m1.medium, retail-net and project tienda-online.')],
    ['openstack --os-project-name tienda-online server create --flavor m1.medium --image backup-redis-carrito-02-20260923 --network retail-net redis-carrito-02', 'arreglo', T('La VM nueva, desde la copia y en su proyecto, con el mismo flavor y la misma red.', 'The new VM, from the backup and in its own project, with the same flavor and the same network.')],
    ['sleep 60', '', T('Un minuto para que arranque.', 'One minute for it to boot.')],
    ['openstack server show redis-carrito-02', 'comprobar', T('ACTIVE, en tienda-online y con la imagen de la copia.', 'ACTIVE, in tienda-online and running the backup image.')],
  ],
},
'INC-4880': {
  terminos: ['estado-transitorio', 'cinder-volume', 'openrc', 'cuota'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales para el cliente de OpenStack.', 'Credentials for the OpenStack client.')],
    ['openstack volume list --all-projects', 'diag', T('pedidos-db-old, 400 GB, en deleting.', 'pedidos-db-old, 400 GB, in deleting.')],
    ['openstack volume show pedidos-db-old', 'diag', T('os-vol-host-attr:host = ctl02@rbd-1: es el cinder-volume de ctl02 quien tenía que terminar el borrado. updated_at es de ayer.', 'os-vol-host-attr:host = ctl02@rbd-1: the cinder-volume on ctl02 was supposed to finish the deletion. updated_at is from yesterday.')],
    ['openstack volume service list', 'diag', T('cinder-volume de ctl02@rbd-1: down desde ayer por la tarde.', 'cinder-volume on ctl02@rbd-1: down since yesterday afternoon.')],
    ['ssh ctl02', '', T('Al controlador que tiene el servicio caído.', 'To the controller with the failed service.')],
    ['systemctl status cinder-volume', 'diag', T('"RADOS timed out": perdió la conexión con Ceph en mitad del borrado y murió.', '"RADOS timed out": it lost its connection to Ceph in the middle of the deletion and died.')],
    ['sudo systemctl restart cinder-volume', 'arreglo', T('Ceph ya responde: el servicio vuelve a arrancar.', 'Ceph is responding now: the service starts again.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['openstack volume set --state error pedidos-db-old', 'arreglo', T('Un volumen en deleting no admite otro borrado. Pasarlo a error lo desbloquea: es la forma de decir «esto se quedó a medias».', 'A volume in deleting will not accept another delete. Setting it to error unblocks it: it is how you say "this was left half done".')],
    ['openstack volume delete pedidos-db-old', 'arreglo', T('Ahora sí hay un cinder-volume vivo que lo termine.', 'Now there is a live cinder-volume to finish it.')],
    ['sleep 60', '', T('Un minuto para que cinder-volume lo borre en Ceph.', 'One minute for cinder-volume to delete it in Ceph.')],
    ['openstack volume list --project tienda-online', 'comprobar', T('pedidos-db-old ya no está.', 'pedidos-db-old is gone.')],
    ['openstack quota show --usage tienda-online', 'comprobar', T('gigabytes en uso: de 1000 a 600. Ya pueden crear el volumen nuevo.', 'gigabytes in use: from 1000 down to 600. They can create the new volume now.')],
  ],
},
'INC-4884': {
  terminos: ['fuga-memoria', 'instalado-corriendo', 'rolling-restart', 'oom'],
  pasos: [
    ['amtool alert', 'diag', T('NodeMemoryHighUtilization en ctl03, al 92 %.', 'NodeMemoryHighUtilization on ctl03, at 92 %.')],
    ['ssh ctl03', '', T('Al controlador que se está quedando sin memoria.', 'To the controller that is running out of memory.')],
    ['free -h', 'diag', T('Cuánto: más de 110 de 128 GB usados.', 'How much: more than 110 of 128 GB in use.')],
    ['ps aux --sort=-rss | head -5', 'diag', T('Quién: nova-api con más de 60 GB de memoria residente. Normalmente ocupa uno.', 'Who: nova-api with more than 60 GB of resident memory. It normally takes one.')],
    ['apt list --upgradable', 'diag', T('Hay una versión nueva de nova: 29.2.1.', 'There is a new version of nova: 29.2.1.')],
    ['apt changelog nova-api', 'diag', T('"Fix memory leak in nova-api when listing servers with many ports (LP: #2071234)": es exactamente esto.', '"Fix memory leak in nova-api when listing servers with many ports (LP: #2071234)": that is exactly this.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['cd infra', '', T('La carpeta de Ansible.', 'The Ansible directory.')],
    ['ansible-playbook playbooks/nova-patch.yml', 'arreglo', T('Instala la 29.2.1 y reinicia nova-api en los tres controladores, de uno en uno: la API nunca se queda sin servicio.', 'Installs 29.2.1 and restarts nova-api on the three controllers, one at a time: the API is never left without service.')],
    ['ssh ctl03', '', T('A comprobarlo.', 'To check it.')],
    ['free -h', 'comprobar', T('La memoria vuelve a su sitio, y con el parche cargado ya no volverá a subir.', 'Memory is back to normal, and with the patch loaded it will not climb again.')],
  ],
},
'CHG-0218': {
  terminos: ['cambio', 'noout', 'down-out', 'playbook'],
  pasos: [
    ['ceph -s', 'diag', T('El punto de partida está sano. Un cambio no empieza sobre un clúster degradado.', 'The starting point is healthy. A change never begins on a degraded cluster.')],
    ['cd infra', '', T('La carpeta de Ansible.', 'The Ansible directory.')],
    ['ansible-playbook playbooks/os-update.yml -l ceph02', 'arreglo', T('Instala el kernel nuevo en ceph02. A propósito no reinicia: eso va aparte y con cuidado.', 'Installs the new kernel on ceph02. It deliberately does not reboot: that is a separate, careful step.')],
    ['ansible-playbook playbooks/ceph-reboot.yml -l ceph02', 'arreglo', T('Comprueba HEALTH_OK, pone noout, reinicia, espera a los OSD y a la recuperación, y quita noout.', 'Checks HEALTH_OK, sets noout, reboots, waits for the OSDs and the recovery, and unsets noout.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK y sin flags.', 'HEALTH_OK and no flags.')],
    ['ssh ceph02', '', T('Al nodo parcheado.', 'To the patched node.')],
    ['uname -r', 'comprobar', T('5.15.0-122-generic: el kernel nuevo está cargado.', '5.15.0-122-generic: the new kernel is loaded.')],
  ],
},
'INC-4847': {
  terminos: ['noout', 'down-out', 'smart', 'osd', 'recent-crash', 'degraded'],
  pasos: [
    ['ceph health detail', 'diag', T('Dos líneas clave: OSD_DOWN (osd.7) y OSDMAP_FLAGS (noout). La segunda explica por qué Ceph no se ha curado solo.', 'Two key lines: OSD_DOWN (osd.7) and OSDMAP_FLAGS (noout). The second explains why Ceph has not healed itself.')],
    ['ceph osd metadata 7', 'diag', T('osd.7 está en ceph03, disco sdc, con su número de serie: lo que necesita hardware para cambiarlo.', 'osd.7 is on ceph03, disk sdc, with its serial number: what the hardware team needs to replace it.')],
    ['ssh ceph03', '', T('Al nodo del disco.', 'To the disk\'s node.')],
    ['sudo smartctl -a /dev/sdc', 'diag', T('SMART FAILED: el disco está muerto. No se reinicia: se saca y se cambia.', 'SMART FAILED: the disk is dead. You do not restart it: you pull it and replace it.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ceph crash ls', 'diag', T('El crash de osd.7 al fallar la lectura.', 'The osd.7 crash when the read failed.')],
    ['ceph osd unset noout', 'arreglo', T('Quita el flag olvidado del cambio de anoche.', 'Removes the flag left over from last night\'s change.')],
    ['ceph osd out 7', 'arreglo', T('Saca el OSD ya, sin esperar: Ceph empieza a reconstruir sus réplicas en los otros ocho.', 'Takes the OSD out right away, without waiting: Ceph starts rebuilding its replicas on the other eight.')],
    ['sleep 600', '', T('La reconstrucción tarda unos minutos.', 'The rebuild takes a few minutes.')],
    ['ceph crash archive-all', 'arreglo', T('Crash leído y archivado.', 'Crash read and archived.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK con 8 OSD up y 8 in. Queda abrir el ticket a hardware para /dev/sdc de ceph03.', 'HEALTH_OK with 8 OSDs up and 8 in. What is left is opening the hardware ticket for /dev/sdc on ceph03.')],
  ],
},
'INC-4871': {
  terminos: ['quorum', 'admin-socket', 'fallo-latente', 'start-limit', 'enable-start', 'recent-crash'],
  pasos: [
    ['amtool alert', 'diag', T('CephHealthError con MON_DOWN y ceph-mon@ceph03 en failed: el clúster ha perdido el quórum.', 'CephHealthError with MON_DOWN and ceph-mon@ceph03 in failed: the cluster has lost quorum.')],
    ['ssh ceph01', '', T('Al único monitor que sigue vivo.', 'To the only monitor still alive.')],
    ['sudo ceph daemon mon.ceph01 mon_status', 'diag', T('"state": "probing" y quorum vacío: ceph01 está solo, buscando a los demás. El socket responde aunque ceph -s se cuelgue.', '"state": "probing" and an empty quorum: ceph01 is alone, looking for the others. The socket answers even when ceph -s hangs.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ssh ceph03', '', T('Al monitor caído hoy.', 'To the monitor that went down today.')],
    ['systemctl status ceph-mon@ceph03', 'diag', T('Un fallo de Paxos tres veces seguidas y "Start request repeated too quickly": systemd ha dejado de intentarlo.', 'A Paxos failure three times in a row and "Start request repeated too quickly": systemd has stopped trying.')],
    ['sudo systemctl reset-failed ceph-mon@ceph03', 'arreglo', T('Limpia el contador de arranques fallidos.', 'Clears the failed-start counter.')],
    ['sudo systemctl start ceph-mon@ceph03', 'arreglo', T('Con ceph01 y ceph03 ya son 2 de 3: vuelve el quórum.', 'With ceph01 and ceph03 that makes 2 of 3: quorum is back.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ssh ceph02', '', T('Al monitor que lleva días fuera.', 'To the monitor that has been out for days.')],
    ['journalctl -u ceph-mon@ceph02 -n 5', 'diag', T('"systemctl disable --now ceph-mon@ceph02" hace tres días, durante el CHG-0215. Nadie lo volvió a encender.', '"systemctl disable --now ceph-mon@ceph02" three days ago, during CHG-0215. Nobody turned it back on.')],
    ['sudo systemctl enable --now ceph-mon@ceph02', 'arreglo', T('Habilitado y arrancado: vuelven a ser tres.', 'Enabled and started: three again.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ceph crash archive-all', 'arreglo', T('El crash de mon.ceph03, leído y archivado.', 'The mon.ceph03 crash, read and archived.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK y quórum de ceph01, ceph02 y ceph03.', 'HEALTH_OK and a quorum of ceph01, ceph02 and ceph03.')],
  ],
},
'INC-4889': {
  terminos: ['config-central', 'nivel-log', 'du-df', 'adhoc', 'quorum'],
  pasos: [
    ['ceph health detail', 'diag', T('MON_DOWN (ceph01) y MON_DISK_LOW en ceph02: el problema no es sólo de un nodo.', 'MON_DOWN (ceph01) and MON_DISK_LOW on ceph02: the problem is not limited to one node.')],
    ['ssh ceph01', '', T('Al nodo del monitor caído.', 'To the node with the failed monitor.')],
    ['df -h', 'diag', T('/ al 100 %.', '/ at 100 %.')],
    ['sudo du -sh /var/log/ceph/*', 'diag', T('ceph-mon.ceph01.log pesa 35 GB: un monitor escribiendo en debug.', 'ceph-mon.ceph01.log weighs 35 GB: a monitor logging at debug level.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ceph config dump', 'diag', T('mon · debug_mon · 20/20: alguien lo subió para depurar y nunca lo bajó. Afecta a los tres monitores.', 'mon · debug_mon · 20/20: someone raised it to debug and never lowered it. It affects all three monitors.')],
    ['ceph config set mon debug_mon 1/5', 'arreglo', T('Vuelve al valor por defecto en los tres a la vez: se corta el grifo.', 'Back to the default on all three at once: the tap is turned off.')],
    ['cd infra', '', T('La carpeta de Ansible.', 'The Ansible directory.')],
    ['ansible ceph -b -m shell -a "truncate -s 0 /var/log/ceph/ceph-mon.*.log"', 'arreglo', T('Vacía los logs de los tres monitores de una vez, también los de ceph02 y ceph03, que iban camino de llenarse.', 'Empties the logs of all three monitors in one go, including ceph02 and ceph03, which were on their way to filling up.')],
    ['ssh ceph01', '', T('Al nodo del monitor caído.', 'To the node with the failed monitor.')],
    ['sudo systemctl start ceph-mon@ceph01', 'arreglo', T('Con espacio, el monitor arranca y vuelve al quórum.', 'With space available, the monitor starts and rejoins the quorum.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['ceph -s', 'comprobar', T('HEALTH_OK: tres monitores en quórum y sin avisos de disco.', 'HEALTH_OK: three monitors in quorum and no disk warnings.')],
  ],
},
'INC-4852': {
  terminos: ['openrc', 'security-group', 'terraform-state', 'drift'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales: tanto el cliente de OpenStack como el provider de Terraform las leen del entorno.', 'Credentials: both the OpenStack client and the Terraform provider read them from the environment.')],
    ['openstack security group rule list sg-pos-backend', 'diag', T('Hay una regla 22 desde 0.0.0.0/0 y falta la de 10.20.0.0/16.', 'There is a port 22 rule from 0.0.0.0/0 and the one for 10.20.0.0/16 is missing.')],
    ['cd infra/terraform', '', T('Terraform sólo encuentra su configuración en esta carpeta.', 'Terraform only finds its configuration in this directory.')],
    ['terraform plan', 'diag', T('Terraform ve que ssh_admin "has been deleted" y la quiere recrear. De la regla abierta no dice nada: nunca estuvo en su estado.', 'Terraform sees that ssh_admin "has been deleted" and wants to recreate it. It says nothing about the open rule: it was never in its state.')],
    ['terraform apply -auto-approve', 'arreglo', T('Recrea la regla de SSH de administración.', 'Recreates the admin SSH rule.')],
    ['openstack security group rule delete <ID>', 'arreglo', T('Borra a mano la regla abierta al mundo. El ID se copia de la lista del paso 2.', 'Deletes the world-open rule by hand. Copy the ID from the list in step 2.')],
    ['terraform plan', 'comprobar', T('"No changes": lo declarado y lo real vuelven a coincidir.', '"No changes": what is declared and what exists match again.')],
  ],
},
'CHG-0221': {
  terminos: ['cambio', 'inventario', 'check', 'celda', 'nova-compute'],
  pasos: [
    ['cd infra', '', T('La carpeta de Ansible.', 'The Ansible directory.')],
    ['ansible cmp04 -m ping', 'diag', T('Ansible llega al nodo y el nodo está en el inventario.', 'Ansible reaches the node, and the node is in the inventory.')],
    ['cat playbooks/alta-compute.yml', 'diag', T('Leer antes de lanzar: el comentario de cabecera avisa de que el mapeo en la celda no lo hace el playbook.', 'Read before you run: the header comment warns that the playbook does not do the cell mapping.')],
    ['ansible-playbook playbooks/alta-compute.yml -l cmp04 --check', 'diag', T('Ensayo: cuenta lo que cambiaría sin tocar nada.', 'A dry run: it reports what would change without touching anything.')],
    ['ansible-playbook playbooks/alta-compute.yml -l cmp04', 'arreglo', T('Instala y arranca nova-compute, libvirt y el agente de Open vSwitch.', 'Installs and starts nova-compute, libvirt and the Open vSwitch agent.')],
    ['ssh ctl01', '', T('nova-manage se ejecuta en un controlador.', 'nova-manage runs on a controller.')],
    ['sudo nova-manage cell_v2 discover_hosts --verbose', 'arreglo', T('Mapea cmp04 en cell1. Sin esto, el scheduler nunca le manda una VM.', 'Maps cmp04 into cell1. Without this, the scheduler never sends it a VM.')],
    ['exit', '', T('De vuelta al bastión.', 'Back to the bastion.')],
    ['source ~/admin-openrc', '', T('Credenciales para el cliente de OpenStack.', 'Credentials for the OpenStack client.')],
    ['openstack hypervisor list', 'comprobar', T('cmp04 aparece up.', 'cmp04 shows up.')],
  ],
},
'CHG-0224': {
  terminos: ['disable-compute', 'live-migration', 'cambio', 'nova-compute'],
  pasos: [
    ['source ~/admin-openrc', '', T('Credenciales para el cliente de OpenStack.', 'Credentials for the OpenStack client.')],
    ['openstack server list --all-projects --host cmp03', 'diag', T('Siete VMs de clientes viven en cmp03.', 'Seven customer VMs live on cmp03.')],
    ['openstack compute service set --disable --disable-reason "CHG-0224 firmware" cmp03 nova-compute', 'arreglo', T('Saca cmp03 del scheduler: no recibirá VMs nuevas mientras lo vacías.', 'Takes cmp03 out of the scheduler: it will not receive new VMs while you drain it.')],
    ['nova host-evacuate-live cmp03', 'arreglo', T('Migra en vivo todas sus VMs a cmp01 y cmp02, sin apagarlas.', 'Live-migrates all its VMs to cmp01 and cmp02, without shutting them down.')],
    ['openstack server list --all-projects --host cmp03', 'comprobar', T('Vacío. Ahora sí se puede reiniciar.', 'Empty. Now it is safe to reboot.')],
    ['ssh cmp03', '', T('Al hipervisor.', 'To the hypervisor.')],
    ['sudo reboot', 'arreglo', T('El reinicio aplica el firmware. No queda nada dentro que apagar.', 'The reboot applies the firmware. There is nothing left inside to shut down.')],
    ['sleep 300', '', T('Un hipervisor tarda unos 4 minutos en volver.', 'A hypervisor takes about 4 minutes to come back.')],
    ['openstack compute service set --enable cmp03 nova-compute', 'arreglo', T('Devuelve cmp03 al scheduler.', 'Puts cmp03 back in the scheduler.')],
    ['openstack compute service list', 'comprobar', T('cmp03 enabled y up.', 'cmp03 enabled and up.')],
  ],
},
};

// ------------------------------------------------------------------ glosario
P.glosario = [
  { id: 'adhoc', t: T('Orden ad-hoc (Ansible)', 'Ad-hoc command (Ansible)'), d: T('Un comando suelto lanzado a muchos nodos a la vez: ansible <grupo> -m shell -a "…". Sirve para preguntar a la flota antes de cambiar nada.', 'A one-off command sent to many nodes at once: ansible <group> -m shell -a "…". Useful for asking the fleet a question before changing anything.') },
  { id: 'alertmanager', t: 'Alertmanager', d: T('La parte de Prometheus que agrupa las alertas y avisa a la guardia. amtool alert las lista. Es lo primero que se mira: dice dónde duele antes que ningún log.', 'The part of Prometheus that groups alerts and notifies the on-call engineer. amtool alert lists them. It is the first thing you check: it tells you where it hurts before any log does.') },
  { id: 'balancer', t: 'Balancer (Ceph)', d: T('Módulo del mgr que mueve PGs entre OSD hasta igualar su uso. En modo upmap lo hace con precisión. Si se apaga, el reparto natural de CRUSH deja OSD mucho más llenos que otros.', 'An mgr module that moves PGs between OSDs until their usage evens out. In upmap mode it does so precisely. If it is off, CRUSH\'s natural distribution leaves some OSDs much fuller than others.') },
  { id: 'cambio', t: T('Cambio (ITIL)', 'Change (ITIL)'), d: T('Una modificación planificada y aprobada (por el CAB), con ventana y criterio de éxito. No es una incidencia: nada está roto, pero hacerlo mal puede romperlo.', 'A planned, approved modification (by the CAB), with a window and success criteria. It is not an incident: nothing is broken, but doing it wrong can break something.') },
  { id: 'celda', t: T('Celda de nova (cell_v2)', 'Nova cell (cell_v2)'), d: T('Nova agrupa sus hipervisores en celdas. Un nodo nuevo se registra solo, pero hay que mapearlo en su celda con nova-manage cell_v2 discover_hosts; hasta entonces el scheduler lo ignora.', 'Nova groups its hypervisors into cells. A new node registers itself, but it has to be mapped into its cell with nova-manage cell_v2 discover_hosts; until then the scheduler ignores it.') },
  { id: 'check', t: T('Modo --check (Ansible)', '--check mode (Ansible)'), d: T('Ensayo: el playbook cuenta qué cambiaría (changed) sin cambiar nada. Las tareas de tipo command se saltan, porque Ansible no puede saber qué harían.', 'A dry run: the playbook reports what it would change (changed) without changing anything. command tasks are skipped, because Ansible cannot know what they would do.') },
  { id: 'chrony', t: 'chrony', d: T('El cliente NTP de la flota. Corrige la hora poco a poco (slew) para no dar saltos; chronyc makestep la corrige de golpe. chronyc tracking dice el desfase actual.', 'The fleet\'s NTP client. It corrects the clock gradually (slew) to avoid jumps; chronyc makestep corrects it in one step. chronyc tracking shows the current offset.') },
  { id: 'clock-skew', t: 'Clock skew (MON_CLOCK_SKEW)', d: T('Los monitores de Ceph necesitan la hora casi idéntica (menos de 50 ms). Si uno se desvía, el clúster avisa; si se desvía mucho, pueden perder el quórum.', 'Ceph monitors need nearly identical clocks (less than 50 ms apart). If one drifts, the cluster warns; if it drifts a lot, they can lose quorum.') },
  { id: 'cuota', t: T('Cuota (OpenStack)', 'Quota (OpenStack)'), d: T('Límite administrativo por proyecto: instancias, cores, RAM, gigabytes de volumen… Es lo que prometes, no lo que tienes: antes de ampliarla se mira la capacidad real.', 'An administrative limit per project: instances, cores, RAM, volume gigabytes… It is what you promise, not what you have: before raising it, check the real capacity.') },
  { id: 'degraded', t: 'Degraded / misplaced', d: T('Degraded: hay datos con menos copias de las debidas (peligro). Misplaced: están todas las copias pero no donde deberían (sólo hay que moverlas). ceph -s distingue los dos.', 'Degraded: some data has fewer copies than it should (danger). Misplaced: all the copies exist but not where they should be (they just need to be moved). ceph -s tells the two apart.') },
  { id: 'down-out', t: 'down / out (OSD)', d: T('down: el proceso no responde. out: Ceph ya no le asigna datos y reconstruye sus réplicas en otro sitio. Un OSD down pasa a out solo a los 10 minutos (mon_osd_down_out_interval), salvo con noout.', 'down: the process is not responding. out: Ceph no longer assigns it data and rebuilds its replicas elsewhere. A down OSD is marked out automatically after 10 minutes (mon_osd_down_out_interval), unless noout is set.') },
  { id: 'drift', t: T('Deriva (drift)', 'Drift'), d: T('Diferencia entre lo que declara el código (Terraform, Ansible) y lo que existe de verdad, casi siempre por un cambio a mano. terraform plan la detecta, pero sólo en los recursos que conoce.', 'The difference between what the code declares (Terraform, Ansible) and what actually exists, almost always because of a manual change. terraform plan detects it, but only for the resources it knows about.') },
  { id: 'du-df', t: T('df y du', 'df and du'), d: T('df dice cuánto espacio queda en cada sistema de ficheros; du dice qué ocupa ese espacio. Primero df para saber que está lleno, después du para saber quién lo llena.', 'df tells you how much space is left on each filesystem; du tells you what is using that space. First df to learn it is full, then du to learn who is filling it.') },
  { id: 'enable-start', t: T('enable frente a start (systemd)', 'enable vs. start (systemd)'), d: T('start arranca el servicio ahora; enable hace que arranque en cada reinicio. enable --now hace las dos cosas. Arrancado pero sin habilitar es una avería aplazada al próximo reinicio.', 'start starts the service now; enable makes it start on every boot. enable --now does both. Started but not enabled is a failure postponed until the next reboot.') },
  { id: 'handler', t: 'Handler (Ansible)', d: T('Una tarea que sólo se ejecuta si otra la avisa (notify) porque ha cambiado algo. Típico: reiniciar un servicio sólo si su configuración cambió.', 'A task that only runs when another task notifies it (notify) because something changed. Typical use: restart a service only if its configuration changed.') },
  { id: 'health', t: 'HEALTH_OK / WARN / ERR', d: T('El estado global de Ceph. WARN no significa que se pierdan datos, pero algo requiere atención; ceph health detail dice qué, línea a línea.', 'Ceph\'s overall status. WARN does not mean data is being lost, but something needs attention; ceph health detail tells you what, line by line.') },
  { id: 'idempotencia', t: T('Idempotencia', 'Idempotence'), d: T('Aplicar lo mismo dos veces deja el mismo resultado que aplicarlo una. Un playbook bien escrito arregla lo que está mal y no toca lo que está bien: la segunda pasada da changed=0.', 'Applying the same thing twice gives the same result as applying it once. A well-written playbook fixes what is wrong and leaves alone what is right: the second run reports changed=0.') },
  { id: 'inventario', t: T('Inventario (Ansible)', 'Inventory (Ansible)'), d: T('La lista de nodos agrupados (controllers, compute, ceph…). Los playbooks apuntan a grupos; -l limita a unos nodos concretos.', 'The list of nodes, grouped (controllers, compute, ceph…). Playbooks target groups; -l limits them to specific nodes.') },
  { id: 'libvirt', t: 'libvirt', d: T('El demonio que maneja las máquinas virtuales KVM en cada hipervisor. nova-compute le da órdenes; sin libvirtd, nova-compute no arranca.', 'The daemon that manages the KVM virtual machines on each hypervisor. nova-compute gives it orders; without libvirtd, nova-compute does not start.') },
  { id: 'nearfull', t: 'nearfull / full', d: T('Umbrales de llenado de un OSD: 85 % avisa, 95 % bloquea las escrituras de todo el clúster. Cuenta el OSD más lleno, no la media: subir el umbral sólo esconde el problema.', 'Fill thresholds for an OSD: 85 % warns, 95 % blocks writes for the entire cluster. What counts is the fullest OSD, not the average: raising the threshold only hides the problem.') },
  { id: 'no-valid-host', t: '"No valid host was found"', d: T('El scheduler de nova no encontró ningún hipervisor que cumpla los requisitos de la VM (RAM, CPU, disco, estar vivo y mapeado). Casi nunca es falta de hardware: es hardware no disponible para el scheduler.', 'The nova scheduler found no hypervisor that meets the VM\'s requirements (RAM, CPU, disk, being alive and mapped). It is almost never a lack of hardware: it is hardware the scheduler cannot use.') },
  { id: 'noout', t: 'noout', d: T('Flag de Ceph que impide marcar out a los OSD caídos. Se pone antes de un reinicio planificado para que el clúster no empiece a mover datos, y se quita al terminar. Olvidarlo puesto impide que Ceph se cure solo.', 'A Ceph flag that prevents down OSDs from being marked out. You set it before a planned reboot so the cluster does not start moving data, and unset it when you are done. Leaving it set stops Ceph from healing itself.') },
  { id: 'nova-compute', t: 'nova-compute', d: T('El servicio de OpenStack que corre en cada hipervisor. Se presenta al scheduler y crea las VMs a través de libvirt. openstack compute service list dice si está up.', 'The OpenStack service that runs on each hypervisor. It registers with the scheduler and creates VMs through libvirt. openstack compute service list tells you whether it is up.') },
  { id: 'openrc', t: 'openrc', d: T('Fichero con las variables OS_* (URL, usuario, proyecto) que necesitan el cliente de OpenStack y el provider de Terraform. Se carga con source ~/admin-openrc en cada sesión.', 'A file with the OS_* variables (URL, user, project) that the OpenStack client and the Terraform provider need. You load it with source ~/admin-openrc in every session.') },
  { id: 'osd', t: 'OSD', d: T('Object Storage Daemon: un proceso por disco que guarda los datos de Ceph. Aquí hay 9 (3 por nodo), cada dato está en 3 OSD de nodos distintos.', 'Object Storage Daemon: one process per disk that stores Ceph\'s data. There are 9 here (3 per node), and each piece of data lives on 3 OSDs on different nodes.') },
  { id: 'osd-df', t: 'ceph osd df', d: T('Uso de cada OSD. Las columnas clave son %USE, VAR (uso frente a la media) y STDDEV al pie: un VAR alto señala un OSD mucho más lleno que el resto.', 'Usage of each OSD. The key columns are %USE, VAR (usage relative to the average) and STDDEV at the bottom: a high VAR points to an OSD much fuller than the rest.') },
  { id: 'pg', t: 'PG (placement group)', d: T('Ceph no reparte objetos sueltos sino grupos de objetos (PGs). Mover datos es mover PGs de un OSD a otro.', 'Ceph does not distribute individual objects but groups of objects (PGs). Moving data means moving PGs from one OSD to another.') },
  { id: 'playbook', t: 'Playbook (Ansible)', d: T('Un fichero YAML que describe el estado deseado de un grupo de nodos, tarea a tarea. Deja constancia y se puede repetir: por eso los cambios de configuración van por aquí y no a mano.', 'A YAML file that describes the desired state of a group of nodes, task by task. It leaves a record and can be repeated: that is why configuration changes go through here and not by hand.') },
  { id: 'rabbitmq', t: 'RabbitMQ', d: T('La cola de mensajes por la que se hablan los servicios de OpenStack. Si un nodo del clúster cae, las peticiones que pasan por él fallan con errores 500 intermitentes.', 'The message queue the OpenStack services use to talk to each other. If a cluster node goes down, requests that go through it fail with intermittent 500 errors.') },
  { id: 'recent-crash', t: 'RECENT_CRASH', d: T('Aviso de Ceph cuando un demonio se ha caído con volcado. Sigue ahí aunque el demonio ya funcione, hasta que alguien lo lea (ceph crash info) y lo archive (ceph crash archive).', 'A Ceph warning raised when a daemon has crashed with a dump. It stays even after the daemon is working again, until someone reads it (ceph crash info) and archives it (ceph crash archive).') },
  { id: 'replica', t: T('Réplica 3', 'Replica 3'), d: T('Cada dato se guarda tres veces en nodos distintos (size 3, min_size 2). Aguanta perder un nodo entero, pero cada GB útil ocupa 3 GB de disco.', 'Each piece of data is stored three times on different nodes (size 3, min_size 2). It survives losing an entire node, but every usable GB takes 3 GB of disk.') },
  { id: 'security-group', t: T('Grupo de seguridad', 'Security group'), d: T('El cortafuegos de OpenStack por VM: reglas de entrada y salida por puerto y rango de IPs. Una regla 0.0.0.0/0 abre ese puerto a todo internet.', 'OpenStack\'s per-VM firewall: inbound and outbound rules by port and IP range. A 0.0.0.0/0 rule opens that port to the entire internet.') },
  { id: 'smart', t: 'SMART (smartctl)', d: T('La autoevaluación del propio disco. smartctl -a da PASSED o FAILED, y contadores como sectores reasignados o pendientes. Un FAILED no se arregla reiniciando.', 'The disk\'s own self-assessment. smartctl -a gives PASSED or FAILED, plus counters such as reallocated or pending sectors. A FAILED is not fixed by restarting.') },
  { id: 'start-limit', t: T('Límite de arranques (systemd)', 'Start limit (systemd)'), d: T('Si un servicio falla varias veces seguidas, systemd deja de intentarlo ("Start request repeated too quickly"). Hay que limpiar el contador con systemctl reset-failed antes de volver a arrancarlo.', 'If a service fails several times in a row, systemd stops trying ("Start request repeated too quickly"). You have to clear the counter with systemctl reset-failed before starting it again.') },
  { id: 'terraform-state', t: T('Estado de Terraform', 'Terraform state'), d: T('Lo que Terraform recuerda haber creado, con sus IDs. Compara ese estado con la realidad: lo que alguien creó a mano no está en el estado y para Terraform no existe.', 'What Terraform remembers creating, with its IDs. It compares that state with reality: anything someone created by hand is not in the state, and for Terraform it does not exist.') },
  { id: 'certificado', t: T('Certificado TLS', 'TLS certificate'), d: T('Prueba la identidad de un servicio y cifra la conexión. Caduca a una hora exacta (notAfter), y a esa hora todos los clientes empiezan a rechazarlo. openssl x509 -noout -dates la lee.', 'Proves a service\'s identity and encrypts the connection. It expires at an exact time (notAfter), and at that moment every client starts rejecting it. openssl x509 -noout -dates reads it.') },
  { id: 'recargar', t: T('Recargar un servicio', 'Reloading a service'), d: T('Muchos servicios leen su configuración y sus certificados sólo al arrancar. Cambiar el fichero no basta: hasta el reload o el restart siguen usando lo que tienen en memoria.', 'Many services read their configuration and certificates only at startup. Changing the file is not enough: until a reload or restart, they keep using what they have in memory.') },
  { id: 'live-migration', t: T('Migración en vivo', 'Live migration'), d: T('Mover una VM de un hipervisor a otro sin apagarla: se copia su memoria mientras sigue funcionando. Es lo que permite reiniciar un hipervisor sin corte.', 'Moving a VM from one hypervisor to another without shutting it down: its memory is copied while it keeps running. It is what lets you reboot a hypervisor with no outage.') },
  { id: 'disable-compute', t: T('Deshabilitar un hipervisor', 'Disabling a hypervisor'), d: T('openstack compute service set --disable lo saca del scheduler: sus VMs siguen corriendo, pero no recibe ninguna nueva. Se hace antes de un mantenimiento y se deshace al terminar.', 'openstack compute service set --disable takes it out of the scheduler: its VMs keep running, but it receives no new ones. You do it before maintenance and undo it when you are done.') },
  { id: 'galera', t: 'Galera (MariaDB)', d: T('Clúster de MariaDB con réplica síncrona, donde escriben todos los servicios de OpenStack. Necesita mayoría: con 3 nodos aguanta perder 1. wsrep_cluster_size dice cuántos hay.', 'A MariaDB cluster with synchronous replication, where every OpenStack service writes. It needs a majority: with 3 nodes it survives losing 1. wsrep_cluster_size tells you how many there are.') },
  { id: 'split-brain', t: 'Split-brain', d: T('Dos partes de un clúster que se creen cada una el clúster bueno y aceptan escrituras por separado. Los datos divergen y juntarlos luego es muy caro. En Galera se provoca con galera_new_cluster teniendo los otros nodos vivos.', 'Two parts of a cluster that each believe they are the real cluster and accept writes separately. The data diverges, and merging it later is very expensive. In Galera you cause it by running galera_new_cluster while the other nodes are alive.') },
  { id: 'oom', t: 'OOM killer', d: T('Cuando el kernel se queda sin memoria mata un proceso para sobrevivir: normalmente el que más ocupa, que no tiene por qué ser el culpable. Deja rastro en dmesg ("Out of memory: Killed process").', 'When the kernel runs out of memory, it kills a process to survive: usually the largest one, which is not necessarily the culprit. It leaves a trace in dmesg ("Out of memory: Killed process").') },
  { id: 'rol-admin', t: T('Roles de Keystone', 'Keystone roles'), d: T('member trabaja dentro de su proyecto; reader sólo mira; admin, aunque se asigne en un proyecto, da poder sobre toda la nube. Por eso admin sólo para el equipo de plataforma.', 'member works inside their project; reader only looks; admin, even when assigned on a project, grants power over the whole cloud. That is why admin is only for the platform team.') },
  { id: 'proyecto', t: T('Proyecto (Keystone)', 'Project (Keystone)'), d: T('La unidad de reparto de OpenStack: agrupa VMs, redes y volúmenes, con su cuota y sus usuarios. Lo que hay en un proyecto no se ve desde otro.', 'OpenStack\'s unit of tenancy: it groups VMs, networks and volumes, with its own quota and users. What is in one project cannot be seen from another.') },
  { id: 'quorum', t: T('Quórum (monitores de Ceph)', 'Quorum (Ceph monitors)'), d: T('Para decidir, los monitores necesitan mayoría: 2 de 3. Sin quórum el clúster no puede cambiar su mapa y los comandos ceph se quedan colgados hasta "RADOS timed out".', 'To make decisions, the monitors need a majority: 2 of 3. Without quorum the cluster cannot change its map and ceph commands hang until "RADOS timed out".') },
  { id: 'admin-socket', t: T('Socket de administración (ceph daemon)', 'Admin socket (ceph daemon)'), d: T('Canal local con cada demonio de Ceph (/var/run/ceph/*.asok). Funciona aunque el clúster no tenga quórum: sudo ceph daemon mon.<nodo> mon_status, en su propio nodo.', 'A local channel to each Ceph daemon (/var/run/ceph/*.asok). It works even when the cluster has no quorum: sudo ceph daemon mon.<node> mon_status, on the daemon\'s own node.') },
  { id: 'fallo-latente', t: T('Fallo latente', 'Latent failure'), d: T('Un fallo que no rompe nada porque la redundancia lo absorbe, y que por eso nadie arregla. Deja al sistema a un solo fallo de la caída. Un aviso de redundancia perdida es una incidencia, no ruido.', 'A failure that breaks nothing because redundancy absorbs it, and that nobody fixes for that very reason. It leaves the system one failure away from an outage. A lost-redundancy warning is an incident, not noise.') },
  { id: 'ovs', t: 'Open vSwitch', d: T('El switch virtual de cada hipervisor, que conecta las VMs a la red. El agente de neutron lo configura; sin Open vSwitch las VMs siguen ACTIVE pero sin red.', 'The virtual switch on each hypervisor that connects the VMs to the network. The neutron agent configures it; without Open vSwitch the VMs stay ACTIVE but have no network.') },
  { id: 'radio', t: T('Acotar el radio', 'Narrowing the blast radius'), d: T('Antes de arreglar, averigua a cuánto afecta: ¿una VM, un nodo, todo? Si sólo fallan las VMs de un hipervisor, el problema está en ese hipervisor.', 'Before fixing anything, find out how far it reaches: one VM, one node, everything? If only the VMs on one hypervisor are failing, the problem is on that hypervisor.') },
  { id: 'snapshot', t: T('Copia (snapshot) de una VM', 'VM backup (snapshot)'), d: T('Imagen del disco de una VM en un momento dado. En OpenStack se guarda como imagen, y restaurar es crear una VM nueva desde ella.', 'An image of a VM\'s disk at a given moment. In OpenStack it is stored as an image, and restoring means creating a new VM from it.') },
  { id: 'ambito', t: T('Ámbito de proyecto', 'Project scope'), d: T('Cada orden de OpenStack actúa en un proyecto: el de las credenciales (OS_PROJECT_NAME) o el que indiques con --os-project-name. Una VM creada en el proyecto equivocado existe, pero su dueño no la ve.', 'Every OpenStack command acts on a project: the one in your credentials (OS_PROJECT_NAME) or the one you pass with --os-project-name. A VM created in the wrong project exists, but its owner cannot see it.') },
  { id: 'rpo', t: 'RPO', d: T('Recovery Point Objective: cuántos datos puedes perder como máximo. Con una copia nocturna, hasta un día. Restaurar recupera la copia, no lo escrito después.', 'Recovery Point Objective: the maximum amount of data you can afford to lose. With a nightly backup, up to a day. Restoring brings back the backup, not what was written after it.') },
  { id: 'estado-transitorio', t: T('Estado transitorio atascado', 'Stuck transitional state'), d: T('«deleting», «creating», «migrating»: estados que deberían durar segundos. Si no avanzan, casi siempre murió el servicio que tenía que terminar la operación. Primero se levanta ese servicio; después se corrige el estado.', '"deleting", "creating", "migrating": states that should last seconds. If they do not move, the service that had to finish the operation almost always died. First bring that service back; then fix the state.') },
  { id: 'cinder-volume', t: 'cinder-volume', d: T('El servicio de Cinder que ejecuta las operaciones de los volúmenes en el almacenamiento (aquí, Ceph). Cada volumen lo gestiona uno concreto: os-vol-host-attr:host dice cuál.', 'The Cinder service that carries out volume operations on the storage backend (Ceph, here). Each volume is managed by one specific instance: os-vol-host-attr:host tells you which.') },
  { id: 'fuga-memoria', t: T('Fuga de memoria', 'Memory leak'), d: T('Un proceso que reserva memoria y nunca la libera: crece sin parar hasta que el sistema se queda sin ella. Reiniciarlo la devuelve (mitigación); sólo el parche lo corrige.', 'A process that allocates memory and never frees it: it grows nonstop until the system runs out. Restarting it gives the memory back (mitigation); only the patch fixes it.') },
  { id: 'instalado-corriendo', t: T('Instalado no es corriendo', 'Installed is not running'), d: T('Actualizar un paquete cambia los ficheros en disco, no el proceso que ya está en memoria. Hasta reiniciar el servicio (o el nodo, si es el kernel), sigue funcionando el código viejo.', 'Upgrading a package changes the files on disk, not the process already in memory. Until you restart the service (or the node, if it is the kernel), the old code keeps running.') },
  { id: 'rolling-restart', t: T('Reinicio de uno en uno', 'Rolling restart'), d: T('Reiniciar los nodos de un servicio redundante de uno en uno (serial: 1 en Ansible), para que el balanceador siempre tenga alguno sano al que mandar las peticiones.', 'Restarting the nodes of a redundant service one at a time (serial: 1 in Ansible), so the load balancer always has a healthy one to send requests to.') },
  { id: 'config-central', t: T('Configuración central de Ceph', 'Ceph centralized configuration'), d: T('ceph config set guarda la configuración en los monitores y se aplica a todos los demonios del tipo indicado (mon, osd…), estén en el nodo que estén. ceph config dump enseña lo que difiere de los valores por defecto.', 'ceph config set stores configuration in the monitors and applies it to every daemon of the given type (mon, osd…), whatever node it is on. ceph config dump shows what differs from the defaults.') },
  { id: 'nivel-log', t: T('Nivel de log (debug)', 'Log level (debug)'), d: T('Cuánto detalle escribe un servicio. Subirlo ayuda a depurar un rato; dejarlo subido llena discos. En Ceph, debug_mon 1/5 es lo normal y 20/20 es el máximo.', 'How much detail a service writes. Raising it helps you debug for a while; leaving it raised fills disks. In Ceph, debug_mon 1/5 is normal and 20/20 is the maximum.') },
];

})(window.PUESTO = window.PUESTO || {});
